### PR TITLE
WIP: Use POSIX sh instead of GNU Bash

### PR DESCRIPTION
**Pull request by yukiisbored**
Closes https://github.com/cuberite/cuberite/issues/4296

### CODE REVIEW

**Comment by yukiisbored** [comment]
I wanna add ShellCheck to be part of the CircleCI pipeline to ensure POSIX compliance

**Comment by bearbin** [comment]
How is this PR coming along, will you be able to complete it soon?

**Comment by yukiisbored** [comment]
Le Monday 24 September 2018 à 13:31 -0700, Alexander Harkness a écrit :
> How is this PR coming along, will you be able to complete it soon?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 

Currently busy IRL, I'll find some time this weekend.

**Comment by bearbin** [comment]
Closing as completely stale.

**Pull request closed without merging**
