### PR TITLE
Don't feed golden apple in creative mode

### PR DESCRIPTION
**Pull request by Lightn1ng**
Fixes issue #3627

Took me 3 pull requests to eventually realize that it doesn't work with trailing whitespace

Ryan El Kochta <ryane512@gmail.com>

### CODE REVIEW

**Comment by Lightn1ng** [comment]
well, crap. I have had 4 tries to get the code styling just right. 4th times a charm?

**Comment by worktycho** [comment]
Locking at this its making me wonder why on earth the Golden Apple Eating code calls cPlayer::Feed directly rather than delegating to the parent which would fix this problem. Also the current behavior for cuberite is that it lets you eat, but doesn't take the item. Is there a scenario where that could behave differently?

**Comment by Lightn1ng** [comment]
@worktycho Interesting because the other foods that give effects are spider eyes and rotten flesh, and they're handled normally in ItemFood.h

**Comment by worktycho** [comment]
I think its because unlike spider eyes and rotten flesh the golden apple gives at least two status effects. And the current GetEatEffect API can only handle one effect.

**Comment by Lightn1ng** [comment]
@worktycho I'll look into maybe making another api for multiple status effects. Not necessarily aware how to make 1 function to either apply multiple or one.

**Comment by lkolbly** [comment]
What's the status of this? Asking because, in fixing pufferfish, I got rid of the entire GetEatEffect API in PR #3875 and replaced it with how golden apples do it - i.e., directly calling AddEatEffect from EatItem. So that PR and this PR have some things in common.

**Comment by Lightn1ng** [comment]
@lkolbly still not been merged. These people don't seem to like PRs.

_Sent from my Samsung SM-G900V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by madmaxoft** [comment]
Sorry for the delay.

I wouldn't mind merging this, but @worktycho had some concerns, so it's up to him to decide if they have been "addressed enough", or we'll ignore them for now, or something else.

**Comment by worktycho** [comment]
It fixes the problem, but only by fixing the symptom, not that actual root cause which #3875 is addressing, so I prefer that approach.

**Comment by madmaxoft** [comment]
I assume this PR is no longer needed?

**Comment by worktycho** [comment]
Should not be.

**Pull request closed without merging**
