### PR TITLE
LuaTCPLink: Report data received via SSL just before connection closed.

### PR DESCRIPTION
**Pull request by madmaxoft**
DO NOT MERGE YET, this is for shared testing.

@LogicParrot edit:
Binaries for testing
 - [Windows x64](https://builds.cuberite.org/job/Cuberite%20Windows%20x64%20pr-testing/1/artifact/Install/Cuberite.zip)
 - [Gnu/Linux x64](https://builds.cuberite.org/job/Cuberite%20Linux%20x64%20pr-testing/1/artifact/Cuberite.tar.gz)

### CODE REVIEW

**Comment by madmaxoft** [comment]
@NiLSPACE does this fix your HTTPS download issues? And does it output the log message `Leftover data in SSL context, flushing.`? (debug-mode only)

**Comment by NiLSPACE** [comment]
I've tried it, but it doesn't receive any data:
```
     [dec3d1ad2a06c22|15:46:03] Executing console command: "load WorldEdit"
     [dec3d1ad2a06c22|15:46:03] [WorldEdit] Enabling WorldEdit v0.1.1
     [dec3d1ad2a06c22|15:46:03] Plugin loaded
Info [9a36935c4af72867|15:46:03] Connecting
Info [9a36935c4af72867|15:47:04] Connection closed
Info [9a36935c4af72867|15:47:04] Connecting
Info [9a36935c4af72867|15:48:05] Connection closed
Info [9a36935c4af72867|15:48:05] Connecting
Info [9a36935c4af72867|15:49:06] Connection closed
Info [9a36935c4af72867|15:49:06] Connecting
Info [9a36935c4af72867|15:50:07] Connection closed
Warn [9a36935c4af72867|15:50:07] Could not connect to Github to check for a newer version for WorldEdit
```

I've noticed this before at my internship (where I've done this test). Only sometimes it actually gets through. This also happens allot back home, but it happens way more here. As you can see the connection is closed exactly one minute after it is started.

Here is the used connection code just to see where I got the LOGINFO's:
```lua
OnConnected = function(a_TCPLink)
		local res, msg = a_TCPLink:StartTLSClient("", "", "")
		LOGINFO("Connecting")
		a_TCPLink:Send("GET /cuberite/WorldEdit/master/Info.lua HTTP/1.1\r\nHost: raw.githubusercontent.com\r\nConnection: Close\r\n\r\n")
	end,
	
	OnError = function(a_TCPLink, a_ErrorCode, a_ErrorMsg) 
		LOGINFO("Error")
		LOGWARNING("Error while checking for newer WorldEdit version: " .. a_ErrorMsg)
	end,
	
	OnReceivedData = function(a_TCPLink, a_Data)
		LOGINFO("Receiving Data")
		g_PluginInfo = g_PluginInfo .. a_Data
	end,
	
	OnRemoteClosed = function(a_TCPLink)
		LOGINFO("Connection closed")
		cUpdater:ParseResults()
	end,
```

I'll reload the plugin a few times to see if I can get it to connect at least once.

**Comment by madmaxoft** [comment]
Looks as if the problem was elsewhere - with an exact minute before the disconnect, I'd venture a guess that Cuberite isn't actually sending the HTTP request, so the Mojang server just times out the connection without ever replying anything.

Might be interesting to replicate this behavior against a HTTPS server for which we have a certificate and dissect the traffic with wireshark, to see if it really is the case.

**Comment by NiLSPACE** [comment]
You could use the gallery's webadmin to do that.

**Comment by NiLSPACE** [comment]
Interesting. I decided to speed things up by putting the request in a for-loop that is 15 long. I finally got it to receive something back, but apparently it decided to merge two requests in one.
[RawOutput.txt](https://github.com/cuberite/cuberite/files/96084/RawOutput.txt)

**Comment by madmaxoft** [comment]
You're not resetting the `g_PluginInfo` variable, so it's possible it got data from multiple requests.

**Comment by NiLSPACE** [comment]
But it's only writing to `RawOutput.txt` if the file doesn't exist yet, so only the first request that receives data should be written.

**Comment by LogicParrot** [comment]
I added the relevant CI binaries so that others can test without compiling.

**Comment by madmaxoft** [comment]
This is not really testable in-game.
Anyway, I believe this change is valid, even if it doesn't fix the immediate problem, it makes the code more resistant. I have removed the debug logging and rebased onto master, I suggest we merge this in.

**Comment by NiLSPACE** [comment]
Yes, I agree.

**Pull request merged**
