### PR TITLE
Added MAINTAINERS file

### PR DESCRIPTION
**Pull request by SphinxC0re**

### CODE REVIEW

**Comment by bearbin** [comment]
What is the point of this?

**Comment by SphinxC0re** [comment]
I though it would be useful. Other projects also maintain such a file. Why do you think it wouldn't?

**Comment by SphinxC0re** [comment]
I'm adding all the core team members while we should discuss about the use of this

**Comment by bearbin** [comment]
I guess I don't see the point of this file any more than the existing CONTRIBUTORS file. We have a group email support@cuberite.org, and the core team is listed in the github org.

**Comment by SphinxC0re** [comment]
Okay :disappointed:

**Comment by SafwatHalaby** [comment]
Can I be added to the group mail?

**Comment by SphinxC0re** [comment]
@madmaxoft could do that. Also what about a policy to set the support mail address as cc when answering a support mail?

**Comment by bearbin** [comment]
I don't think the group mail is working at the moment. But that would be a good policy, so we can know what the others are saying.

**Comment by SafwatHalaby** [comment]
Only 4 people are publicly listed as the Cuberite team at Github. Check out https://github.com/orgs/cuberite/people without logging in. The unlisted ones are all those who have a "collaborator" status, and those who have "owner" status but have their privacy setting set to "private".

**Pull request closed without merging**
