### PR TITLE
Added more information about contributing to Cuberite

### PR DESCRIPTION
**Pull request by Woazboat**
Added a paragraph about contributing to Cuberite, as well as a link to a github tutorial to CONTRIBUTING.md

The CONTRIBUTING file was severely lacking in actual information about the contribution process, even though it's the first place someone would check to get more information about contributing.

Also added a 'PRs welcome' badge to the readme.

### CODE REVIEW

**Comment by bearbin** [comment]
I think the paragraph you added to the CONTRIBUTING file is great, not so sure about the PRs welcome badge - what's the point?

**Comment by Woazboat** [comment]
No particular reason, it's just a non-intrusive way to inform people that contributions to the project are welcome. I can remove it if you want, or change it to point to the CONTRIBUTING document.

**Comment by madmaxoft** [comment]
The badge link doesn't provide much information, instead I feel drowned by nonsense. I think making it point to the CONTRIBUTING file is a much better idea.

**Comment by tigerw** [comment]
Badges are an essential part of any project.

Research shows that startups who do not incorporate the liberal use of badges into their philosophy typically have a MTTF (mean time-to-failure) of much less<sup>[\[qualification needed\]](https://en.wikipedia.org/wiki/Template:Clarify)</sup> that their counterparts.<sup>[\[citation needed\]](https://en.wikipedia.org/wiki/Wikipedia:Citation_needed)</sup>

**Comment by Woazboat** [comment]
Removed the badge to unrustle some Jimmies

**Pull request merged**
