### PR TITLE
Fixed failed assertation

### LINKED ISSUE #2336: Assertion failed and deadlock
```
     [8dbf2be8|01:28:24] Chunk generator performance: 20.13 ch / sec (32 ch total)
     [8dbf2be8|01:28:24] Generating chunk [-16, -11]
     [8dbf2be8|01:28:24] Generating chunk [-16, -12]
     [8dbf2be8|01:28:24] Generating chunk [-16, -13]
     [ab0b5525|01:28:24] Spawning cZombiePigman #2637 at {-212, 37, -110}
Err  [ab0b5525|01:28:25] Assertion failed: !"cChunkData::GetMeta(): coords out of chunk range!", file D:\Projects\C++\Cuberite\src\ChunkData.cpp, line 315
Err  [69b63c0d|01:28:45] Deadlock detected, aborting the server
Err  [69b63c0d|01:28:45] Assertion failed: !"Deadlock detected", file D:\Projects\C++\Cuberite\src\DeadlockD
```

### PR DESCRIPTION
**Pull request by bibo38**
This was caused by a monster with a negative Y-position.
Fixes #2336

### CODE REVIEW

**Comment by worktycho** [comment]
I think the key question is why the y position is negative in the first place.

**Comment by madmaxoft** [comment]
Even the way to fix is needlessly complicated. It's preferred to use negative-bailout:
```cpp
if (GetY() < 0)
{
  return;
}
// original code
```

**Comment by bibo38** [comment]
@worktycho A Mob falling out of the world could be a case of a negative y position. Also this happened to Mobs in the nether sometimes(maybe a generator/spawn failure?)

@madmaxoft I didn't used this fast bailout, because i didn't wanted to bail out the HandleFalling, ... routines when the mob is in the void. By moving the ai and burning to the end the behaviour would change slightly.

**Comment by madmaxoft** [comment]
But you've structured the code exactly well for a fast bailout. I has a huge conditional block that terminates at function end.

**Comment by tigerw** [comment]
Xoft, there appears to be more code in Tick than the changes view suggests.

**Comment by madmaxoft** [comment]
Ah, I've missed that.

**Comment by SphinxC0re** [comment]
Update? :point_left:

**Comment by bearbin** [comment]
Rebase and merge?

**Comment by bibo38** [comment]
I'll rebase this tomorrow.

**Comment by bibo38** [comment]
Now it is rebased

**Pull request merged**
