### PR TITLE
Revert "Changed cPath to have a reset method".

### LINKED ISSUE #2784: Mob path recalc acting weird
~~Possibly~~ introduced in https://github.com/cuberite/cuberite/commit/2c0ca0b4c3152765f97e9bb3894b55694e979f32

Mobs are sometimes going to the wrong spot (Looks like a spot they have been in before). More info soon.

### PR DESCRIPTION
**Pull request by SafwatHalaby**
Fixes #2784

### CODE REVIEW

**Comment by SafwatHalaby** [comment]
Fixes #2784

**Comment by SafwatHalaby** [comment]
is Appveyor stuck?

**Comment by madmaxoft** [comment]
It says "cancelled", I'll restart the job.

**Comment by SafwatHalaby** [comment]
Thank you. Merge ASAP when this compiles.

**Comment by Seadragon91** [comment]
Still not started...

**Pull request merged**
