### PR TITLE
Re-implement up/down placement metadata

### LINKED ISSUE #4651: Rethink the method on how to rotate blocks on placing them
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: c9a9b3c9d0d4fed0b02d9935923bfd7dcbc45d1e

### Expected behavior
Blocks are placed on the server exactly as the client would expect them to be placed.

### Actual behavior
The rotation of a block depends serversided only on the angle the player is looking when a block is placed - if it is above or below 50 degrees.
So this issue just exists so everyone could provide an idea. :) If there is such a thing like an "not very important" - tag: apply it to this one please :)

I am currently on it to do some testing and math and research and stuff to figure out, what other factors are important for the placement of the blocks when playing singleplayer for instance.

(Is there any way to read the rotation the clients wants the block to have?)

### Steps to reproduce the behavior
Place blocks and watch them get rotated after a split second by the server.

### Server log
```
-
```

### PR DESCRIPTION
**Pull request by tigerw**
+ Use player position when placing blocks which can face up or down, seems to better correspond to Vanilla behaviour.
* Fixes #4651

### CODE REVIEW

**Review by 12xx12 — COMMENTED** [review]
Code looks good. Don't merge yet I want to gameplay test this

**Review by bearbin — APPROVED** [review]
Looks good, but I'll wait for @12xx12 to merge after ingame testing.

**Comment by tigerw** [comment]
Did you get a chance to try the new algo?

**Review by 12xx12 — APPROVED** [review]

**Comment by 12xx12** [comment]
Yeah - another PR to merge in the block states

**Comment by tigerw** [comment]
Sorry, I have been causing a lot of merge conflicts for you recently

**Comment by 12xx12** [comment]
Yeah - I'm procatinating on going through with  the merge :D

**Pull request merged**
