### PR TITLE
Updated compile.sh script

### PR DESCRIPTION
**Pull request by Bond-009**
Changes:
* Gets number of threads on FreeBSD
* Fixes an issue where the script would return an error when you chose no compile mode
* Improves consistency
* 'Fixes' a wording issue: cores != threads
* yum -> dnf

### CODE REVIEW

**Comment by LogicParrot** [comment]
>Gets number of threads on FreeBSD

Are you sure yours is the right wording? Aren't we **getting the number of cores**, and then **choosing the number of compilation threads**? What does "getting the number of threads" mean?

**Comment by LogicParrot** [comment]
Nevermind that, I understand now. I would change `THREAD_COUNT` to `CPU_THREAD_COUNT` to avoid confusion between CPU threads and compilation threads.

**Comment by LogicParrot** [comment]
The YUM issue was not fixed.

**Comment by Bond-009** [comment]
@LogicParrot What do you mean?

**Pull request merged**
