### PR TITLE
Added detailed logging to cBlockArea::Read() bad Y coords.

### PR DESCRIPTION
**Pull request by madmaxoft**
Ref.: http://forum.mc-server.org/showthread.php?tid=2307

### CODE REVIEW

**Comment by NiLSPACE** [comment]
Perhaps we should hide these warnings in Release mode? Or we should add a debug mode for plugins where these warnings are shown. Not per-plugin, because that would be too difficult, but as a setting in the server.

**Comment by madmaxoft** [comment]
If we hid them, we'd never really get the reports and never would fix such issues. I prefer people complaining to having hidden bugs.

**Comment by NiLSPACE** [comment]
True, but if the problem is in a badly written plugin rather than the server it could get pretty annoying.

**Comment by madmaxoft** [comment]
A badly written plugin can always be fixed

**Pull request merged**
