### PR TITLE
Fix sticky piston pulling item when retracting if cycle was less than 2 ticks

### PR DESCRIPTION
**Pull request by InfRandomness**
Fixes https://github.com/cuberite/cuberite/issues/5365

### CODE REVIEW

**Comment by InfRandomness** [comment]
Fixes https://github.com/cuberite/cuberite/issues/5365

**Comment by InfRandomness** [comment]
There are still a few issues with this : 
After a few cycles of the piston extending and pushing the block, retracting and not pulling the block, then extending back, the block seems to completely disappear until logging out and back in
It also seems to happen so fast that it appears as laggy from a client

**Comment by tigerw** [comment]
Could you revert the formatting changes? The diff has a lot of noise.

**Comment by InfRandomness** [comment]
Did this work ?

**Pull request closed without merging**
