### PR TITLE
Fixed flags for ARM native debug build.

### PR DESCRIPTION
**Pull request by madmaxoft**
Also fixed indentation style in SetFlags.cmake to all-tabs.

### CODE REVIEW

**Comment by madmaxoft** [comment]
The previous master branch failed to compile on my RasPi:
```
[  0%] Building CXX object lib/jsoncpp/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o
cd /home/pi/mcs/Debug/lib/jsoncpp/src/lib_json && /usr/bin/c++   -DXML_STATIC -DLUA_USE_APICHECK -DSELF_TEST -pthread          -std=c++11 -fsigned-char -std=c++11 -Werror -Wall -Wconversion -Wshadow -Wextra -pedantic -Werror=strict-aliasing -g    -D_DEBUG;-fomit-frame-pointer    -std=c++11    -w -I/home/pi/mcs/lib/jsoncpp/include    -o CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o -c /home/pi/mcs/lib/jsoncpp/src/lib_json/json_reader.cpp
c++: fatal error: no input files
compilation terminated.
/bin/sh: 1: -fomit-frame-pointer: not found
lib/jsoncpp/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/build.make:54: recipe for target 'lib/jsoncpp/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o' failed
```

This change fixes the build.

**Comment by madmaxoft** [comment]
@zackp30 Can you please check this? It seems you are the original author of the ARM override.

**Comment by zackp30** [comment]
@madmaxoft Oops, sorry about that, I forgot to check it.

I'll check if it works on my pi when I get home from school, thanks for the headsup!

**Comment by worktycho** [comment]
Rebase and merge?

**Comment by madmaxoft** [comment]
Rebased, merge if CI succeeds.

**Pull request merged**
