### PR TITLE
Update cRankManager::SetRankVisuals

### PR DESCRIPTION
**Pull request by nicodinh**
delete LOGINFO message

### CODE REVIEW

**Comment by madmaxoft** [comment]
Why would you want to remove the message? Setting visuals for a non-existent rank should give some kind of an error.

**Comment by nicodinh** [comment]
Currently the message is displayed even if the update is done.

**Comment by madmaxoft** [comment]
Ah, of course, the update statement doesn't return a row, so the condition was wrong.
Still, I think the log message should be present for the failure case.

**Comment by madmaxoft** [comment]
Okay, can you squash the two commits into a single one?

**Comment by SphinxC0re** [comment]
Also, rebase onto current master

**Comment by nicodinh** [comment]
i'm lost, i don't know what i'm doing...

**Comment by SphinxC0re** [comment]
NOoooooooooooo, don't close

**Comment by nicodinh** [comment]
@SphinxC0re  Thanks a lot !
It's better with -f.

**Pull request merged**
