### PR TITLE
Added BACKERS to list of files in Windows build

### PR DESCRIPTION
**Pull request by mathias-github**

### CODE REVIEW

**Comment by tigerw** [comment]
I feel strongly that only the bare minimum required to bring the server up to normal functionality should be included. Therefore there should be *reductions* in what is bundled in the install package, rather than additions.

Who will be the first to bring up the licensing? :P

**Comment by mathias-github** [comment]
On the Bountysource page, the rewards section says that this file will be distributed with the binaries (it's currently included in the binaries for other OS:es). If people are against this, we should modify the text in the rewards section.

**Comment by madmaxoft** [comment]
I actually think it's only fair to add the mentions to the distributions. And there's no questions about the licenses, we are using the libraries, so the least we could do to show our appreciation is to include their license files.
It's not like those files blow up the size considerably, they're text files, after all.

**Comment by bearbin** [comment]
I don't know why the CIs didn't start, but it shouldn't have failed :P

**Comment by tigerw** [comment]
Where then, would you put this file if the server were to be installed? In the user's Documents folder? Shown at startup? Shouldn't those who wish to know consult the repository?

**Pull request merged**
