### PR TITLE
Fix style of Tools

### PR DESCRIPTION
**Pull request by bearbin**

### CODE REVIEW

**Comment by bearbin** [comment]
I'll fix the items you pointed out and have a go at getting CBS to ignore stuff in comments.

**Comment by bearbin** [comment]
I've had a look at CheckBasicStyle, and it seems like getting it to exclude stuff in comments would be a lot more work than it's worth, tbh. I think it will be staying how it is for now, by me at least.

**Comment by peterbell10** [comment]
That's a shame, maybe it would be better to look into clang-format or even a custom clang tool.  Obviously beyond the scope of this PR though.

**Comment by bearbin** [comment]
Merged manually.

**Pull request closed without merging**
