### PR TITLE
Fix door placement check / Smooth weather

### PR DESCRIPTION
**Pull request by TsFreddie**
1.The checking of the two blocks that will get replaced by the door is wrong.

2.Add weather smoothing.

3.How can I split these into two separate pull request?

### CODE REVIEW

**Comment by madmaxoft** [comment]
I'd like a verification on this. Can anyone test? Try placing doors in 3-high spaces, 2-high spaces and 1-high spaces.
I'm currently away from minecraft-able computer

**Comment by TsFreddie** [comment]
image
image


before changed, the door cannot be placed in 2-high spaces, because the code checked the upper block of the door (Y + 1) and the block above the upper block of the door (Y + 2) which should be the bottom block of the door (Y) and upper block of the door (Y + 1).

**Comment by TsFreddie** [comment]
image
another pic showing the 1-high place.

**Comment by LO1ZB** [comment]
Xoft is somewhat shadow-blind, those last 2 images are to dark. ;)

**Comment by madmaxoft** [comment]
And I meant someone else to test this independently :)

**Comment by madmaxoft** [comment]
I just with you didn't combine multiple issues into the PR. Now we can't merge the door fix because there's additional code that needs reviewing.

I'll cherry-pick your door fix, hopefully this will leave the PR with only the weather changes.

**Comment by madmaxoft** [comment]
Cherry-picked, please rebase this branch onto current master and squash the "fix" and "revert" commits.

**Comment by bearbin** [comment]
@TsFreddie Any progress on fixing the issues xoft highlighted?

**Comment by SphinxC0re** [comment]
@TsFreddie I'm closing this for now. Come back, when you fixed this.

**Pull request closed without merging**
