### PR TITLE
Fixed typo. DO NOT MERGE

### PR DESCRIPTION
**Pull request by bearbin**

### CODE REVIEW

**Comment by tigerw** [comment]
Hi @bearbot, there appears to be a typo in your message:

> Once 2maintainers

!m @bearbot!

**Comment by bearbin** [comment]
@tigerw Fixed already.

**Comment by bearbin** [comment]
@bearbot lgtm

**Comment by tigerw** [comment]
Well, the changes are technically good, and since I'm purging branches, merge?

(technically X being of course always the best kind of X)

**Comment by madmaxoft** [comment]
First rebase (and reword), then merge, if you insist

**Pull request closed without merging**
