### PR TITLE
Don't let redstone blocks power adjacent blocks.

### PR DESCRIPTION
**Pull request by QUSpilPrgm**
This fixes issue #2966

### CODE REVIEW

**Comment by QUSpilPrgm** [comment]
The style checker seems to fail because of a style violation outside of the changed files of this pull request.

**Comment by tigerw** [comment]
...it was probably me. Could you fix it quickly? :)

**Comment by QUSpilPrgm** [comment]
I have updated the code.

**Comment by bearbin** [comment]
This looks like a fairly trivial change, but I'll wait for @tigerw to approve. While you wait, do you want to add yourself to the CONTRIBUTORS file and make it clear that any copyright interest is licensed under the MIT license?

**Comment by madmaxoft** [comment]
Looks good to me, good candidate for squash-merge.

**Pull request merged**
