### PR TITLE
Improved testing framework.

### PR DESCRIPTION
**Pull request by madmaxoft**
Removed `testassert` and `CheckAsserts` in favor of `TEST_EQUAL`, `TEST_ASSERTS` et al in tests/TestHelpers.h.

Added more testing options.

### CODE REVIEW

**Comment by madmaxoft** [comment]
Not sure if we can make any library work with our custom `ASSERT`s. And it's already written :)

**Comment by peterbell10** [comment]
Would it not just be a case of
```cpp
#include <catch.hpp>
#define ASSERT REQUIRE
```

**Comment by madmaxoft** [comment]
Not really, because we want to test that the code we call raises an assert (see the `TEST_ASSERTS` macro). But that code resides in the main source tree in src/ and is not part of the test, so it must not include the test library.

**Comment by peterbell10** [comment]
I think the biggest problem with this test framework is that when multiple test-cases exist it isn't always clear which one has failed. This was a problem before as well though, so I'm fine with merging.

**Comment by madmaxoft** [comment]
Both the assertion and test exceptions now store the exact file name, line number and function name of the failure, so it should be pretty apparent where the problem is.

**Comment by peterbell10** [comment]
Unless I'm misunderstanding, when an assertion fails you can tell which assertion failed but not which test case was running when the assertion trigered.

**Comment by madmaxoft** [comment]
Hm, that's true. Perhaps next refactor :)

**Pull request merged**
