### PR TITLE
Redstone fixes

### LINKED ISSUE #3168: Crashing cuberite with a sticky piston, redstone, and a redstone block
### Expected behavior
Piston should oscillate at 1 tick, just like on bukkit, spigot, etc

### Actual behavior
Piston oscillates at intervals below 1 tick, resulting in the server crashing.
https://www.youtube.com/watch?v=h65EHBxXC2k

### Steps to reproduce the behavior
Shown in the youtube video.

### Build + Commit ID
Cuberite build id: 295
commit id: 16d53a039b2bd590989477c0f8b25acecd988417

### Similar issues
Similar to issue #3080

### PR DESCRIPTION
**Pull request by tigerw**
* Various improvements
* Fixes #3168 

Recreated from #3226.

### CODE REVIEW

**Comment by sphinxc0re** [comment]
Why are the appyeyor changes still in there? 😠

**Comment by tigerw** [comment]
Just an innocuous clone depth change.

**Comment by sphinxc0re** [comment]
It is still not in the same context as the redstone changes

**Comment by madmaxoft** [comment]
I had set the clone depth to `50` on purpose when setting up AppVeyor, it is quite necessary if there are multiple people working on the repo at the same time - if you push commit A to your PR and it starts a build, but the build is queued for a while (because another build is already running), then someone pushes commit B to another branch still before your build starts, your build will fail because it will not find the commit A anymore.

**Comment by tigerw** [comment]
In that case, perhaps I should stop saying 'innocuous'. :P

**Comment by tigerw** [comment]
Going once!

**Comment by madmaxoft** [comment]
Next time don't merge master into your branch, instead, rebase your branch onto master.

There are no non-redstone chnges in this PR, so nothing for me to review :P

**Comment by tigerw** [comment]
I was hoping that GitHub would squash everything together.

----

Ah, carte blanche I see :D

**Pull request merged**
