### PR TITLE
Prevent piston duplication

### LINKED ISSUE #4468: Piston drops cPickup of attached block ( if sticky ) or of itself on retraction
Client version:   1.12.2
Server OS:        Linux
Commit id:        a867388f6400729e2bd881f7f41c69fce130371f

### Steps to reproduce
1. Place a piston and power it. After it extends unpower it.
2. During retraction it will drop piston block, sticky piston block, or the block which was attached to the sticky piston before retraction

Screenshot from 2020-02-10 06-33-41
Screenshot from 2020-02-10 06-33-32

### Server log
```
[6297524e64d3032c|06:33:23] HandleRightClick: {22, 79, 14}, face 1, Hand: 0, HeldItem: redstonedust:0 * 1; Dist: 3.36
[6297524e64d3032c|06:33:23] Destroying entity #157 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:24] Destroying entity #158 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:24] Destroying entity #159 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:24] Destroying entity #160 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:25] Destroying entity #161 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:25] Destroying entity #162 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:26] Destroying entity #163 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:26] Destroying entity #164 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:27] Destroying entity #165 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:27] Destroying entity #166 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:27] Destroying entity #167 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:28] Destroying entity #168 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:28] Destroying entity #169 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:29] Destroying entity #170 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:29] Destroying entity #171 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:29] Destroying entity #172 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:30] Destroying entity #173 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:30] Destroying entity #174 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:31] Destroying entity #175 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:31] Destroying entity #176 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:31] Destroying entity #177 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:32] Destroying entity #178 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:32] Destroying entity #179 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:33] Destroying entity #180 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:33] Destroying entity #181 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:33] Destroying entity #182 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:34] Destroying entity #183 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:34] Destroying entity #184 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:35] Destroying entity #185 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:35] Destroying entity #186 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:35] Destroying entity #187 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:36] Destroying entity #188 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:36] Destroying entity #189 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:37] Destroying entity #190 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:37] Destroying entity #191 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:37] Destroying entity #192 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:38] Destroying entity #193 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:38] Destroying entity #194 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:39] Destroying entity #195 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:39] Destroying entity #197 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:40] Destroying entity #198 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:41] Destroying entity #199 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:41] Destroying entity #200 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:41] Destroying entity #201 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:41] Destroying entity #202 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:42] Destroying entity #203 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:42] Destroying entity #204 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:43] Destroying entity #205 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:43] Destroying entity #206 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:44] Destroying entity #207 (cPickup) from chunk (1, 1)
[6297524e64d3032c|06:33:44] HandleLeftClick: {21, 79, 18}; Face: 1; Stat: 0
```

### PR DESCRIPTION
**Pull request by mathiascode**
Fixes #4468

### CODE REVIEW

**Comment by mathiascode** [comment]
Travis has seen better days...

**Comment by bearbin** [comment]
Travis has come to its senses again, and I have restarted the failed builds.

**Comment by mathiascode** [comment]
Opinions?

**Comment by bearbin** [comment]
I don't understand the mechanism for the duplication so I can't really evaluate whether this is a good fix or not.

**Comment by mathiascode** [comment]
The change essentially disables cBlockPistonHeadHandler::OnBroken when the piston is retracting. I tried a bunch of other methods to fix the issue, but only ended up with a headache.

**Comment by peterbell10** [comment]
@madmaxoft is `cWorld::SetBlock` meant to cause item drops? I though that was what `cWorld::DigBlock` was for. 

In the piston handler, `OnDestroyed` has been renamed `OnBroken` and now drops items instead of just removing the block. That seems to be the root cause.

**Comment by mathiascode** [comment]
I played around with explosions a bit. Looks like #4418 wasn't solved.

**Comment by mathiascode** [comment]
Is there a reason simulators were not woken up in cChunkMap::SetBlockMeta, or was it just missing?

**Comment by madmaxoft** [comment]
Oh what a headache!
We've got `cWorld::SetBlock()`, `cWorld::DigBlock()` and `cWorld::DropBlockAsPickups()`. I can't really tell why `DigBlock` should be anything special other than `SetBlock(..., E_BLOCK_AIR)`.

`cWorld::SetBlock` should not create pickups. 

Pistons are tricky. Especially with their extension. If the piston is destroyed, the extension needs to be destroyed as well. How about the other way around, if the extension is destroyed, should the piston be destroyed as well? I suppose so. However, the piston retracting effectively destroys the extension.
So the extension must be able to distinguish between "retracting" and "destroying" somehow. Could it check the piston body block for that?

**Comment by mathiascode** [comment]
Don't merge this. The base should not drop if the extension is destroyed in creative mode.

I played around with ConvertToPickups for the extension earlier, but the issue with that is that we need to know if the base is a normal or sticky piston.

**Pull request closed without merging**
