### PR TITLE
WebAdmin logo improvements

### PR DESCRIPTION
**Pull request by mathiascode**
Improvements to make the WebAdmin logo render properly in some older browsers.
Screenshot

### CODE REVIEW

**Comment by madmaxoft** [comment]
What did the logo look like before this change?

**Comment by mathiascode** [comment]
https://user-images.githubusercontent.com/8754153/70290003-3d312c00-17df-11ea-8faf-35b0e27542e7.png

**Comment by madmaxoft** [comment]
So it's about the Cuberite vs Webadmin text? I don't see why Webadmin is better than Cuberite.

**Comment by mathiascode** [comment]
It was mostly a change made on the side when converting the logo to text format, but I can change the text back if people prefer that.

**Comment by bearbin** [comment]
I think I do prefer Cuberite over Webadmin, but I don't think it really matters that much.

**Pull request merged**
