### PR TITLE
Support for the 1.11 protocol

### PR DESCRIPTION
**Pull request by madmaxoft**
Basic support for the 1.11 protocol. Doesn't support mobs yet (any mob will D/C clients immediately)

Also changed the protocol classes' names for better legibility, and slightly refactored to allow simple overrides for handling incoming packets.

Ref.: #3479

### CODE REVIEW

**Comment by madmaxoft** [comment]
@NiLSPACE , @sphinxc0re , @Pokechu22 what do you think of the new class names, are they alright?

**Comment by Pokechu22** [comment]
I like the idea of naming them that way (especially for the file names), but I feel like it might be clearer to name the first versions `Protocol_1_9_0` instead of `Protocol_1_9`.  It's not to significant but I think it makes it more obvious that it's intended for the first version.  (Of course, mojang doesn't name them that way, so it can go either way)

**Comment by sphinxc0re** [comment]
I totally agree with @Pokechu22 here. The classnames are much better to read and better to distinguish

**Comment by NiLSPACE** [comment]
Yeah, the names are much better.

**Comment by madmaxoft** [comment]
I'm not too enthusiastic about `1_9_0` having the `_0` suffix, there are iterations that have only a single protocol version, so it does make sense to have the first version without any suffix and additional versions with a suffix.

**Comment by NiLSPACE** [comment]
Having no suffix could also indicate that the class is used for all 1.9 protocols, so I'm inclined to keep it with the suffix.

**Comment by madmaxoft** [comment]
The problem with that is that you don't know whether there will be a new version, until they make the next "major" update, at which point you'll be renaming the class just for the sake of the suffix.

**Comment by madmaxoft** [comment]
Okay, two against one, I'll rename the classes to include the suffix, and then I'm done with this PR :)

**Comment by NiLSPACE** [comment]
Great :)

**Comment by NiLSPACE** [comment]
Now the websites needs to be updated.

**Comment by sphinxc0re** [comment]
@mathiascode to the rescue. Also update the banner

**Comment by madmaxoft** [comment]
I wouldn't advertise 1.11 support just yet. It's very preliminary, I have a feeling that even when a second player joins the game, both players' clients will crash. I'd wait until #3479 is closed.

**Comment by mathiascode** [comment]
Once entities work fine again, I will update the website.

**Comment by NiLSPACE** [comment]
It seems the OnPlayerRightClick hook is called twice in 1.11. Is that a bug in our code or did the protocol actually change to do that?

**Pull request merged**
