### PR TITLE
Added missing hooks to cPluginManager

### PR DESCRIPTION
**Pull request by Seadragon91**

### CODE REVIEW

**Comment by NiLSPACE** [comment]
Well, they aren't actually missing, their constants are just not documented :) Good catch :+1:

**Comment by NiLSPACE** [comment]
Don't you have access to the repo directly? I thought you had.

**Comment by Seadragon91** [comment]
You mean to cuberite? No I haven't.

**Comment by NiLSPACE** [comment]
Anyone opposed to add @Seadragon91 to the organization?

**Comment by Seadragon91** [comment]
Well xoft already added me.

**Comment by NiLSPACE** [comment]
Ah, okay :)

**Pull request merged**
