### PR TITLE
Add terrain gen docs

### PR DESCRIPTION
**Pull request by madmaxoft**
Added a new section about the `Grown` biome generator, plus a program to generate the example images.

Documentation preview is available at http://cuberite.xoft.cz/docs/Generator.html

### CODE REVIEW

**Comment by Schwertspize** [comment]
Travis failes... Looks like you got serious errors in the code... (did you test it locally?)

**Comment by madmaxoft** [comment]
No, I was on a train so couldn't access any Linux box for compilation. Fixing now.

**Comment by madmaxoft** [comment]
All green now :)

**Comment by bearbin** [comment]
If this is the same changes as I previously reviewed, then they are good.

What did you think about some basic CSS for that page to make it easier to read, similar to https://book.cuberite.org?

**Comment by madmaxoft** [comment]
I have adjusted the text based on some of your notes, so it is an updated version - has a lot more pictures and examples, not to mention the basic TOC :)

Honestly, I don't like the CSS too much. Anything that constrains the contents' width to anything less than the full screen worth is, in my opinion, worthless - why have a big screen if a stupid webpage won't fit it anyway?

Still, the CSS could be changed independently of this PR - this is more about the content, while CSS is more about presentation.

**Comment by Schwertspize** [comment]
> why have a big screen if a stupid webpage won't fit it anyway?

There are surveys (and I agree personally) that text is better readable if you don't have wide lines. Have you ever seen a newspaper without columns?

**Comment by bearbin** [comment]
The changes you made are good, only thing I might do is switch the River and MixRivers pictures over, as the output from "River" is the input to "MixRivers"? Other than that, looks good to me.

**Comment by madmaxoft** [comment]
@Schwertspize If I want columns, I'll make my web browser window narrower. If I don't want columns, I want the web to allow me not to have columns.

@bearbin the operations are listed alphabetically.

**Comment by SphinxC0re** [comment]
@madmaxoft could you please rebase your changes, so we can merge this?

**Comment by madmaxoft** [comment]
Rebased

**Pull request merged**
