### PR TITLE
WebAdmin: Report opened ports.

### PR DESCRIPTION
**Pull request by madmaxoft**
Simply outputs the webadmin ports to log.

### CODE REVIEW

**Comment by madmaxoft** [comment]
Such a nice issue number and wasted for such a trivial matter :P

**Comment by tigerw** [comment]
There's always #5318008

**Comment by sphinxc0re** [comment]
or just

#01189998819991197253

**Comment by tigerw** [comment]
To be honest, judging by the number of bugs in Cuberite, that's a perfectly plausible number to reach.

#itcrowd

**Comment by LogicParrot** [comment]
That is impossible to reach regardless of the amount of bugs, because there's a leftmost zero.

*(Unless the merger of #3115 causes some spacetime rapture, making everything possible)*

**Comment by tigerw** [comment]
Curses

**Comment by Cl1608Ho** [comment]
If we skip that leftmost zero and say we create 1000 issues/pr per second (and say we are not getting rate limited by github), we would still need 37 billions of years to accomplish that. 

Although ruby might handle these things automatically (github is a rails application) this number would take up more than 64 bits to store so isn't reachable in most programming languages except for when you are working with strings. 

Also if we assume each issue takes one byte of storage (which it doesn't, even the issue number takes up more) we would still need (github needs) 275 Petabytes of storage just for that (275000 Terabyte). Let's assume each issue needs one kilobyte and you can shift each unit one up. 

And lastly, such a big issue number would probably lead to problems in the website because something like pagination isn't made for billions of pages (just because the numbers would get too long and too wide)

**Comment by tigerw** [comment]
okay okay i concede defeat already

**Comment by tigerw** [comment]
still, a bunch of large numbers don't mean something's impossible, per se

**Comment by tigerw** [comment]
maybe just... improbable

**Comment by tigerw** [comment]
though with the number of bugs we have, maybe it is, I don't know.

**Comment by bearbin** [comment]
#03333

**Comment by tigerw** [comment]
Very self-referential there.

**Pull request merged**
