### PR TITLE
Explictly link against libm

### LINKED ISSUE #4573: Build fails on linking
```
make[1]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
[  1%] Built target jsoncpp_lib_static
[  2%] Built target SQLiteCpp
[  6%] Built target zlib
[ 12%] Built target lua
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
[ 14%] Built target event_pthreads_static
[ 14%] Built target fmt
[ 14%] Built target expat
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
[ 18%] Built target event_core_static
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
[ 20%] Built target event_extra_static
[ 23%] Built target HTTPServer
[ 24%] Built target Items
[ 35%] Built target mbedcrypto
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
[ 37%] Built target Blocks
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
[ 40%] Built target Simulator
[ 43%] Built target Protocol
[ 50%] Built target Mobs
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
[ 50%] Built target IncrementalRedstoneSimulator
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
[ 50%] Built target sqlite
[ 53%] Built target UI
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
[ 56%] Built target BlockEntities
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
[ 56%] Built target luaexpat
[ 57%] Built target tolualib
[ 61%] Built target OSSupport
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
[ 63%] Built target mbedx509
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
[ 63%] Built target Noise
[ 65%] Built target WorldStorage
[ 67%] Built target mbedtls
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
[ 70%] Built target mbedTLS++
[ 74%] Built target Bindings
[ 80%] Built target Entities
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
[ 86%] Built target Generating
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[2]: Entering directory '/home/bond/dev/cuberite/Debug'
[ 86%] Linking CXX executable ../Server/Cuberite
/usr/bin/ld: CMakeFiles/Cuberite.dir/Chunk.cpp.o: in function `std::log(long double)':
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/cmath:343: undefined reference to `__logl_finite'
/usr/bin/ld: CMakeFiles/Cuberite.dir/Map.cpp.o: in function `cMap::GetPixelWidth() const':
/home/bond/dev/cuberite/src/Map.cpp:333: undefined reference to `__pow_finite'
/usr/bin/ld: Entities/libEntities.a(Entity.cpp.o): in function `_ZSt3powIiiEN9__gnu_cxx11__promote_2IT_T0_NS0_9__promoteIS2_Xsr3std12__is_integerIS2_EE7__valueEE6__typeENS4_IS3_Xsr3std12__is_integerIS3_EE7__valueEE6__typeEE6__typeES2_S3_':
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/cmath:418: undefined reference to `__pow_finite'
/usr/bin/ld: Entities/libEntities.a(Player.cpp.o): in function `std::binomial_distribution<short>::param_type::_M_initialize()':
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/random.tcc:1468: undefined reference to `__log_finite'
/usr/bin/ld: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/random.tcc:1472: undefined reference to `__log_finite'
/usr/bin/ld: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/random.tcc:1481: undefined reference to `__exp_finite'
/usr/bin/ld: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/random.tcc:1484: undefined reference to `__exp_finite'
/usr/bin/ld: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/random.tcc:1486: undefined reference to `__exp_finite'
/usr/bin/ld: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/random.tcc:1489: undefined reference to `__exp_finite'
/usr/bin/ld: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/random.tcc:1492: undefined reference to `__log_finite'
/usr/bin/ld: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/random.tcc:1494: undefined reference to `__log_finite'
/usr/bin/ld: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/random.tcc:1498: undefined reference to `__log_finite'
/usr/bin/ld: Entities/libEntities.a(Player.cpp.o): in function `short std::binomial_distribution<short>::operator()<std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul> >(std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul>&, std::binomial_distribution<short>::param_type const&)':
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/random.tcc:1585: undefined reference to `__log_finite'
/usr/bin/ld: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/random.tcc:1597: undefined reference to `__log_finite'
/usr/bin/ld: Entities/libEntities.a(Player.cpp.o):/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/random.tcc:1604: more undefined references to `__log_finite' follow
/usr/bin/ld: BlockEntities/libBlockEntities.a(NoteEntity.cpp.o): in function `cNoteEntity::MakeSound()':
/home/bond/dev/cuberite/src/BlockEntities/NoteEntity.cpp:249: undefined reference to `__pow_finite'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/CMakeFiles/Cuberite.dir/build.make:1116: Server/Cuberite] Error 1
make[2]: Leaving directory '/home/bond/dev/cuberite/Debug'
make[1]: *** [CMakeFiles/Makefile2:1372: src/CMakeFiles/Cuberite.dir/all] Error 2
make[1]: Leaving directory '/home/bond/dev/cuberite/Debug'
make: *** [Makefile:147: all] Error 2
```
Fails using Clang 9.0.1
Succeeds using gcc 9.3.0

### PR DESCRIPTION
**Pull request by peterbell10**
Intended to fix #4573

@Bond-009 can you see if this works for you?

### CODE REVIEW

**Comment by Bond-009** [comment]
Doesn't seem to work, same error

**Comment by bearbin** [comment]
What environment are you using? This is an odd error to come up when nothing's been changed for several years! (You do have the libraries installed..?)

**Comment by Bond-009** [comment]
Manjaro Linux, Clang 9.0.1, it compiles successfully when using gcc 9.3.0

**Comment by peterbell10** [comment]
Actually, I checked again and `-lm`  is included in the executable compile command line. Just isn't included in `compile_commands.json`.

**Pull request closed without merging**
