### PR TITLE
Check for invalid tags when reading a compound tag

### PR DESCRIPTION
**Pull request by worktycho**

### CODE REVIEW

**Comment by madmaxoft** [comment]
Looks good. Will you be doing anything more with this, or is this finished?

**Comment by worktycho** [comment]
That depends if my fuzzing finds any more crashes. But it hasn't found any crashes in the last four hours of running, so I don't think so.

**Comment by madmaxoft** [comment]
Wow, you're bringing some heavy guns in :)

**Comment by worktycho** [comment]
I've been wanting to try fuzzing something for a while, and the NBT parser turned out to be easy to split. I'll upload the NBT validation program I wrote that I'm actually fuzzing over the weekend. It returns a zero exit code for valid NBT, and non-zero for invalid.

**Comment by Seadragon91** [comment]
Thank you doing that :smile:

**Comment by worktycho** [comment]
If theres any other parsers that are easy to split, I'll try and fuzz them. I'd like to fuzz the protocol, but I'm not sure I can split it into a separate small program.

**Comment by madmaxoft** [comment]
Would it make sense to put the test programs into the `tests` folder and add it to the unit testing?

**Comment by worktycho** [comment]
It might do. Just take all the testcases the fuzzer has generated, and test the parser against them to ensure it doesn't crash.

**Comment by madmaxoft** [comment]
I rebased this thing on top of current master, merge if it compiles.

**Pull request merged**
