### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by birdoplank**

### CODE REVIEW

**Comment by Janmm14** [comment]
No typo fixed, just a blank line added @birdoplank

**Comment by bearbin** [comment]
Indeed, and it's a nice PR number too :( 

Closing, if this was a mistake and there is a fix, feel free to reopen.

**Comment by Janmm14** [comment]
Watching his other latest contributions it seems the account in question is SUS, PR'ing security vulnerabilities elsewhere.

**Comment by bearbin** [comment]
Yep, looking at one of his other PRs, seems like he wants to hack into our CI and do something with it...

**Comment by mathiascode** [comment]
Should we restrict CI to existing contributors? GitHub Actions does that at least, where runs have to be approved manually until a user's first PR has been merged.

**Comment by bearbin** [comment]
Yes, that would be ideal. I've never set that up (since it happily hasn't been necessary!) and it seems to be a bit of a pain to do that on Jenkins :( Maybe now's the time to migrate onto GitHub actions for our CI, it seems to have got a lot more mature in the past few years.

**Comment by 12xx12** [comment]
Or adding some binary data to the test sets that is built into the final product. xD

**Comment by mathiascode** [comment]
> Maybe now's the time to migrate onto GitHub actions for our CI, it seems to have got a lot more mature in the past few years.

I think that was suggested on Discord as well. GitHub actions has worked fine for me for several years now. For Nicotine+, I use it in combination with https://nightly.link to provide downloadable builds: https://github.com/nicotine-plus/nicotine-plus/blob/master/.github/workflows/packaging.yml

**Pull request closed without merging**
