### PR TITLE
Fixed issue #3155.

### PR DESCRIPTION
**Pull request by johnsoch**
Added fatal error messages to CMakeLists.txt for compiler version GCC < 4.8 and Clang < 3.4

### CODE REVIEW

**Comment by madmaxoft** [comment]
Apparently that doesn't work properly. Travis has Clang 3.4, yet fails the test. Similar with gcc.

Also, the message should also say "you have clang version X.Y, but at least 3.4 is needed"

**Comment by johnsoch** [comment]
Sorry, the CMAKE_CXX_COMPILER_VERSION is only available starting with CMake 2.8.8 and I didn't catch it. I also discovered that CMAKE_CXX_COMPILER_VERSION doesn't report correctly with Apple Clang on MacOS. I think I have a fix that will work, I'll do another pull request shortly.

**Comment by madmaxoft** [comment]
You don't need to make another PR, just commit to this one, we'll squash the changes in the end.

**Comment by johnsoch** [comment]
Understood, thanks! New commit is submitted, not tested on CMake 2.8.7 directly, just verified with the docs.

**Comment by johnsoch** [comment]
madmaxoft, are any other changes needed to this?

**Comment by madmaxoft** [comment]
Unfortunately now it produces a warning in MSVC:
```
-- Detecting C compiler ABI info - done
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.
cl : Command line warning D9002 : ignoring unknown option '-dumpversion'
cl : Command line error D8003 : missing source filename
```
https://ci.appveyor.com/project/madmaxoft/mcserver/build/1.0.5741 , lines 70+

It'd be great if the check was done only for the compilers for which it is needed.

**Comment by johnsoch** [comment]
No worries, @madmaxoft, I moved the GCC and Clang checks and the warning is gone.

**Comment by madmaxoft** [comment]
Thanks.

**Pull request merged**
