### PR TITLE
Adding some string utils split from loot tables

### PR DESCRIPTION
**Pull request by 12xx12**
This PR adds two string utils functions I added for the loot tables.

### CODE REVIEW

**Comment by tigerw** [comment]
I'm not yet sure how NamespaceConverter would be used, but does NamespaceSerializer::SplitNamespacedID in WorldStorage\NamespaceSerializer.h not satisfy?

**Comment by 12xx12** [comment]
It also removes "_" and so on. But yeah. I think I can make it work wir that too

**Comment by 12xx12** [comment]
I just wanted to be able to support loot tables in minecraft:naming_convention but also in CuberiteNamingConvention

**Comment by tigerw** [comment]
I'd say keep the namespaced IDs in their original form, it may confuse people if we create our own scheme.

@12xx12 would you like to close #5002 #5004, I don't mind looking at the large #4842.

**Comment by 12xx12** [comment]
Yeah we dropped the c++ parsing anyway

I'm gonna close those as soon as I did the changes to the main PR.

This week I don't have much time to finish it so this will wait until next week. Or maybe not (Corona stuff)

**Comment by tigerw** [comment]
Thanks!

**Comment by 12xx12** [comment]
Closed in favour of #4842

**Pull request closed without merging**
