### PR TITLE
Put the entire "automatic compile" script in a code block for security

### PR DESCRIPTION
**Pull request by bmintz**
This makes sure that sh will error out if the connection is interrupted.
See here: https://www.seancassidy.me/dont-pipe-to-your-shell.html

### CODE REVIEW

**Comment by madmaxoft** [comment]
Looks reasonable to me, the only concern I have is compatibility: will this work with ~~all~~ most shells?

**Comment by madmaxoft** [comment]
(also your commit message sux :P )

**Comment by bmintz** [comment]
Yup, it's [specified in POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_04).

**Comment by SphinxC0re** [comment]
@worktycho what about rebasing and squashing? It's one of the main policy's if this project.

**Comment by worktycho** [comment]
It's rate limiting, and I forgot.

**Comment by SafwatHalaby** [comment]
@bmintz Nice trick. Thank you.

**Pull request merged**
