### PR TITLE
Added gdb to travis

### PR DESCRIPTION
**Pull request by Seadragon91**
Added gdb and script commands.
Also code that crashes the server after initialized, will be removed after success.

### CODE REVIEW

**Comment by worktycho** [comment]
Why does this need the old arcitecture? the new one is faster, and tavis have indecated they will eventually close the old one.

**Comment by Seadragon91** [comment]
According to this https://github.com/travis-ci/travis-ci/issues/3754#issuecomment-95629153

The problem is we cannot change the core-pattern to core and in containers the core-pattern is changed.

Then we need to wait until travis fixes the container.

**Comment by worktycho** [comment]
Then do we really need to have core dumps on travis? It rarely dumps core in a way that cannot be dumped locally, and in my opinon we lose more from giving up container builds than we gain for getting core dumps.

**Comment by Seadragon91** [comment]
I think so, too. Just close this and if there is a fix that works in containers, then we can reopen this.

**Pull request closed without merging**
