### PR TITLE
Setting command-block's command requires a permission.

### PR DESCRIPTION
**Pull request by madmaxoft**
Fixes a possible security issue reported through the support email.

### CODE REVIEW

**Review by 12xx12 — APPROVED** [review]

**Review by bearbin — APPROVED** [review]
This looks good - do we have docs forthe commandblock.set permission?

**Comment by madmaxoft** [comment]
There's no docs, I don't know where to put it. Any ideas?
Anyway, it will mostly just work(tm), since the only people who are supposed to be able to edit commandblocks are ops, who have all permissions anyway.

**Comment by bearbin** [comment]
Yeah, probably file that one on the later list. LGTM :)

**Comment by 12xx12** [comment]
later(tm)

**Pull request merged**
