### PR TITLE
[PhantomWorlds - 5] Remove CreateAndInitializeWorld

### PR DESCRIPTION
**Pull request by LogicParrot**
Fixes part 5 of #2810.

### CODE REVIEW

**Comment by NiLSPACE** [comment]
The documentation can be removed as well.

**Comment by LogicParrot** [comment]
@NiLSPACE Done.

**Comment by NiLSPACE** [comment]
Great :). No objections here anymore.

**Comment by LogicParrot** [comment]
Note to everyone, do NOT merge this before #2961. If a player teleports to a non existing world, this will assert. #2961 prevents the server from starting if there are invalid worlds in the INI.

**Comment by LogicParrot** [comment]
I've modified `cRoot::GetWorld`, which is an API function. Is this OK? @madmaxoft

**Comment by LogicParrot** [comment]
Nevermind. The exported version ignores the second parameter, which I've removed. lgtm.

**Pull request merged**
