### PR TITLE
Readding enderman spawning

### PR DESCRIPTION
**Pull request by 12xx12**
Yeah the end stuff is getting further and the enderman are missing...

The TODO said that there should be  a bug that needs fixing. I checked with the issues. there aren't andy bugs with enderman in them

### CODE REVIEW

**Comment by KingCol13** [comment]
I just messed with them and they didn't seem to do any damage to me while they were attacking, maybe that's what it meant?

**Comment by 12xx12** [comment]
They don't even take blocks if i remember correctly... had a look in the code

**Comment by bearbin** [comment]
I think we need proper _working_ enerman AI before this can be merged in. If you want to have a go at implementing that, have at it, otherwise this should be closed.

**Comment by 12xx12** [comment]
Closing this PR. Might feeling like reopening later.

**Pull request closed without merging**
