### PR TITLE
Added PieceStructures generator.

### PR DESCRIPTION
**Pull request by madmaxoft**
DO NOT MERGE YET, this is not complete yet - it is meant as an early preview and review.

This is an addition to the structure generators that is able to generate prefab-based structures based on .cubeset files.

TODO:
 - [x] Add PieceStructures generator
 - [x] Fix up prefabs for the Villages to match the new loader requirements (`VerticalStrategy`, `VerticalLimit`, ...)
 - [x] Add the posibility to read gzipped .cubeset files.
 - [x] Change the old generators to use this structure: POCPieces, TestRails, UnderwaterBase (add more VerticalStrategies as needed)
 - [x] Add SeedOffset parameter to cubeset files
 - [x] Add documentation for the cubeset file format
 - [ ] Add documentation for the world.ini setup
 - [x] Add possibility to specify multiple instances of `PieceStructures` generator (for ordering reasons)

### CODE REVIEW

**Comment by NiLSPACE** [comment]
> Add the possibility to read gzipped .cubeset files

That shouldn't be too hard right?  Just change [this](https://github.com/cuberite/cuberite/blob/master/src/Generating/PrefabPiecePool.cpp#L174) to
```cpp
AString FileContent = InflateString(cFile:ReadWholeFile(<Path>));
if (!Lua.LoadString(FileContent))
{
   // ...
```

cLuaState:LoadString should be implemented, but that shouldn't be too hard.

**Comment by madmaxoft** [comment]
Yes, it won't be too difficult, just haven't got around to it yet.
Also, I haven't decided yet whether to make auto-detection of the file format (`.cubeset` could be both Lua or Gzip-Lua), or use an extension to differentiate between the two (`.cubeset.gz` for gzipped file).

**Comment by madmaxoft** [comment]
Gzip autodetection added, and the filename *can* have `.gz` appended to it, but it needn't. Even multiple levels of gzipping are supported :)

**Comment by madmaxoft** [comment]
I've solved the problem of ordering multiple `PieceStructure` generators: The `PieceStructures` generator may be listed multiple times in the `Finishers` section, and it should specify the prefabs to use directly in that list. Multiple prefabs can be specified, delimited by a pipe character:
```
Finishers = Trees, PieceStructures: UnderwaterBase | TreePaths, RoughRavines, PieceStructures: TestRails
```

**Comment by madmaxoft** [comment]
I had to really bump up the biome and height cache sizes, otherwise the generator would get really slow - from 30 chps to 0.2 chps.

**Comment by SphinxC0re** [comment]
Any updates on this one?

**Comment by madmaxoft** [comment]
I'm still working on it, but the free time I need to finish it is scarce.

**Comment by madmaxoft** [comment]
Since there's no place for the world.ini documentation, I think this is as much done as possible for now. How about merging?

**Comment by NiLSPACE** [comment]
Yeah, I'm all for it :)

**Comment by madmaxoft** [comment]
I'd prefer more people to have a look at this and find any oversights I might have made. @worktycho ?

**Comment by madmaxoft** [comment]
No replies, merging. I don't want to rebase yet again :P

**Pull request merged**
