### PR TITLE
Choose # of threads based on system info (compile.sh)

### LINKED ISSUE #3014: compile.sh todo
Todo:
- [ ] Ask the user about how many threads they'd like to use.  If the user does not make a choice, resort to a sane default. Perhaps using some variant [of this](https://forum.cuberite.org/thread-2332-page-2.html#pid25009).
- [ ] Add commandline arguments. This allows convenient automatic unattended updates.

### PR DESCRIPTION
**Pull request by Bond-009**
Fixes #3014

### CODE REVIEW

**Comment by LogicParrot** [comment]
I'd like to note that my system chokes on 4 threads, even though it is quad core. Perhaps check should be smarter than that and take RAM into account. Or maybe just cap it at 2 or 3.

**Comment by Bond-009** [comment]
`Maybe just cap it at 2 or 3`
The speed difference is too big to just cap it such a low value, I use 8 threads and it's waaaay faster than the old default 2 threads.

**Comment by LogicParrot** [comment]
It's better to be on the safe side and not choke people's systems. If they know their PC can handle it, they can override the default.

Or we could go the RAM checking road. But it might be overkill.

**Comment by Bond-009** [comment]
How much RAM do you have, because I run make on my VPS with 4 threads with only 2GB of RAM in total and it works fine.

**Comment by LogicParrot** [comment]
I use 4GBs of RAM. 

I am still not completely sure, but this might be a *Linux* issue. Some sources seem to indicate that Linux is not optimized for *desktops*, and when under heavy paging or IO, GUIs freeze. This is not noticable on servers.

Sources:

https://lwn.net/Articles/682582/

https://superuser.com/questions/1115983/prevent-system-freeze-unresponsiveness-due-to-swapping-run-away-memory-usage

**Comment by bearbin** [comment]
This is particularly relevant for early RasPis (~256 MiB of RAM). Even later ones would choke with 4 threads, and 2 is the max. I suggest changing the default number of threads to 1, but still allowing 'smart' choosing behind an option, e.g:

    --parallel   # runs with `CPUTHREADS` threads
    --parallel 2 # runs with 2 threads

**Comment by LogicParrot** [comment]
Whatever we do, the default shouldn't kill raspberry Pis, and the current default does. This PR needs fixing.

**Comment by LogicParrot** [comment]
I tried to run compilation on a secondary harddrive. Things are much smoother now, even with `-j4`. I speculate the compiler queues up too many writes, so paging requests and write requests of other programs have to sit in a very long queue. This is just a guess based on the above links.

**Comment by LogicParrot** [comment]
@bearbin I am working on it. Do you think Raspberry Pis should default to 1 or 2?

**Comment by bearbin** [comment]
I think the default number of threads should be 1, for maximum compatibility. The newer pies with 1GB of ram can handle 2, but not the older ones.

**Comment by bearbin** [comment]
Replaced by #3960

**Pull request merged**
