### PR TITLE
Revert Clang compiler flag that breaks OS X build

### PR DESCRIPTION
**Pull request by mjhanninen**
This is probably not the right way to fix the problem reported in #2440 but let's OS X people to build the software in the interim.

### CODE REVIEW

**Comment by tigerw** [comment]
Could you do what the other compiler flags do in this block and do a check for existence before adding? That's probably a better fix.

**Comment by tigerw** [comment]
Also, ermagherd I broke something; @SamJBarney, pitchfork please.

**Comment by mjhanninen** [comment]
Indeed, that's a lot better solution. Duh.

**Comment by SamJBarney** [comment]
@tigerw  how about an angry mob instead?
Grab a Pitchfork

**Comment by tigerw** [comment]
Aaaaah! *♪[The Simpsons...](https://www.youtube.com/watch?v=DX1iplQQJTo)♪*

**Comment by tigerw** [comment]
Squash into one commit with 2nd commit's message?

**Comment by SphinxC0re** [comment]
Also rebase onto current master

**Comment by tigerw** [comment]
I've always wondered [@SphinxC0re](http://www.crystalinks.com/sphinx3.gif), why rebase onto master if GitHub can merge into master as-is, i.e. no merge conflicts?

**Comment by worktycho** [comment]
its because with long running feature branches the merge results in a complex tree if you don't rebase first. however for a two commit PR I think we can merge this.

**Comment by tigerw** [comment]
Even if it's squashed into one commit?

**Comment by worktycho** [comment]
Yes.

Also, we really need better testing against apples clang.

**Comment by tigerw** [comment]
When I say apples you say clang!
apples clang!
apples clang!

:DD

**Comment by tigerw** [comment]
In fact, as per https://github.com/cuberite/cuberite/pull/2380/files#r37696134, the issues which the flag warns about are technically issues. Just remove the lines completely :)

**Comment by mjhanninen** [comment]
Done, squashed, and rebased.

**Pull request merged**
