### PR TITLE
MUSL stack size

### LINKED ISSUE #3406: Cuberites crashes on generating world on alpine linux
Server OS:        alpine linux
Commit id:        (be916bc7e85843291c5ab8cb4f268bd1daa57b76)
### Actual behavior

Cuberite crashes on generating the world. The stack trace makes no sense.

```
#0  0x00000dac149fe55c in cChunkDef::SetBiome (a_BiomeMap=..., a_X=0, a_Z=14, a_Biome=biTaigaHills)
    at /root/cuberite/src/ChunkDef.h:251
#1  0x00000dac14d5fef6 in cBioGenGrown::GenBiomes (this=0xdac1a3175a0, a_ChunkX=0, a_ChunkZ=-1, a_Biomes=...)
    at /root/cuberite/src/Generating/BioGen.cpp:1025
#2  0x00000dac14d55b1c in cBioGenCache::GenBiomes (this=0xdac1a51b8a0, a_ChunkX=0, a_ChunkZ=-1, a_BiomeMap=...)
    at /root/cuberite/src/Generating/BioGen.cpp:122
#3  0x00000dac14d55e71 in cBioGenMulticache::GenBiomes (this=0xdac1a3185d0, a_ChunkX=0, a_ChunkZ=-1, a_BiomeMap=...)
    at /root/cuberite/src/Generating/BioGen.cpp:171
#4  0x00000dac14d25fe0 in cBiomalNoise3DComposable::CalcBiomeParamArrays (this=0x74819dbe7030, a_ChunkX=0,
    a_ChunkZ=0, a_HeightAmp=..., a_MidPoint=...) at /root/cuberite/src/Generating/Noise3DGenerator.cpp:689
#5  0x00000dac14d258fd in cBiomalNoise3DComposable::GenerateNoiseArrayIfNeeded (this=0x74819dbe7030, a_ChunkX=0,
    a_ChunkZ=0) at /root/cuberite/src/Generating/Noise3DGenerator.cpp:629
#6  0x00000dac14d26c42 in cBiomalNoise3DComposable::GenShape (this=0x74819dbe7030, a_ChunkX=0, a_ChunkZ=0,
    a_Shape=...) at /root/cuberite/src/Generating/Noise3DGenerator.cpp:811
#7  0x00000dac14cd1739 in cComposableGenerator::DoGenerate (this=0xdac1a317520, a_ChunkX=0, a_ChunkZ=0,
    a_ChunkDesc=...) at /root/cuberite/src/Generating/ComposableGenerator.cpp:161
#8  0x00000dac14ccfd50 in cChunkGenerator::DoGenerate (this=0x74819cd3f008, a_ChunkX=0, a_ChunkZ=0)
    at /root/cuberite/src/Generating/ChunkGenerator.cpp:295
#9  0x00000dac14ccfac9 in cChunkGenerator::Execute (this=0x74819cd3f008)
    at /root/cuberite/src/Generating/ChunkGenerator.cpp:275
#10 0x00000dac14b0b8d7 in cIsThread::DoExecute (this=0x74819cd3f008) at /root/cuberite/src/OSSupport/IsThread.cpp:74
#11 0x00000dac14b0d0eb in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<, void>(cIsThread*) const (
    this=0xdac1a5b8530, __object=0x74819cd3f008) at /usr/include/c++/5.3.0/functional:600
#12 0x00000dac14b0d059 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0xdac1a5b8528) at /usr/include/c++/5.3.0/functional:1531
#13 0x00000dac14b0cf60 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0xdac1a5b8528) at /usr/include/c++/5.3.0/functional:1520
#14 0x00000dac14b0cef0 in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0xdac1a5b8510) at /usr/include/c++/5.3.0/thread:115
#15 0x000074819d787c8a in execute_native_thread_routine () from /usr/lib/libstdc++.so.6
#16 0x000074819da6d4fc in ?? () from /lib/ld-musl-x86_64.so.1
#17 0x0000000000000000 in ?? ()

```

Compiled cuberite with gcc/g++ without any problems. Maybe there are some problems with the use of musl, linking problems or missing flags.

### LINKED ISSUE #4978: Cuberite terminated by signal SIGSEGV
Client version: 1.12.3, but that's irrelevant to this issue
Server OS: Alpine Linux (uses Musl libc)
Cuberite Commit id: 6de6ac750bca2f26dd9dc425ca94e9244c340944

### Expected behavior
Cuberite to start

### Actual behavior

```
fish: './Cuberite' terminated by signal SIGSEGV (Address boundary error)
```

### Steps to reproduce the behavior

Launch Cuberite with 6de6ac750bca2f26dd9dc425ca94e9244c340944 (otherwise it won't build) on a Musl based system, e.g. an Alpine Linux docker container.

### Server log
```
> ./Cuberite 
[14:07:19] --- Started Log ---
[14:07:19] Cuberite local build (id: Unknown)
[14:07:19] from commit approx: 6de6ac750bca2f26dd9dc425ca94e9244c340944 built at: approx: 2020-10-09 13:47:24 +0200
[14:07:19] Creating new server instance...
[14:07:19] Reading server config...
[14:07:19] Regenerating settings.ini, all settings will be reset
[14:07:19] Starting server...
[14:07:19] Compatible clients: 1.8.x-1.12.x
[14:07:19] Loaded 757 crafting recipes
[14:07:19] Cannot open file "Protocol/1.14.4/base.recipes.txt", no recipe book recipes will be available!
[14:07:19] Cannot open file "Protocol/1.13/base.recipes.txt", no recipe book recipes will be available!
[14:07:19] Loaded 1.12.2 380 recipe book
[14:07:19] Loaded 67 furnace recipes and 66 fuels
[14:07:19] Loaded 49 brewing recipes
[14:07:19] Invalid biome ("BambooJungle") specified in AllowedBiomes in cubeset file Prefabs/SinglePieceStructures/JungleTemple.cubeset. Skipping the biome.
[14:07:19] Invalid biome ("BambooJungleHills") specified in AllowedBiomes in cubeset file Prefabs/SinglePieceStructures/JungleTemple.cubeset. Skipping the biome.
[14:07:19] -- Loading Plugins --
[14:07:19] Initialised Core
[14:07:19] Initialized ChatLog v.3
[14:07:19] -- Loaded 2 Plugins --
fish: './Cuberite' terminated by signal SIGSEGV (Address boundary error)
```

### PR DESCRIPTION
**Pull request by tigerw**
~~@PureTryOut could you test when you have time?~~

Fixes #4978
Fixes #3406

### CODE REVIEW

**Review by bearbin — APPROVED** [review]
This is rather a hack, and the stack size still needs to be reduced for the other beneficial reasons; but since this fixes the problem it should be merged in.

A surprising number of people use alpine!

**Comment by bearbin** [comment]
Merging, unless anyone has objections? @cuberite/core-team

**Comment by tigerw** [comment]
objection, your honor!

**Comment by bearbin** [comment]
An objection to a PR of your own creation? Of course, let me close it right out then :P

**Comment by tigerw** [comment]
objection overruled!

**Comment by PureTryOut** [comment]
I like this banter, you guys seem like a fun bunch of people :smile: 

But darn merge it already :joy:

**Pull request merged**
