### PR TITLE
Don't remove water after ice block has been destroyed

### PR DESCRIPTION
**Pull request by Seadragon91**
This would fix issue #3018. The question is now, if this is good enough or not.

### CODE REVIEW

**Comment by SphinxC0re** [comment]
Looks good to me. And well documented as well :wink:

**Comment by SphinxC0re** [comment]
Merge if CI succeeds

**Comment by SphinxC0re** [comment]
This is okay for now but when more of these 'special cases' come up, we have to think about a better way to handle them

**Comment by madmaxoft** [comment]
I'm not too happy about block-exceptions being stuffed into `cClientHandle`. Ideally, the client handle would know nothing about blocks and everything would be handled by the handlers. This points at the blockhandlers having the wrong interface.

**Comment by SphinxC0re** [comment]
I totally agree with you, but for now, this fixed a real issue for the survival game. So we should start worry about this when more of these *special cases* pop up

**Comment by Seadragon91** [comment]
@madmaxoft Would the idea to add a boolean value as return in `OnDestroyedByPlayer` fit for you?

**Comment by NiLSPACE** [comment]
@Seadragon91 That was exactly what I had in mind.

**Comment by Seadragon91** [comment]
bump
@madmaxoft return value okay for you?

**Comment by madmaxoft** [comment]
How about the digging be moved into the `OnBlockDestroyed()` handler itself?

**Pull request merged**
