### PR TITLE
Tried mapping of nether coords

### LINKED ISSUE #2541: Map nether coordinates to overworld coordinates and reverse when using portals
> Locations in the Nether correlate to Overworld coordinates, but horizontal Overworld distances are scaled down by a ratio of 8:1 for travel in the Nether. Therefore, traveling one block in the Nether means traveling eight blocks in the Overworld.

– from http://minecraft.gamepedia.com/The_Nether

So the teleport function should take the type of world the player is currently in plus his position. Then the position gets mapped onto the destination world. After this procedure, the player gets teleported

### PR DESCRIPTION
**Pull request by SphinxC0re**
I don't know if this is in any way the right way to do this, but I hope that a review will do

fixes #2541

### CODE REVIEW

**Comment by worktycho** [comment]
What about overworld to overworld portals? or Nether to Nether portals?

**Comment by SphinxC0re** [comment]
these doesn't exist in Vanilla

**Comment by SphinxC0re** [comment]
Oh :smile: I think this already happens in cEntity

**Comment by worktycho** [comment]
They may not exist in vanilla, but they are possible in cuberite.

**Comment by Seadragon91** [comment]
Well then I think, we could implement something into the api, for creating and linking portals in same worlds or other worlds. One point would be to allow to use portals to change the server (bungecoord)

**Comment by SphinxC0re** [comment]
What I meant was that this PR is obsolete due to the fact that this is already done in cEntity. I just didn't recognize

**Comment by SphinxC0re** [comment]
@Seadragon91 exporting portal linkage to the API might be a good idea though

**Pull request closed without merging**
