### PR TITLE
Don't assert when placing beds in older versions

### PR DESCRIPTION
**Pull request by mathiascode**

### CODE REVIEW

**Comment by madmaxoft** [comment]
Does this actually work with the older clients? Shouldn't the protocol code just bail out without sending anything?

**Comment by mathiascode** [comment]
When I placed different variants of beds in older clients, the beds were always red, but had the correct color in 1.12.

**Comment by Seadragon91** [comment]
I guess we can merge as the assert will only occur in debug mode.

**Comment by mathiascode** [comment]
What do you want?

**Comment by madmaxoft** [comment]
I think it's okay as-is

**Pull request merged**
