### PR TITLE
Chickens shouldn't take fall damage

### PR DESCRIPTION
**Pull request by Gargaj**
Also needs an exception at https://github.com/cuberite/cuberite/blob/master/src/Entities/Entity.cpp#L931 for the falling speed to be exempted from gravity, but I don't know the actual numbers.

### CODE REVIEW

**Comment by NiLSPACE** [comment]
I could be completely wrong, but doesn't the `HandleFalling` handle the actual falling of an entity, not the damage?

**Comment by Gargaj** [comment]
Not as far as I can tell? https://github.com/cuberite/cuberite/blob/master/src/Mobs/Monster.cpp#L565

**Comment by madmaxoft** [comment]
Looks good to me. Could be extended to ocelots, too.

**Comment by SphinxC0re** [comment]
That would be another PR just for structure. Please rebase onto current master and squash the commits so we can merge

**Pull request closed without merging**
