### PR TITLE
Build Lua in C++ mode, use exceptions for error-raising.

### LINKED ISSUE #3678: Memory leak in StringUtils::AppendVPrintf
Server OS:        Linux

Combined plugin APIFuzzing with valgrind and got a few results.
This one with call to `StringUtils::AppendVPrintf` appeared the most time.
```
==7409== 31 bytes in 1 blocks are definitely lost in loss record 1 of 2
==7409==    at 0x4C2C1EC: operator new(unsigned long) (vg_replace_malloc.c:334)
==7409==    by 0x545DAE8: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate$
==7409==    by 0x545F072: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append$
==7409==    by 0x9973E2: AppendVPrintf(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>$
==7409==    by 0x997874: Printf[abi:cxx11](char const*, ...) (StringUtils.cpp:133)
==7409==    by 0xA1328A: cLuaState::CheckParamString(int, int) (LuaState.cpp:1750)
==7409==    by 0xB30B96: tolua_cJson_Parse(lua_State*) (LuaJson.cpp:279)
==7409==    by 0xEF8633: luaD_precall (ldo.c:319)
==7409==    by 0xF0FD1D: luaV_execute (lvm.c:587)
==7409==    by 0xEF8DD2: luaD_call (ldo.c:377)
==7409==    by 0xEF2FBE: f_call (lapi.c:800)
==7409==    by 0xEF7D64: luaD_rawrunprotected (ldo.c:116)
```

Reproduce:
1) Add this code to a plugin: `cJson:Parse(nil)`
2) Start cuberite under valgrind and it should print the output above

### PR DESCRIPTION
**Pull request by madmaxoft**
Fixes #3678 .

Note that the actual implementation of the change is in the updated submodule.

### CODE REVIEW

**Comment by madmaxoft** [comment]
I'd like to ask someone with a Mac and someone with a FreeBSD to test this on their platforms. I've only tested on Windows and Linux.

**Comment by Bond-009** [comment]
I tested it on macOS
I hope this is what you need:
```
testjson
Log: [ad75bd6ce5092996|16:43:29] Executing console command: "testjson"
Log: [ad75bd6ce5092996|16:43:29] Testing Json parsing...
Log: [ad75bd6ce5092996|16:43:29] Json parsing example 1 successful
Log: [ad75bd6ce5092996|16:43:29] Json parsing an invalid string: Error message returned: Parsing Json failed: * Line 1, Column 10
  Syntax error: value, object or array expected.

Log: [ad75bd6ce5092996|16:43:29] Json parsing a 'nil' raised an error
Log: [ad75bd6ce5092996|16:43:29] Json parsing test succeeded
Log: [ad75bd6ce5092996|16:43:29] Testing Json serializing...
Log: [ad75bd6ce5092996|16:43:29] Serialization result: {
 "a" : 1,
 "b" : "2",
 "c" : 
 [
  3,
  "4",
  5
 ],
 "d" : true
}
Log: [ad75bd6ce5092996|16:43:29] Serialization correctly failed with message: Cannot serialize into Json, value "valueB.badValue" caused an error "in Json::Value::resolveReference(key, end): requires objectValue"
Log: [ad75bd6ce5092996|16:43:29] Json serializing test succeeded
```

**Comment by Seadragon91** [comment]
Compiling release and debug builds under FreeBSD, works fine.
Running and command `testjson` works fine, too.

**Comment by madmaxoft** [comment]
Thanks, guys

**Pull request merged**
