### PR TITLE
Fix #3030

### LINKED ISSUE #3030: After I join, the server crashes
LOG:
```
     [11:48:30] --- Started Log ---
     [11:48:30] Cuberite  build id: 254
     [11:48:30] from commit id: 4495dd62b90e8f3a405ae7d9f464a574831aac91 built at: 254
     [11:48:30] Creating new server instance...
     [11:48:30] Reading server config...
Warn [11:48:30] Regenerating settings.ini, all settings will be reset
     [11:48:30] Starting server...
Info [11:48:30] Compatible clients: 1.7.x, 1.8.x
Info [11:48:30] Compatible protocol versions 4, 5, 47
Warn [11:48:30] Regenerating webadmin.ini, all settings will be reset
Warn [11:48:30] WebServer: The server is running in unsecured HTTP mode.
Info [11:48:30] Put a valid HTTPS certificate in file 'webadmin/httpscert.crt' and its corresponding private key to 'webadmin/httpskey.pem' (without any password) to enable HTTPS support
Info [11:48:31] There are no ranks, migrating old-style INI files to new DB ranks...
Info [11:48:31] (This might take a while)
Info [11:48:31] Rank migration failed, creating default ranks...
Info [11:48:31] Default ranks created.
     [11:48:31] Loaded 449 crafting recipes
     [11:48:31] Loaded 20 furnace recipes and 56 fuels
     [11:48:31] Loaded 88 brewing recipes
     [11:48:31] -- Loading Plugins --
     [11:48:31] Initialized ChatLog v.3
     [11:48:31] Initialised Core v.15
     [11:48:31] Initialized TransAPI v.1
     [11:48:31] -- Loaded 3 Plugins --
Info [11:48:31] Chosen a new random seed for world: 644403895
     [11:48:32] Preparing spawn (world): 2.75% (11/400; 10.87 chunks / sec)
     [11:48:33] Chunk generator performance: 41.29 ch / sec (83 ch total)
     [11:48:33] Preparing spawn (world): 8.00% (32/400; 20.98 chunks / sec)
     [11:48:34] Preparing spawn (world): 16.75% (67/400; 34.86 chunks / sec)
     [11:48:35] Preparing spawn (world): 26.00% (104/400; 37.00 chunks / sec)
     [11:48:35] Chunk generator performance: 40.57 ch / sec (163 ch total)
     [11:48:36] Preparing spawn (world): 35.75% (143/400; 38.96 chunks / sec)
     [11:48:37] Preparing spawn (world): 45.50% (182/400; 38.88 chunks / sec)
     [11:48:37] Chunk generator performance: 41.35 ch / sec (249 ch total)
     [11:48:38] Preparing spawn (world): 55.75% (223/400; 40.51 chunks / sec)
     [11:48:39] Preparing spawn (world): 65.50% (262/400; 38.92 chunks / sec)
     [11:48:40] Chunk generator performance: 41.79 ch / sec (336 ch total)
     [11:48:41] Preparing spawn (world): 75.50% (302/400; 39.84 chunks / sec)
     [11:48:42] Chunk generator performance: 42.12 ch / sec (423 ch total)
     [11:48:42] Preparing spawn (world): 85.50% (342/400; 38.54 chunks / sec)
     [11:48:43] Preparing spawn (world): 95.25% (381/400; 36.90 chunks / sec)
     [11:48:43] Chunk generator performance: 42.06 ch / sec (484 ch total)
Info [11:48:43] Generated spawnpoint position at {0.50, 72.00, 8.50}
Info [11:48:43] Chosen a new random seed for world: 742709465
     [11:48:44] Preparing spawn (world_end): 23.50% (94/400; 93.63 chunks / sec)
     [11:48:45] Preparing spawn (world_end): 52.25% (209/400; 113.97 chunks / sec)
     [11:48:46] Preparing spawn (world_end): 82.25% (329/400; 119.52 chunks / sec)
Warn [11:48:47] Did not find an acceptable spawnpoint. Generated a random spawnpoint position at {0.00, 168.00, 0.00}
```
----------------------------------------------------------------
There is no crashdump
----------------------------------------------------------------
It crashes everytime i join... I can see the animals and the world but then the server stops working!
----------------------------------------------------------------
Setings:
```
; This is the main server configuration
; Most of the settings here can be configured using the webadmin interface, if enabled in webadmin.ini

[Authentication]
Authenticate=1
AllowBungeeCord=0
Server=sessionserver.mojang.com
Address=/session/minecraft/hasJoined?username=%USERNAME%&serverId=%SERVERID%

[MojangAPI]
NameToUUIDServer=api.mojang.com
NameToUUIDAddress=/profiles/minecraft
UUIDToProfileServer=sessionserver.mojang.com
UUIDToProfileAddress=/session/minecraft/profile/%UUID%?unsigned=false

[Server]
Description=Cuberite - in C++!
MaxPlayers=100
HardcoreEnabled=0
AllowMultiLogin=0
Ports=25565
DefaultViewDistance=10

[RCON]
Enabled=0

[PlayerData]
LoadOfflinePlayerData=0
LoadNamedPlayerData=1

[Worlds]
DefaultWorld=world
World=world_nether
World=world_end

[Plugins]
; Plugin=Debuggers
; Plugin=HookNotify
; Plugin=ChunkWorx
; Plugin=APIDump
Plugin=Core
Plugin=TransAPI
Plugin=ChatLog

[DeadlockDetect]
Enabled=1
IntervalSec=20
```
----------------------------------------------------------------
World(default):
```
[SpawnProtect]
ProtectRadius=10

[WorldLimit]
LimitRadius=0

[Difficulty]
WorldDifficulty=1

[General]
Dimension=Overworld
IsDaylightCycleEnabled=1
Gamemode=1
Weather=0
TimeInTicks=0

[Broadcasting]
BroadcastDeathMessages=1
BroadcastAchievementMessages=1

[SpawnPosition]
MaxViewDistance=12
X=0.500000
Y=72.000000
Z=8.500000
PregenerateDistance=20

[Storage]
Schema=Default
CompressionFactor=6

[Plants]
MaxCactusHeight=3
MaxSugarcaneHeight=3
IsCactusBonemealable=0
IsCarrotsBonemealable=1
IsCropsBonemealable=1
IsGrassBonemealable=1
IsMelonStemBonemealable=1
IsMelonBonemealable=0
IsPotatoesBonemealable=1
IsPumpkinStemBonemealable=1
IsPumpkinBonemealable=0
IsSaplingBonemealable=1
IsSugarcaneBonemealable=0

[Physics]
DeepSnow=1
ShouldLavaSpawnFire=1
TNTShrapnelLevel=2
WaterSimulator=Vanilla
LavaSimulator=Vanilla
SandInstantFall=0
RedstoneSimulator=Incremental

[Mechanics]
CommandBlocksEnabled=0
PVPEnabled=1
UseChatPrefixes=1
MinNetherPortalWidth=2
MaxNetherPortalWidth=21
MinNetherPortalHeight=3
MaxNetherPortalHeight=21

[Monsters]
VillagersShouldHarvestCrops=1
AnimalsOn=1
Types=bat, cavespider, chicken, cow, creeper, enderman, guardian, horse, mooshroom, ocelot, pig, rabbit, sheep, silverfish, skeleton, slime, spider, squid, wolf, zombie

[Weather]
MaxSunnyTicks=180000
MinSunnyTicks=12000
MaxRainTicks=24000
MinRainTicks=12000
MaxThunderStormTicks=15600
MinThunderStormTicks=3600

[LinkedWorlds]
NetherWorldName=world_nether
EndWorldName=world_end

[Generator]
Generator=Composable
BiomeGen=Grown
ShapeGen=BiomalNoise3D
CompositionGen=Biomal
Finishers=RoughRavines, WormNestCaves, WaterLakes, WaterSprings, LavaLakes, LavaSprings, OreNests, Mineshafts, Trees, Villages, TallGrass, SprinkleFoliage, Ice, Snow, Lilypads, BottomLava, DeadBushes, NaturalPatches, PreSimulator, Animals
BiomeGenCacheSize=16
BiomeGenMultiCacheLength=128
SeaLevel=62
BiomalNoise3DFrequencyX=40.000000
BiomalNoise3DFrequencyY=40.000000
BiomalNoise3DFrequencyZ=40.000000
BiomalNoise3DBaseFrequencyX=40.000000
BiomalNoise3DBaseFrequencyZ=40.000000
BiomalNoise3DChoiceFrequencyX=40.000000
BiomalNoise3DChoiceFrequencyY=80.000000
BiomalNoise3DChoiceFrequencyZ=40.000000
BiomalNoise3DAirThreshold=0.000000
BiomalNoise3DNumChoiceOctaves=4
BiomalNoise3DNumDensityOctaves=6
BiomalNoise3DNumBaseOctaves=6
BiomalNoise3DBaseAmplitude=1.000000
CompositionGenCacheSize=64
RoughRavinesGridSize=256
RoughRavinesMaxOffset=128
RoughRavinesMaxSize=128
RoughRavinesMinSize=64
RoughRavinesMaxCenterWidth=8.000000
RoughRavinesMinCenterWidth=2.000000
RoughRavinesMaxRoughness=0.200000
RoughRavinesMinRoughness=0.050000
RoughRavinesMaxFloorHeightEdge=8.000000
RoughRavinesMinFloorHeightEdge=30.000000
RoughRavinesMaxFloorHeightCenter=20.000000
RoughRavinesMinFloorHeightCenter=6.000000
RoughRavinesMaxCeilingHeightEdge=56.000000
RoughRavinesMinCeilingHeightEdge=38.000000
RoughRavinesMaxCeilingHeightCenter=58.000000
RoughRavinesMinCeilingHeightCenter=36.000000
WormNestCavesSize=64
WormNestCavesGrid=96
WormNestMaxOffset=32
WaterLakesProbability=25
LavaLakesProbability=10
MineShaftsGridSize=512
MineShaftsMaxOffset=256
MineShaftsMaxSystemSize=160
MineShaftsChanceCorridor=600
MineShaftsChanceCrossing=200
MineShaftsChanceStaircase=200
VillageGridSize=384
VillageMaxOffset=128
VillageMaxDepth=2
VillageMaxSize=128
VillageMinDensity=50
VillageMaxDensity=80
VillagePrefabs=PlainsVillage, SandVillage
BottomLavaLevel=10
PreSimulatorFallingBlocks=1
PreSimulatorWater=1
PreSimulatorLava=1

[WaterSimulator]
Falloff=1
TickDelay=5
NumNeighborsForSource=2

[LavaSimulator]
Falloff=2
TickDelay=30
NumNeighborsForSource=-1

[FireSimulator]
BurnStepTimeFuel=500
BurnStepTimeNonfuel=100
Flammability=50
ReplaceFuelChance=50000

[Seed]
Seed=644403895

[WaterSprings]
HeightDistribution=0, 0; 10, 10; 11, 75; 16, 83; 20, 83; 24, 78; 32, 62; 40, 40; 44, 15; 48, 7; 56, 2; 64, 1; 255, 0
Chance=24

[LavaSprings]
HeightDistribution=0, 0; 10, 5; 11, 45; 48, 2; 64, 1; 255, 0
Chance=9

[Animals]
AnimalSpawnChunkPercentage=10
```

### PR DESCRIPTION
**Pull request by bearbin**
Logicparrot's instructions

### CODE REVIEW

**Comment by LogicParrot** [comment]
Outside the block

**Comment by LogicParrot** [comment]
as in after the if

**Comment by LogicParrot** [comment]
```
(*itr)->SetParentChunk(nullptr);
MoveEntityToNewChunk(*itr);
itr = m_Entities.erase(itr);
// Mark as dirty if it was a server-generated entity:
if (!(*itr)->IsPlayer())
{
	MarkDirty();	
}
itr = m_Entities.erase(itr);
```

**Comment by bearbin** [comment]
New one correct?

**Comment by LogicParrot** [comment]
Yes.

**Pull request merged**
