### PR TITLE
Fix unexpected world creation introduced by #2821

### PR DESCRIPTION
**Pull request by LogicParrot**
#2821

### CODE REVIEW

**Comment by SphinxC0re** [comment]
Looks good. 

Could you please stop merging your own PRs? After all, we introduced a policy for that.

**Comment by LogicParrot** [comment]
But I merged #2941 and #2939 after @tigerw 's approval. I admit I didn't wait with #2952.

**Comment by SphinxC0re** [comment]
That's not the point. The policy prevent mistakes, so acknowledge it.

**Comment by LogicParrot** [comment]
I am sorry, I might be misunderstanding something. Is it wrong to merge my own PRs after someone reviews them?

For instance, you said this PR looks good, so I merged it. Is that a problem?

**Comment by SphinxC0re** [comment]
For smaller changes that's okay. Merging without any feedback is not and for bigger changes, you should wait for two or more maintainers to review it.

**Comment by SphinxC0re** [comment]
And I'm saying that despite the fact that the policy itself says:

> Never merge your own PR

**Comment by LogicParrot** [comment]
I rarely merge without any feedback. As stated earlier, @tigerw LGTM'ed those changes. 

>you should wait for two or more maintainers to review it.

I typically wait for one other reviewer. That'd be two in total. (Them and me). 
In all honesty, waiting for two reviewers practically means almost nothing will be merged without sitting there for anything between 3 weeks and 3 months.

Where is the policy? Everyone seemed fine with 1-other-reviewer before. Even Bearbot used to merge when only two people LGTM'ed.

**Comment by SphinxC0re** [comment]
Yes, but the creator of a PR isn't usually supposed to LGTM' his own PR. Like Xoft once said:

> Of course it looks good to you, it's your own PR.

**Comment by LogicParrot** [comment]
@SphinxC0re I presumed that was a joke. There was never a clearly written policy. If you'd scroll back in PRs, you'd see that more often than not, it's just one reviewer (the PR author) or two reviewers.

I wouldn't mind following a clearly defined policy, but right now there is none. Also, I think 3-maintainer reviewes are overkill, considering the current manpower.

**Comment by LogicParrot** [comment]
The semi-formal policy @bearbin tried enforcing with bearbot was:
- 2 **maintainers** per PR.

This means that if it's an external contribution, then there are at least 3 reviewers: the original author, and the two maintainers.

If it's a contribution from one of the maintainers, then the minimum numer of reviewers goes down to two.

**Comment by SphinxC0re** [comment]
We all agreed on the policy about the anti-selfmerge

**Comment by LogicParrot** [comment]
I've always thought this isn't about who clicks the merge button, but about getting atleast 1 peer-review. I think there should be a written policy to avoid such misunderstanding, as clearly at least one of us is misunderstanding the unwritten policy.

**Comment by LogicParrot** [comment]
I've always thought this isn't about who clicks the merge button, but about getting atleast 2 maintainers looking at the code. I think there should be a written policy to avoid such misunderstanding, as clearly at least one of us is misunderstanding the unwritten policy.

**Comment by LogicParrot** [comment]
I've always thought this isn't about who clicks the merge button, but about getting atleast 2 maintainers (one of them can be the initial PR creator) looking at the code. I think there should be a written policy to avoid such misunderstanding, as clearly at least one of us is misunderstanding the unwritten policy.

**Comment by SphinxC0re** [comment]
I totally agree with the written policy and the probability of misunderstandings

**Comment by jammet** [comment]
End users like me appreciate all the work being done. :) Teamwork is the best thing in the world. Thank you guys!

**Comment by LogicParrot** [comment]
@jammet And I appreciate awesome end users :)

**Pull request merged**
