### PR TITLE
Slimes should only spawn at night

### LINKED ISSUE #2233: Slime spawn in light
Slime blocks are spawning in swamp biome during the day.

According to gamepedia: Slimes spawn in the Overworld in specific chunks below layer 40. They can also spawn in swamp biomes between layers 50-70 in light levels of 7 or less. (http://minecraft.gamepedia.com/Slime)

related to #1828 

This is on the first day the world was generated
slime001

### PR DESCRIPTION
**Pull request by nounoursheureux**
Fixes #2233

### CODE REVIEW

**Comment by madmaxoft** [comment]
I think slimes are allowed to spawn in higher blocklight. When playing vanilla survival, after I light all the caves, slimes are still spawning in them.

**Comment by bibo38** [comment]
Yeah, thats right. It depends, where the slime spawns.
See http://minecraft.gamepedia.com/Slime

The caves in the slime chunks doesn't need any light level:
> Slimes spawn throughout the world (except mushroom islands) below layer 40 regardless of light level, but only in certain chunks, 1 in 10 of all chunks. These "slime chunks" are determined pseudo-randomly by combining their chunk coordinates with the seed of the world

but for the swamps the light level is important and cannot be higher than 7:
> In swamps, slimes may spawn at night between the heights of 50 and 70 provided the light level is 7 or less. They spawn most often on a full moon, and never on a new moon.

**Comment by SphinxC0re** [comment]
Any updates on this?

**Comment by SphinxC0re** [comment]
Closing due to no response

**Pull request closed without merging**
