### PR TITLE
WebAdmin improvements

### LINKED ISSUE #4068: Webadmin footer covering content in Safari
Server OS:        Linux
Commit id:        c54bf40

### Expected behavior
The footer of the webadmin should be after the content, or at least, not covering it, without the ability to scroll.

### Actual behavior
Scrolling a long page to the bottom, the footer covers the content.
Scrolling down further is impossible, so the save button can't be clicked.

screenshot

### Steps to reproduce the behavior
Open a longer page, like `/Core/Plugins` in Safari 11.0.2 and scroll to the bottom.

### PR DESCRIPTION
**Pull request by mathiascode**
- Cleaned up unused, duplicated and messy CSS
- Simplified HTML
- Fixed scaling on smaller screens
- Made UI elements larger for better touch screen experience (Android)
- Changed the color scheme to match Cuberite's green color
- Fixes an issue where the logout link wouldn't work if you were located on a subpage

- (Updated Cuberite Windows icon to match Android's shape)

Fixes #4068

image
image
image

### CODE REVIEW

**Comment by madmaxoft** [comment]
I can't really comment on the code, but I like the new design, so consider this a +0.5  approval review :)

**Comment by DaMatrix** [comment]
I like this much more than #3968 , it's not too much of a change and looks quite a bit nicer. :+1:

**Comment by madmaxoft** [comment]
Could you check how this change works with the Gallery plugin's area preview pages? Those tend to get really wide, requiring horizontal scrolling. If you need example data for the galleries: http://cuberite.xoft.cz/GalleryBackup/

**Comment by mathiascode** [comment]
There are slight issues with the preview pages. I'll come up with a solution when I have time.

**Comment by mathiascode** [comment]
Fixed the issue. The container box now expands past the max width when the content is too wide. For some reason, the old WebAdmin layout deliberately disabled horizontal scrolling, but this is no longer the case.

**Comment by madmaxoft** [comment]
Sounds good, could you post a screenshot of the gallery page? I'm really too lazy to log into the Gallery server and upload your changes there to test it :P

**Comment by mathiascode** [comment]
Do you want small preview images (perhaps clickable?), or large ones? (just used some sample images, since I didn't look into setting up the schematic to png tool)
image
image
image
image

**Pull request merged**
