### PR TITLE
Fixed horse bug

### PR DESCRIPTION
**Pull request by tonibm19**
Now horses cannot be controlled if they're not tamed and saddled

### CODE REVIEW

**Comment by tonibm19** [comment]
I did something wrong with updating my fork maybe?

**Comment by SphinxC0re** [comment]
You should squash again and rebase onto current master

**Comment by madmaxoft** [comment]
This should help:
```
git remote add upstream https://github.com/cuberite/cuberite.git
git fetch upstream
git rebase upstream/master
```
(You won't need the first line the next time you run into this)

This is why you should be developing each PR on a separate branch, instead of "master"; you can then update the branch to the canon repository using
```
git checkout -b MyNewBranch
... do some work, create commits
git fetch upstream master:master
git rebase master
```

**Comment by tonibm19** [comment]
Thanks, seems OK now

**Pull request merged**
