### PR TITLE
Added Log That Says The Port

### PR DESCRIPTION
**Pull request by CoolPuppyKid**
fixes https://github.com/cuberite/cuberite/issues/5381 cause i also ran into this issue and found it annoying

### CODE REVIEW

**Review by bearbin — CHANGES_REQUESTED** [review]
At this point the server hasn't started yet, this is just reading the config - so saying the "Server Running" is incorrect. Also this just logs the first port, it's possible to specify multiple.

Change it to log inside the `if (Handle->IsListening())` of cServer::Start (at that point the server is running so it's fine to log with your current message) and it'll be good :)

**Comment by CoolPuppyKid** [comment]
> At this point the server hasn't started yet, this is just reading the config - so saying the "Server Running" is incorrect. Also this just logs the first port, it's possible to specify multiple.
> 
> Change it to log inside the `if (Handle->IsListening())` of cServer::Start (at that point the server is running so it's fine to log with your current message) and it'll be good :)

fixed now :D

**Comment by MightyFilipns** [comment]
@CoolPuppyKid you have commited world_the_end/level.dat, I presume accidentaly. You should remove it.

**Comment by CoolPuppyKid** [comment]
> @CoolPuppyKid you have commited world_the_end/level.dat. You should remove it.

Fixed now sorry about that

**Review by bearbin — APPROVED** [review]

**Pull request merged**
