### PR TITLE
Redstone

### PR DESCRIPTION
**Pull request by Haxi52**

### CODE REVIEW

**Comment by worktycho** [comment]
I like the way you're going with this, but can I suggest that we keep the old simulator in the server as an option, until the new one is shown to have feature parity?

**Comment by Haxi52** [comment]
Oh! lol, I clicked the wrong button and this pull request came up. I wasn't planning on making a pull request until everything was in place. Have been working with tigerw on this and I'm fairly excited to see it develop. Thanks for the feed back. hopefully you'll see this soon.

**Comment by SphinxC0re** [comment]
@Haxi52 I know you didn't want to open a PR but what is the status on this? Are there any new features? Updates?

**Comment by Haxi52** [comment]
Sorry I haven't had a lot of time lately to work on this. Hopefully soon.

**Comment by SphinxC0re** [comment]
@Haxi52 I would really like this to be developed further. A new structure for the redstone sim would be nice

**Comment by Haxi52** [comment]
oh! Ok, I stopped developing this when I saw @tigerw implement his changes. But if there is still interest I can start working on this again.

**Pull request closed without merging**
