### PR TITLE
Fixed tall flowers not being destroyed properly while generating snow

### LINKED ISSUE #1428: Peonys top part gets generated on top of snow layers in the ice mountains

### PR DESCRIPTION
**Pull request by Altenius**
Fixes #1428 #3539

### CODE REVIEW

**Comment by madmaxoft** [comment]
I don't think this is the right way to go about this. The main problem would seem that the tall flowers don't update the heightmap properly, so that when the Snow finisher asks for the top block, it sees the grass block, rather than the top flower block.

Since the Snow finisher doesn't destroy any other block types, I'm against this kind of change, sorry.

**Comment by Altenius** [comment]
I've made the proper changes. Thanks

**Comment by sphinxc0re** [comment]
@Altenius Are you actively working on this? Updates?

**Comment by sphinxc0re** [comment]
@Altenius if this change is ready, please rebase your branch onto the current master branch of the canon repo

**Comment by Altenius** [comment]
This has been ready since the last change. I rebased it again..

**Comment by madmaxoft** [comment]
@sphinxc0re There's not much need for rebasing if the resulting PR will be squash-merged into a single commit - GH does the work for us. There are only two scenarios when rebasing is still needed:
 - we want the result to consist of multiple commits
 - we want to re-run the CI tests for the PR against the current master
Neither of these apply here.

**Comment by sphinxc0re** [comment]
@madmaxoft Oh, okay. Thank you for clearification 😁

**Comment by LogicParrot** [comment]
I presume nobody tested and @sphinxc0re rushed a merge :P

**Comment by sphinxc0re** [comment]
@LogicParrot I didn't rush anything. What are you talking about?

**Comment by LogicParrot** [comment]
>@madmaxoft added the status/ingame-testing-needed label on Jan 19


>@Altenius if this change is ready, please rebase your branch onto the current master branch of the canon repo

=> PR merged, no one tested.

**Comment by sphinxc0re** [comment]
So what did I rush? 😁

**Pull request merged**
