### PR TITLE
Made IsThread terminate flag into atomic running flag

### LINKED ISSUE #2636: cIsThread::m_ShouldTerminate synchronisation
The variable is being set in the world thread when Stop() is called but accessed in Execute() from another thread. The variable is declared volatile but this provides no atomicity guarantees.

### PR DESCRIPTION
**Pull request by worktycho**
Fixes #2636

### CODE REVIEW

**Comment by madmaxoft** [comment]
Can't you use something that doesn't have a `test_and_set`, because it's misleading that a test actually sets a value?

**Comment by worktycho** [comment]
Theres atomic_bool, but its not guarenteed to be lock free, as not all platforms have support for an atomic load instruction.

**Comment by madmaxoft** [comment]
What is the danger of using a non-lock-free variant? If it's a (reasonable) performance hit, I think we can live with that, since it's just a flag to tell the thread to terminate, after all.

**Comment by worktycho** [comment]
The problem is that any platform that doesn't have an atomic load instruction is probably not going to have fast mutexes, so thats exactly when you don't want to be using mutex's.

**Comment by worktycho** [comment]
So it would probably involve at least two syscalls to on load an atomic bool on a platform that doesn't have lock free atomic_bool.

**Comment by Seadragon91** [comment]
@worktycho forgot to update submodules before commit? :)

**Comment by worktycho** [comment]
Probably, I'm working on several pre-submodulisation branches,

**Comment by madmaxoft** [comment]
I still don't like this. Now the flag's description is kinda wrong. The flag is set to false to terminate the thread, but the thread then resets it back to true after the first check. We can't have multiple places checking the flag because of the reset.

**Comment by worktycho** [comment]
You can have multiple checks, its just a risk they might not notice because theres a gap between one thread reading it and resting it. Look at what I did with the lighting thread.

**Comment by madmaxoft** [comment]
Which is another reason why I don't like the change - when reading such a piece of code, you go just "wtf?!"

**Comment by SphinxC0re** [comment]
Do you have a better idea or would you go with "keep as it is"

**Comment by worktycho** [comment]
We can't really keep as is.
The other two options are: wrap atomic_flag so that it auto reclears when reading, or risk performance issues with atomic_bool.

**Comment by SphinxC0re** [comment]
What is the difference between ```std::atomic<bool>``` and ```std::atomic_bool``` ?

**Comment by worktycho** [comment]
nothing, std::atomic_bool is just a typedef for std::atomic<bool>

**Comment by madmaxoft** [comment]
I haven't found much on the performance, but all info I found suggested that there's not much difference between `atomic_flag` and `atomic_bool` performance-wise.

**Comment by worktycho** [comment]
I depends on the implementations. pretty much all major implementations do have a lock free atomic bool, I'm arguing from a purely standard based point of view.

**Comment by madmaxoft** [comment]
If they don't have a lock-free atomic bool, we'll be having much worse performance problems than threads checking whether they should exit. Please do rewrite this to use the `atomic_bool`.

**Comment by tigerw** [comment]
(xoft being difficult again :P)

**Pull request closed without merging**
