### PR TITLE
Flush log file when a warning or error message is output.

### LINKED ISSUE #2419: Flush log file after each warning and error
If the server outputs a warning or error message to the log, it should flush the file, so that all the log contents are synced to the disk. Otherwise error reports get lost because the server is terminated before it manages to flush the log.

### PR DESCRIPTION
**Pull request by madmaxoft**
Fixes #2419.

### CODE REVIEW

**Comment by SphinxC0re** [comment]
Wouldn't it be good, if the logs contained every logline? For error reporting this would be a good thing to get a context

**Comment by madmaxoft** [comment]
The problem is that flushing the file is a rather expensive operation, so you don't want to do it too often. Especially with the debug output, there's no point, really. I think having the flush for warnings and errors is a reasonable compromise.

**Comment by SphinxC0re** [comment]
So does every log message get fushed into a file? If not we could solve the problem by caching the log output, flushing it into a file when warning or error mesages come

**Comment by madmaxoft** [comment]
Right now the messages are cached by the C runtime and flushed out to file in 4-KiB blocks. This PR changes that so that after each warning or error message the buffers are flushed.

**Comment by madmaxoft** [comment]
(rebased onto current master)

**Pull request merged**
