### PR TITLE
Squashed Bonemeal Plant Growth Update

### PR DESCRIPTION
**Pull request by SamJBarney**
* Fixed Crops growing to maturity with only 1 bonemeal
* Trees now go through growth stages with bonemeal, as they do in
Vanilla Minecraft

### CODE REVIEW

**Comment by tigerw** [comment]
There is no need to open a new PR to squash changes :P

**Comment by SphinxC0re** [comment]
I was wondering too :grin: but I think it's okay

**Comment by SamJBarney** [comment]
I'm having to do it manually. My git is messing up my repos

**Comment by SphinxC0re** [comment]
You gotta join the irc and tell us more :grin:

**Comment by SamJBarney** [comment]
irc? I didn't know we had one

**Comment by SphinxC0re** [comment]
Look at the website :smile:

**Pull request merged**
