### PR TITLE
Fix for #2404

### PR DESCRIPTION
**Pull request by yo4you**
Fixes issue #2404: "Lilly pad doesn't get destroyed when block is placed under it"

### CODE REVIEW

**Comment by madmaxoft** [comment]
I believe lilypads can be placed on non-stationary water as well. I'm not sure about non-source water, though.

**Comment by yo4you** [comment]
This works for non stationary water, non source doesn't work (like it should).

**Comment by madmaxoft** [comment]
There's no way to know whether the source in the screenshot is stationary or not. Breaking the tallgrass next to it should convert it to non-stationary, until the fluid simulator converts it back to stationary; I'm not sure if block checks on neighbors are performed with such a change, though.

There's nothing in the code that prevents lilypads on non-source water blocks; being unable to place them there may be a client-side check.

**Comment by yo4you** [comment]
Updated the blocks around it and the lily pad seems to stay on until I remove the water.  Turning a source into a non-source does make it pop off. Also, removing a source next to another source makes both lilies pop off, I'm not sure if that's related to the water system.
(unrelated: Heh sorry, I have still to figure out how to make commands work in my debug world)

**Comment by madmaxoft** [comment]
The neighbor source removal that pops off both lilypads is what I was referring to with stationary / nonstationary. Removing the neighboring source turns the source into a non-stationary block so that the fluid simulator checks it again, and that triggers the lilypad check. So that's why you need to check for both stationary and non-stationary source block.

**Comment by yo4you** [comment]
I see, interesting. Changed the commit works fine now.

**Comment by madmaxoft** [comment]
You seem to be doing unrelated changes on this branch. This way the PR will never get merged.

I'll try cherry-picking and squashing your commits relevant to the lilypad change.

**Comment by yo4you** [comment]
Oh sorry my bad (didn't know that would affect his PR), those were for a different issue. The only file related is lilypad.hpp I'll put the other ones in a seperate PR once I'm done messing with it.

**Comment by SphinxC0re** [comment]
Update?

**Comment by madmaxoft** [comment]
I have cherry-picked the lilypad-related changes into a separate PR, and updated the changes to match vanilla behavior. Closing this PR.

**Pull request closed without merging**
