### PR TITLE
Revert redstone handler

### LINKED ISSUE #3235: Restart command crashes server
Client version:   1.9.4
Commit id:        ec998e821fd905966ed14ed47a29520ec1d1d782

### Expected behavior
The restart command should restart the server.

### Actual behavior
Release mode: The server crashes, when the user reconnects after executing the restart command.
Debug mode: The server crashes on executing the restart command.
Edit: This crashes sometimes on a assert error.

### Steps to reproduce the behavior
```
1. Start the server
2. Connect to the server
3. Execute command restart (users get disconnected)
4. Reconnect to the server
```

### PR DESCRIPTION
**Pull request by Seadragon91**
This fixes #3235. Have done the revert this way, because there was a conflict.

### CODE REVIEW

**Comment by madmaxoft** [comment]
I took the liberty and squashed those reverts/readds into a single commit. I believe this is better for the history.

**Comment by Seadragon91** [comment]
Yes that's better :)

**Comment by SphinxC0re** [comment]
Please rebase your branch, so we can merge this ASAP

**Comment by madmaxoft** [comment]
I think there's something wrong with GitHub. The branch is up to date, and GitHub says that "Required statuses must pass before merging", but the CI builds are all green.

**Pull request merged**
