### PR TITLE
Fixed falling block spawning

### LINKED ISSUE #3222: Falling block animation starts too high and ends too low.
Client version:   1.8.9 (OptiFine) + 1.9.4 (Vanilla)
Commit id:        a567b36a8a6574208b30f8a22d3240d13a01bf63

### Expected behavior
If I place a block and he should fall down because of the gravity, he starts falling at the point I placed him and stops at the moment he hits the block below.

### Actual behavior
If I place a block and he falls down because of the gravity, the animation of the falling block starts too high and ends too low. (often it gets into the block below.)

### Steps to reproduce the behavior
Create a tower of 3 solid blocks and place a block with physics (e.g. sand, gravel, an anvil) and watch the falling animation. 
Make sure that "SandInstantFall" is disabled (=0) in the world.ini of the selected world to enable the falling animation!

### PR DESCRIPTION
**Pull request by Altenius**
Fixes #3222

### CODE REVIEW

**Comment by madmaxoft** [comment]
CircleCI seems to be failing because they have some internal problems. I'll restart the build later, probably tomorrow.

**Comment by madmaxoft** [comment]
Nooo, don't merge master. We don't merge master, we rebase onto it.

**Comment by Altenius** [comment]
Sorry.. I have no idea what I'm doing, this is my first time doing anything with other projects. How do I undo that?

**Comment by madmaxoft** [comment]
That's the problem, it's very difficult to undo a merge.

Usually it's easiest to start a new branch in your copy of the repository, and cherry-pick the relevant commit onto it, then drop the old branch and rename the new one to the same name. Finally, force-push the new branch to GitHub.

In command-line git, something like this:
```
git remote add upstream https://github.com/cuberite/cuberite.git  # Link your repo with the official repo
git fetch upstream  # Fetch the latest source from the official repo
git checkout upstream/master  # Checkout the latest source
git cherry-pick <commitID>  # Cherry-pick your changes
git branch -D <oldBranchName>  # Delete the old branch
git branch -b <oldBranchName>  # Create a new branch with the same name as the previous one, with new contents
git push -f  # Force-push the changes to GitHub
```

For normal operations, assuming you have already added the `upstream` remote, this is how to update the branch to the newest official repo (assuming you are working on a separate branch, not on master):
```
git fetch upstream master:master  # Fetch the newest sources from official repo and move your master branch to them
git rebase master  # Rebase your changes onto the newest sources
git push -f  # Force-push your branch to your GitHub
```
```

**Comment by madmaxoft** [comment]
I'll merge this PR manually so that you don't have to go through all that.

**Comment by Pokechu22** [comment]
You could probably also use `git reflog` and find the appropriate commit before the merge, and then `git reset --hard` to it.

**Comment by madmaxoft** [comment]
This one's difficult, the original commit was against branch `testing-0.1`, which is really, really old.

**Comment by madmaxoft** [comment]
I have trouble forcing git to do the cherrypick for me. Could you possibly create a new PR, this time based on current master, with your change?

**Comment by Altenius** [comment]
Submitted https://github.com/cuberite/cuberite/pull/3250

**Pull request closed without merging**
