### PR TITLE
New icon colors

### PR DESCRIPTION
**Pull request by mathiascode**
Updated the icon colors to the new color scheme.

### CODE REVIEW

**Comment by Cl1608Ho** [comment]
Would he nice if you asked us before deciding on such a color scheme! 

The gradients are nice, but the black was a lot better imo!

**Comment by madmaxoft** [comment]
The discussion took place in the website repo: cuberite/cuberite.github.io#77
I personally like the new icons more, they are more distinguished.

**Comment by madmaxoft** [comment]
I think the Server/webadmin/files/favicon.ico file should be updated too. But I'm not sure if it should be the exact same as the main site's favicon, because that would make it indistinguishable again.

**Comment by NiLSPACE** [comment]
Perhaps the gradient should be reversed?

**Pull request merged**
