### PR TITLE
Prevent player falling when block breaking is denied

### LINKED ISSUE #2669: Block breaking denied, but player can slip trough
Example
Block breaking denied with plugin.
Player can still fall trough the ground, if he break the block under his feet.

### PR DESCRIPTION
**Pull request by LogicParrot**
Closes #2669

### CODE REVIEW

**Comment by NiLSPACE** [comment]
Is this tested? I believe you have to teleport a player .001 above a block in order to prevent them from falling down.

**Comment by madmaxoft** [comment]
This should be enough, but I'd still like a confirmation from someone who actually tested this in-game.

We should add instructions for testing whenever the `ingame-testing-needed` label is used.

Simplest test case: go to server spawn area, make sure you are not in admin rank, break a block (the default configuration should prevent you from breaking it). Now try breaking the block directly beneath you; before this fix you'd fall into the ground, after this fix you should stay on top of the ground (possibly sinking for small amount of time but always being teleported back to the top).

**Comment by Seadragon91** [comment]
This works fine :)

**Comment by LogicParrot** [comment]
> We should add instructions for testing whenever the ingame-testing-needed label is used.

@madmaxoft Agreed, hence #2959

@Seadragon91 Yay :)

**Comment by SphinxC0re** [comment]
Looks good

**Comment by tigerw** [comment]
woah woah woah, what happens if a player happens to be walking in some direction and breaks a block, say, beside them? Will they get unexpectedly teleported back despite not actually going through anything? Isn't this more of a task for the physics engine?

**Comment by SphinxC0re** [comment]
Yeah it should be. But for now, this is an okayish fix

**Comment by LogicParrot** [comment]
@tigerw Physics engine? [KISS](https://en.wikipedia.org/wiki/KISS_principle). If the block breaking is **denied**, then yes, a player walking in some direction will be teleported back. But typically block breaks are not denied.

**Comment by LogicParrot** [comment]
Why okayish? This is a cool fix. The simplest thing possible, a fully-fledged anti-cheat system server-side player physics system should be very low in the Cuberite priorities right now.

**Comment by tigerw** [comment]
Rare bugs are still bugs though, unless you call them features (we have a lot of those instances :P) Let's call this a stopgap solution.

> KISS
Says the guy of twenty extra member variables. Also, I think I was just subtly insulted via initialism ;)

**Comment by LogicParrot** [comment]
@tigerw Yes but this is an extremely minor bug. A player will jerk a bit when breaking an unbreakable block.

**Comment by LogicParrot** [comment]
@tigerw Yes but this is an extremely minor bug. A player will jerk a bit only when breaking an **unbreakable** block while **walking**.

**Comment by tigerw** [comment]
Could be the difference between escaping and getting ~~360noscope'd~~ eliminated in a PvP match :)

**Comment by LogicParrot** [comment]
@tigerw Why are you ignoring the "unbreakable" part? When was the last time anyone decided to break an unbreakable block in a PvP match? These code paths will not even trigger for say dirt or cobblestone or whatever regular block there is. The block has to be break-denied by a plugin in order for the jerk to occur.

**Comment by bearbin** [comment]
Well, in a PvP arena, all blocks could easily be unbreakable due to the plugin being used. But I agree, this is not really a major issue. We should keep around an issue/reminder to fix it in future, but it's good enough for the moment.

**Comment by LogicParrot** [comment]
@bearbin Good point, but they'd still have to press and hold for a while, a highly unlikely thing to do in PvP.

**Comment by tigerw** [comment]
Snow + shovels?

**Pull request merged**
