### PR TITLE
Implemented the Water Breathing Potion functionality.

### LINKED ISSUE #2556: Potion effects
Water breathing and fire resistance potions have no effect. They only apply the visual icon and the countdown.

### PR DESCRIPTION
**Pull request by bibo38**
In addition to #2584 this fixes #2556

### CODE REVIEW

**Comment by bearbin** [comment]
Looks good to me :)

**Comment by Seadragon91** [comment]
Thanks you very much.

**Comment by Schwertspize** [comment]
wanna add yourself to the CONTRIBUTERS file?

**Comment by bibo38** [comment]
Not now. I plan to add myself, when I have added 1000 lines of code to this project.

**Pull request merged**
