### PR TITLE
AppVeyor release builds

### PR DESCRIPTION
**Pull request by mathiascode**
Also implements cache, fixes https://github.com/cuberite/cuberite/issues/4378
https://forum.cuberite.org/thread-3250.html
https://ci.appveyor.com/project/mathiascode/cuberite/builds/28731668

### CODE REVIEW

**Comment by mathiascode** [comment]
As for enabling cache in pull requests, this should do it: https://github.com/appveyor/ci/issues/1553#issuecomment-356455596

**Comment by mathiascode** [comment]
Github Actions was released on November 13, and supports Linux, Windows and macOS CI with artifacts. Artifacts are stored for 90 days. It could be an option for macOS builds. I'll look into it when I have time.

**Comment by madmaxoft** [comment]
I've enabled the PR caching, as per your comment. We'll see how well that works :)

**Comment by mathiascode** [comment]
What's the difference between https://ci.appveyor.com/project/madmaxoft/mcserver and https://ci.appveyor.com/project/bearbin/cuberite?

**Comment by madmaxoft** [comment]
No idea

**Comment by madmaxoft** [comment]
They both have webhooks active, so they each build the same thing. Only the version number differs, @bearbin 's seems younger than mine. I can edit settings for mine, but can't edit bearbin's, I assume it's the other way around for him (is there a way to make the settings accessible to the entire team?)

**Comment by mathiascode** [comment]
There seems to be Github teams integration available. https://www.appveyor.com/docs/team-setup/

**Comment by mathiascode** [comment]
I'll point the homepage download links for Windows to:
- https://ci.appveyor.com/api/projects/madmaxoft/mcserver/artifacts/Cuberite.zip?job=Windows-x86&pr=false&branch=master
- https://ci.appveyor.com/api/projects/madmaxoft/mcserver/artifacts/Cuberite.zip?job=Windows-x64&pr=false&branch=master
if that's ok?

**Comment by madmaxoft** [comment]
First we should make a team account on Appveyor, then re-target the builds at that official org. So that the download links are not pointed to my account, which looks insecure / amateurish, but the official org.

**Comment by mathiascode** [comment]
Seems to be quite an annoying situation. If you register an AppVeyor account with email and password, you can't grant access to Github users/teams, but if you create an account by logging into Github, the account is tied to your Github profile. You can rename your AppVeyor account to something appropriate though.

**Comment by mathiascode** [comment]
Actually, I could be wrong. Try creating a new AppVeyor account with the cuberite.org email address.

**Comment by madmaxoft** [comment]
I think I managed to create a Cuberite org account on Appveyor (using the support@cuberite.org email address), now I need to move the builds there.

**Comment by madmaxoft** [comment]
Seems to work, when you use your GitHub login to enter Appveyor, you should see the personality selector on the top left, select between your personal account or the Cuberite org account. I've added the main build project to the org account, it's building right now.

**Comment by mathiascode** [comment]
Would it be possible to give core members permission to cancel builds? It's a bit tedious to wait for the builds to complete sometimes, when newer commits have been added since.

**Comment by madmaxoft** [comment]
I seem to have the permission, and I put you on the member list so you should, too.

**Comment by mathiascode** [comment]
image
I lack any sort of control buttons at the moment.

**Comment by madmaxoft** [comment]
The "cancel" link only appears when hovering mouse over the build, next to the "queued" link on the right, and only in the History view of the builds. You can't cancel a single job, only a complete build.

On the other hand, my view shows Deployments, Events and Settings to the left of History, so it seems I have more permissions. No idea what to do, though.

**Comment by madmaxoft** [comment]
After going through the account settings and repo settings, I found something where there was a pairing between users and roles, there's you and @peterbell10 listed there as users (not admins), and no other people. Seems like their GitHub team integration is not working, or I'm not understanding it enough. Anyway, I set both of you as admins, so now you should have the permission.

**Comment by mathiascode** [comment]
In my case, it seems to be due to AppVeyor primarily associating me with the plugins team, which has user access.
image

**Pull request merged**
