### PR TITLE
Change TimeOfDay to WorldDate

### LINKED ISSUE #4737: Day count in f3 not implemented
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: e053f72db824a16c1cb59107315001473058e2bc

### Expected behavior
There should be a number in the f3 menu stating how many in game days have past.

### Actual behavior
The Day count is always 0.

### Steps to reproduce the behavior
Open f3 on server running cuberite

### LINKED ISSUE #5159: World age isn't being sent to the client(?)
Client version: Any.
Server OS: Linux (Armbian)
Cuberite Commit id: 01a4e696b3d2c973cdd1fb4345d747bd10e93ad9

### Expected behavior
The client gets the worlds age.

### Actual behavior
It doesn't

image

### Steps to reproduce the behavior
Join a cuberite server. 
Press F3.
Look at Day counter.

### PR DESCRIPTION
**Pull request by tigerw**
* Do not wrap at 20 minutes, continue incrementing
* Fixes #4737
* Fixes #5159

### CODE REVIEW

**Comment by tigerw** [comment]
cWorld::SetTimeOfDay is now poorly named and using beds will still reset the day count to zero, but for natural progression of time, the client should correctly displays days.

**Comment by 12xx12** [comment]
The time is now displayed properly but the /time command resets the timer back to the first day.
But it think this is a issue of the core plugin

**Comment by 12xx12** [comment]
maybe have a function that takes the values up to 24000 and always skips forward and one that takes absolute values

**Comment by tigerw** [comment]
I tried to make SetTimeOfDay preserve the day count, that should fix Core.

**Comment by 12xx12** [comment]
I realy like how the time transition animation now always goes forward 👍

**Review by 12xx12 — APPROVED** [review]

**Pull request merged**
