### PR TITLE
Changed MCServer output directory name to out

### PR DESCRIPTION
**Pull request by SphinxC0re**

### CODE REVIEW

**Comment by NiLSPACE** [comment]
My internet is too slow to load the changes :|

Did you remove the whole MCServer folder with it's content? Because it should just be renamed. Some files in there are needed for the executable. For example the village prefabs are in there. Even the whole Lua API documentation.

**Comment by SphinxC0re** [comment]
oh xD one moment

**Comment by tigerw** [comment]
One moment

**Comment by tigerw** [comment]
Oops

**Comment by SphinxC0re** [comment]
@tigerw everything is okay :grin:

**Comment by tigerw** [comment]
Did you mean: ~~okay~~ ***awesome***

Awesome

**Comment by SphinxC0re** [comment]
@tigerw Yep :grin:

**Comment by SphinxC0re** [comment]
This did only rename the output directory but not the output directory defined by cmake. does anyone know how I do this?

**Comment by worktycho** [comment]
Its in the cmakelist in the src folder

**Comment by SphinxC0re** [comment]
I can't get it to work. Where is the $MCSERVER_PATH var set?

**Comment by SphinxC0re** [comment]
I will close. This should be solved in #2220

**Pull request closed without merging**
