### PR TITLE
Update fences and gates list

### PR DESCRIPTION
**Pull request by SafwatHalaby**

### CODE REVIEW

**Comment by SafwatHalaby** [comment]
@jammet

**Comment by SafwatHalaby** [comment]
OSX1 build failed again. I'm ignoring that.

**Comment by SphinxC0re** [comment]
You shoudn't ignore it since it's part of our integrity checks. You have to look up the error message and fix the problem

**Comment by SafwatHalaby** [comment]
It's failing often with obscure errors which I don't think are related to the PR itself. This PR is trivial and shouldn't affect whether a compiler would compile succesfully. 

This time the error was:
```
Error: [19:07:41]   D:    | Cuberite has encountered an error and needs to close
Error: [19:07:41] Details | SIGSEGV: Segmentation fault
Error: [19:07:41] Cuberite Jenkins clang x64 Release (master) build id: #76
Error: [19:07:41] from commit id: ef3fcbc201fa5f03a72282622fa5eee117d8c972 built at: Fri Dec 25 18:56:54 CET 2015
Error: [19:07:41]   D:    | Cuberite has encountered an error and needs to close
Error: [19:07:41] Details | SIGABRT: Server self-terminated due to an internal fault
Error: [19:07:41] Cuberite Jenkins clang x64 Release (master) build id: #76
Error: [19:07:41] from commit id: ef3fcbc201fa5f03a72282622fa5eee117d8c972 built at: Fri Dec 25 18:56:54 CET 2015
/var/folders/1r/rw8x6njd2qj7h373k2y3tbf80000gp/T/hudson6210207389879106087.sh: line 36:  1183 Abort trap: 6           ./Cuberite  <<-EOS
load APIDump
api
stop
EOS

Build step 'Execute shell' marked build as failure
Archiving artifacts
Setting status of 958df6ad9192285e0a19caa362f9f0c9e63422d4 to FAILURE with url https://builds.cuberite.org/job/Cuberite%20OSX%20x64%20Pull%20Requests/76/ and message: 'Build Failed
 No test results found.'
Using context: cuberite-buildserver/pr
Finished: FAILURE
```

**Comment by SphinxC0re** [comment]
a segmentation  fault is a serious problem. Also there is a method called ```IsBlockFence``` which does exactly what your function does. Please rework this and update the function in the Defines.h instead

**Comment by SafwatHalaby** [comment]
You're completely correct about `IsBlockFence`. I forgot about it.
A segmentation fault was definitely not caused by this change.

**Comment by tigerw** [comment]
Hmmm. All those extra `case`es look suspicious. What are they doing there? Are you trying to subversively sabotage us with innocuous-looking keywords?

**Pull request merged**
