### PR TITLE
Note Block Left Click Fix V2

### LINKED ISSUE #4839: No noteblock playback on left click
Client version: any
Server OS: any
Cuberite Commit id: d2de029c024309b0ac2429373cc8ef2e56f880e0

### Expected behavior
When left clicking a note block in survival you play back the sound without changing the pitch

### Actual behavior
no sound playback or a animation

### Steps to reproduce the behavior
- place noteblock
- go into survival
- left click on it

### PR DESCRIPTION
**Pull request by ProjectBM**
Redo of PR #5050 since Travis CI build timed out.

* Player can now left click on note block and play back the sound with an animation.

Fixes #4839

### CODE REVIEW

**Comment by 12xx12** [comment]
@bearbin this is strange - we have a build breaking before executing the server not while generating the nether

**Comment by tigerw** [comment]
I'm inclined to blame Travis

**Comment by 12xx12** [comment]
There error is reproduceable. I just restarted the ARM build

**Comment by ProjectBM** [comment]
Strange it still fails 🤔

**Comment by tigerw** [comment]
Quite irregular. @ProjectBM to aid debugging, you could try adding an `echo "Starting server"` just before the `./Cuberite` in travisbuild.sh, and in src\main.cpp, replace `return UniversalMain(argc, argv, false);` at the end with `std::cerr << "test" << std::endl; return 0;` as a sanity check.

**Comment by ProjectBM** [comment]
Did as you said and ran travisbuild.sh but it seems to fail. Strangely enough it failed while building. I usually compile with `cmake . -DCMAKE_BUILD_TYPE=DEBUG && make` so it might be due to the difference in build type.

I ran it with the changes you mentioned and without it and travisbuild.sh still seem to fail. I also tried it on my master branch and the script still failed.

I opened another PR and that branch passes Clang 6.0 - Debug so I can't tell if this is an issue on my end or if Travis is just breaking.

**Comment by 12xx12** [comment]
Travis seems to break on this build. I had some PRs failing in the ARM build too. We had someone with a ARM processor recrreate the steps... that didn't fail - so best add those debug outputs as tigerw suggested

**Comment by ProjectBM** [comment]
For clarification, should I make these changes and make a commit so Travis CI reruns with those changes or should I be running it locally?

**Comment by 12xx12** [comment]
make these changes and commit - we need to sanity check the travis machnine

**Comment by 12xx12** [comment]
maybe we should not not return the universal main to compile everything

**Comment by ProjectBM** [comment]
Seems that the change caused a compile error. Should I change `static int UniversalMain` to `static inline int UniversalMain` and try Travis again?
```
In file included from /home/travis/build/cuberite/cuberite/CMakeFiles/Cuberite.dir/Unity/unity_8_cxx.cxx:4:
/home/travis/build/cuberite/cuberite/src/main.cpp:211:12: error: 'static' function 'UniversalMain' declared in header file should be declared 'static inline' [-Werror,-Wunneeded-internal-declaration]
static int UniversalMain(int argc, char * argv[], bool RunningAsService)

**Comment by 12xx12** [comment]
change the return statement back the way it was.

`/root/cuberite/src/main.cpp:211:12: error: function 'UniversalMain' is not needed and will not be emitted [clang-diagnostic-unneeded-internal-declaration]
static int UniversalMain(int argc, char * argv[], bool RunningAsService)`

**Comment by 12xx12** [comment]
hm... you removed the "test" to std err.. it seems like the executeable isn't launching

**Comment by ProjectBM** [comment]
Uhhh woops, let me add back in

**Comment by 12xx12** [comment]
Hm... so there is a process running but not output 🤔

**Comment by 12xx12** [comment]
Is there anything else logged with the stdio or is everything else logged with the log macros?

**Comment by ProjectBM** [comment]
I think everything is logged by macros since the only outputs using stdio are exceptions/failures.

I could be wrong though since I'm not too familiar with the infrastructure for outputs

**Comment by 12xx12** [comment]
@cuberite/core-team

**Comment by tigerw** [comment]
Master also had a ARM failure: https://travis-ci.org/github/cuberite/cuberite/builds/745295445
But now it's ok again: https://travis-ci.org/github/cuberite/cuberite/builds/745929845

May be an intermittent issue, we'll see. Nonetheless at the time of writing the build's been going 1hr+ with no sign of x64 workers starting, so I wouldn't discount CI just yet.

**Comment by 12xx12** [comment]
#5056  worked fine

**Comment by tigerw** [comment]
@ProjectBM would you like to revert the testing changes? We can give CI another shot.

**Comment by tigerw** [comment]
#5057 passes

**Pull request merged**
