### PR TITLE
Fix errors to support Xcode

### PR DESCRIPTION
**Pull request by hallucino**
Hi,

this is a PR to be able to build with xcode on OSX.

### CODE REVIEW

**Comment by SphinxC0re** [comment]
Can someone test this? @NiLSPACE ? @tigerw ?

**Comment by madmaxoft** [comment]
What was the error message?

I have a feeling that this might have broken some subtle stuff in the json parser. Wouldn't a simple `static_cast<unsigned>(-1)` have fixed it, too? Because that is unlikely to break other stuff.

**Comment by NiLSPACE** [comment]
@SphinxC0re I can't test this. My internet is way too slow. Pushing a few lines to WorldEdit already took 1 minute, so downloading a whole repo would take way too long.

**Comment by SamJBarney** [comment]
I'll test it

**Comment by SamJBarney** [comment]
Can't get it to compile in Xcode, but not related to what he did.
screen shot 2015-07-09 at 9 05 28 am

**Comment by SamJBarney** [comment]
Ummmm.... I can't get it to compile from the commandline either. Too many old-style cast errors. Is this coming from some recent change to the compile flags?
screen shot 2015-07-09 at 9 11 56 am
screen shot 2015-07-09 at 9 10 39 am

**Comment by hallucino** [comment]
yeah you must add -Wno-error=old-style-cast in config files but I'm not sure how to do it automatically :/

**Comment by SamJBarney** [comment]
@hallucino after my fix that does away with errors from the command line gets merged, you will need to fix the errors that show up in SslHTTPConnection.cpp. Those don't break anything with a command line build, but XCode freaks out about it.

**Comment by hallucino** [comment]
It is not only in SslHttpConnection.cpp. I got that in many files.

I generated that with:
cmake -G Xcode -DCMAKE_BUILD_TYPE=RELEASE ..

I'm not sure how to fix that directly for all modules, but I will try to add that in this PR.

**Comment by SamJBarney** [comment]
I've already fixed it for all the others. I'm just waiting for my code to be pulled. You don't have to worry about it.

**Comment by hallucino** [comment]
I could remove this PR due to your PRs ?

**Comment by SamJBarney** [comment]
No, but mine would make yours easier to do.

**Pull request closed without merging**
