### PR TITLE
Gargaj Combined

### PR DESCRIPTION
**Pull request by SafwatHalaby**
Combines these into one, to save @Gargaj the trouble of rebasing 3 times.
- https://github.com/cuberite/cuberite/pull/2738
- https://github.com/cuberite/cuberite/pull/2737
- https://github.com/cuberite/cuberite/pull/2708

All of the original PRs are ripe for merge, but they are blocked by our current Github settings and mandate needless rebases by the original PR creator. I have created this PR to highlight the rebase issue. Discuss [here](http://forum.mc-server.org/showthread.php?tid=2252) (Or here) before merging this.

### CODE REVIEW

**Comment by Gargaj** [comment]
I don't really mind rebasing as such, as long as I know that I should do it for a good reason, i.e. it's something everything agrees on that it should be merged. It's a bit laborious but e.g. at one point when I had a ton of PRs I just went to IRC and talked to @SphinxC0re and we went through them in one session. It's a lot more obtuse when a PR ends up just sitting there (rebased and ready to merge) because noone reacts to it. And even when Github doesn't let you merge automatically, you can still merge manually via Git.

**Comment by SafwatHalaby** [comment]
I cannot merge  manually via git because I do not have the permissions. I am a `colaborator`, not an `owner`.

**Comment by Gargaj** [comment]
Well I meant "you" as indistinct plural :)

**Comment by SafwatHalaby** [comment]
Got it ;)
While you're here, feel free to join the IRC and start a merge-spree of your 4 PRs.

**Pull request closed without merging**
