### PR TITLE
Anvil storage: load block entities from both old and new name-styles.

### LINKED ISSUE #3783: Support newer BlockEntity names in imported worlds
Vanilla has changed the BlockEntity names, as saved to the world files. We need to make our loader support both the old ones and the new ones.

### PR DESCRIPTION
**Pull request by madmaxoft**
Fixes #3783 .

### CODE REVIEW

**Comment by Seadragon91** [comment]
Used this list to create a flat world which all the block entities:
http://minecraft.gamepedia.com/Block_entity

This is the output from console:
```
[11:44:23] WorldLoader(creative_1_12): Block entity mismatch: block type daylightdetectorinverted (178), type "minecraft:daylight_detector", at {-5, 4, -24}; the entity will be lost.
[11:44:23] WorldLoader(creative_1_12): Block entity mismatch: block type unpoweredcomparator (149), type "minecraft:comparator", at {-4, 4, -27}; the entity will be lost.
[11:44:23] WorldLoader(creative_1_12): Block entity mismatch: block type bedblock (26), type "minecraft:bed", at {-4, 4, -28}; the entity will be lost.
[11:44:23] WorldLoader(creative_1_12): Block entity mismatch: block type unpoweredcomparator (149), type "minecraft:comparator", at {-5, 4, -27}; the entity will be lost.
[11:44:23] WorldLoader(creative_1_12): Block entity mismatch: block type bedblock (26), type "minecraft:bed", at {-5, 4, -28}; the entity will be lost.
[11:44:23] WorldLoader(creative_1_12): Block entity mismatch: block type daylightsensor (151), type "minecraft:daylight_detector", at {-4, 4, -24}; the entity will be lost.
[11:44:24] WorldLoader(creative_1_12): Block entity mismatch: block type standingbanner (176), type "minecraft:banner", at {-4, 4, -1}; the entity will be lost.
[11:44:24] WorldLoader(creative_1_12): Block entity mismatch: block type pinkshulkerbox (225), type "minecraft:shulker_box", at {-4, 4, -9}; the entity will be lost.
[11:44:24] WorldLoader(creative_1_12): Block entity mismatch: block type enchantmenttable (116), type "minecraft:enchanting_table", at {-4, 4, -16}; the entity will be lost.
```

Problems that maybe could be fixed in this pull request:
* The sign is not read correctly. Got `{"text":"line 1"}`, expected `line 1`
* Mob spawner is not read correctly. Got pig, expected wolf
* The juke box should contain the item disc

This are more complex and should be done in a new pull request:
* Every block entity can have a custom name, that can be set with an anvil
* The bed has now colors
* The shulker box is a new container that will keep the items stored as NBT, if it's broken

Hope I found all changes :)

Added a flat world that contains the block entities. They are placed at coords 0 5 0
[creative_1_12.zip](https://github.com/cuberite/cuberite/files/1084524/creative_1_12.zip)

**Comment by madmaxoft** [comment]
Well, I only added the expected types, I didn't touch the loading code. I guess I could fix those simple things, too.

Thanks for the world, I have something to test on (don't have access to a MC client right now).

**Comment by madmaxoft** [comment]
No, probably not. I fixed the sign text loading, but won't fix the other two:
  - Spawner needs a complete rewrite anyway, Vanilla supports spawning multiple entities and has potentials, we need that in order to load the spawners properly.
  - Juke box can contain any item (possibly including a shulker box?), so we need to change the `cJukeboxEntity` object.
Both seem out of scope of this PR.

**Comment by Seadragon91** [comment]
Okay thanks.

**Comment by madmaxoft** [comment]
Can this be merged, then?

**Pull request merged**
