### PR TITLE
Outsourced all libraries

### LINKED ISSUE #2429: Outsource all librarys
We should make every library a submodule since they are not part of the project itself.
 - [ ] CMake-Coverage
 - [ ] Expat
 - [x] JsonCpp
 - [x] LibEvent
 - [ ] Lua
 - [ ] LuaExpat
 - [x] PolarSSL
 - [ ] SQLite
 - [x] SQLiteCpp
 - [x] TCLAP
 - [ ] ToLua++
 - [ ] Zlib

### PR DESCRIPTION
**Pull request by SphinxC0re**
Fixes  #2429

### CODE REVIEW

**Comment by madmaxoft** [comment]
Ugh! Another big PR that will not be displayed by GitHub.

**Comment by SphinxC0re** [comment]
I am so sorry

**Comment by SphinxC0re** [comment]
But it's basically all libraries outsourced

**Comment by madmaxoft** [comment]
You should add a check for each library in the top-level CMakeLists.txt file, so that an error is produced by cmake if any of the submodules are missing. Basically, this thing:
```
if (NOT EXISTS ${CMAKE_SOURCE_DIR}/lib/SQLiteCpp/CMakeLists.txt)
	message(FATAL_ERROR "SQLiteCpp is missing in folder lib/SQLiteCpp. Have you initialized the submodules / downloaded the extra libraries?")
endif()
```

**Comment by SphinxC0re** [comment]
I hope I didn't miss any submodule

**Comment by madmaxoft** [comment]
You should indent with tabs, not spaces, in the CMakeLists.txt file.

**Comment by SphinxC0re** [comment]
Oh, I think QtCreator f***ed this up :P

**Comment by SphinxC0re** [comment]
Thank you for making my comments more appropriate :smile:

**Comment by SphinxC0re** [comment]
Any more objections? Or should I just rebase and squash?

**Comment by madmaxoft** [comment]
I don't have any objections, perhaps someone else may have some?

**Comment by SphinxC0re** [comment]
@cuberite/core-team ?

**Comment by Seadragon91** [comment]
I would suggest waiting until tomorrow.

**Comment by SphinxC0re** [comment]
The world is not yet ready for submodules :D but tomorrow it will be

**Comment by NiLSPACE** [comment]
No objection here

**Comment by madmaxoft** [comment]
Wow, and finally the language bar on the projects main page shows true language statistics only for Cuberite :)

**Comment by NiLSPACE** [comment]
Finally :)

**Comment by SphinxC0re** [comment]
I have to admit: That's what I was aiming for ;)

**Pull request merged**
