### PR TITLE
Don't return const ref params and removed functions from ManualBindings.cpp

### PR DESCRIPTION
**Pull request by Seadragon91**

### CODE REVIEW

**Comment by madmaxoft** [comment]
You seem to have forgotten to commit the changes in the ToLua++ submodule.

**Comment by Seadragon91** [comment]
Yes just did that, should have them pushed at first :)

**Comment by madmaxoft** [comment]
Seems like we have a new LuaBindings expert :)

**Comment by madmaxoft** [comment]
This doesn't seem to work for me, the `cWebAdmin:GetHTMLEscapedString()` still returns its param as the second return value.

**Comment by madmaxoft** [comment]
Ah, I see, that's because on my system (Win, MSVC, no `xxd`) the build process doesn't use the system-provided Lua, and therefore compiles a ToLua++ binary rather than using it as Lua scripts.

**Pull request merged**
