### PR TITLE
Compile.sh namechange to cuberite

### PR DESCRIPTION
**Pull request by SafwatHalaby**

### CODE REVIEW

**Comment by madmaxoft** [comment]
Looks good to me, but someone Linux-savvy should look it over :)

**Comment by SafwatHalaby** [comment]
Linux savvy guy here :P

**Comment by SafwatHalaby** [comment]
Closed accidentally, I'll merge once CI is done.

**Comment by SphinxC0re** [comment]
Please squash and rebase onto the current master

**Comment by SafwatHalaby** [comment]
I don't get this change. Why did it force me to merge "master" before merging the pull request?

**Comment by madmaxoft** [comment]
You shouldn't merge, you should rebase (and squash if multiple "fix" commits).

It is GitHub's requirement since when we turned on "required CI build status" (GH won't allow merging PRs until CI builds succeed)

**Comment by SafwatHalaby** [comment]
Yes, right now, I should rebase. But I did not intend to merge master into this branch.

The "Merge pull request" button was grayed out, and it wouldn't let me merge unless I clicked the "Update branch" first, which merged master into this branch.

**Comment by SphinxC0re** [comment]
Some changes seem to be from another PR. The namechange PR

**Comment by SafwatHalaby** [comment]
Oh, sorry. That's exactly what I tried to avoid.
Either the CIs are mis-configured or I'm missing something. Can someone explain this?:
One cannot merge when this message is shown: "This branch is out-of-date with the base branch". Why is that?

**Comment by SafwatHalaby** [comment]
E.g., right now, https://github.com/cuberite/cuberite/pull/2491 is supposed to be ready for merging. But merging it is impossible unless you click "Update branch" first.

**Comment by worktycho** [comment]
We've enabled https://github.com/blog/2051-protected-branches-and-required-status-checks

**Comment by worktycho** [comment]
It disables merging unless CI passed, and the merge could be done as a fast forward merge.

**Comment by SafwatHalaby** [comment]
Why, for instance, is https://github.com/cuberite/cuberite/pull/2491 not mergable right now?

**Comment by madmaxoft** [comment]
Instead of clicking that button, you should use your command-line-fu and rebase the PR onto the current master. That's much cleaner in the history.

**Comment by madmaxoft** [comment]
Because it would not be a fast-forward merge, it would be a three-way merge. I need to rebase it.

**Comment by SafwatHalaby** [comment]
Got it. Sorry for the history pollution. That button confused me.

**Comment by SafwatHalaby** [comment]
`Because it would not be a fast-forward merge`
afaik Github merges are never fast-forward. I think that it won't merge simply because it needs rebasing, and it will be non-ff anyways. Am I missing something?

**Comment by worktycho** [comment]
They don't do fast forward merges, but they use the same rules as the rules on ff merges. the idea being that it guarantees that you won't get a build failure due to a weird interaction that git can't spot.

**Pull request merged**
