### PR TITLE
Fix building with clang 8.0

### PR DESCRIPTION
**Pull request by Bond-009**

### CODE REVIEW

**Comment by madmaxoft** [comment]
If there's a specific warning for the use of extra semicolons, I propose we instead turn that warning off - this diff clearly shows we don't want it.

**Comment by Bond-009** [comment]
@peterbell10 That's just a nasty hack IMO.
@madmaxoft There are also plenty of places where we don't have semicolons after the macro.

**Comment by madmaxoft** [comment]
The "nasty hack" is a pretty standard way of enforcing semicolons after macros. And I for one would very much appreciate if we did require the semicolons, so that the macros don't stand out in the code as something different from everything else.

**Comment by Bond-009** [comment]
Alright, I changed it.

**Pull request merged**
