### PR TITLE
It is time to remove the statistics upgrade map

### PR DESCRIPTION
**Pull request by tigerw**

### CODE REVIEW

**Comment by peterbell10** [comment]
Surely 1 month is hardly enough of a transition period?

**Comment by tigerw** [comment]
With the breathless flavour of CI we have where only master is really supported, you may be surprised! Though without telemetry no one can really tell. Do you have any suggestions?

**Comment by tigerw** [comment]
ping

**Comment by 12xx12** [comment]
My suggestion would be to wait for the next newsletter and send out the message with the info that satitstics data and old achievements with a reasonable date for removal

**Comment by peterbell10** [comment]
Looking again, I see that GitHub rounding down when it said 1 month. It's more like 2 at this point. That's more reasonable but I would prefer, say,  6 months or so. It really doesn't hurt us much to keep it around for a while longer.

**Comment by bearbin** [comment]
Yeah, this mapping doesn't really hurt us ATM. This can go in the deep freeze for another 6 months, then it'll be fine.

**Comment by tigerw** [comment]
Close enough?

**Comment by koutsie** [comment]
+1

**Review by koutsie — APPROVED** [review]
ISNI?

**Comment by 12xx12** [comment]
I'd rather note this in a "news" article with a date and then do it at that date. This still doesn't hurt anyone

**Comment by 12xx12** [comment]
I knew i forgot something in the newsletter

**Comment by bearbin** [comment]
Oh no, another argument for having a newsletter planning issue. Either way this is probably fine to go in now once the conflict is fixed.

**Comment by tigerw** [comment]
😃

**Comment by tigerw** [comment]
I'd like to merge if it passes.

**Pull request merged**
