### PR TITLE
Bulk clearing of whitespace

### LINKED ISSUE #2971: Tab convention
We often get lots of whitespace in PRs because different IDEs treat tabs differently. We must establish a clear tab convention.

This PR is in fact only a one line change: https://github.com/cuberite/cuberite/pull/2969/files

### PR DESCRIPTION
**Pull request by LogicParrot**
closes #2971 (Discuss there before merging)

Used script:
```
#!/bin/sh
set -e
cd ~/cuberite/src
find -name "*.cpp" | grep -vf ~/ignore.txt | while read line; do
perl -pe 's/^\t+$//g' -i $line
done
```

ignore.txt contains:
```
LeakFinder.cpp
LeakFinder.h
```

I ran the script twice, second time with `find -name "*.h"`

### CODE REVIEW

**Comment by LogicParrot** [comment]
Squashed and Rebased, cleared headers too.

**Comment by SphinxC0re** [comment]
Nice! Finally we're getting rid of these all at once. So for the future there is no way to complain about randomly removed ones

**Comment by LogicParrot** [comment]
And to keep it tidy, we should not accept any PR which re-introduces useless tabs.

**Comment by SphinxC0re** [comment]
Agreed ;-)

**Comment by madmaxoft** [comment]
Add a check to CheckBasicStyle.lua, then it will be enforced for the PRs.

Julian Laubstein <notifications@github.com> wrote:

>Agreed ;-) 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cuberite/cuberite/pull/2974#issuecomment-180800698

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by LogicParrot** [comment]
@madmaxoft #2978

**Comment by SphinxC0re** [comment]
@madmaxoft despite the fact, that this is totally the wrong place for that:
I wrote you a PM and an email like 6 days ago. Did any one of these messages reach you?

**Comment by NiLSPACE** [comment]
What? This PR is about removing all the tabs in the Cuberite source and then you guys talked about enforcing it on all new PR's. Xoft said how we can add a check for every PR and it's the wrong place?

**Comment by SphinxC0re** [comment]
Read again. There's a colon

**Comment by NiLSPACE** [comment]
Whoops, I'm so sorry :|

**Comment by LogicParrot** [comment]
@NiLSPACE This is about clearing tabs in empty lines, not about clearing all tabs ;)

**Comment by NiLSPACE** [comment]
Yeah sorry, that's what I meant. 

Man, I've been working too long. I'm making so many mistakes :|

**Pull request merged**
