### PR TITLE
CI: Add arm build to travis

### PR DESCRIPTION
**Pull request by peterbell10**
Travis is adding support for arm based CPUs. 

https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support

### CODE REVIEW

**Comment by madmaxoft** [comment]
Is it wise to add on-ARM compilation? It almost doubles the build time. It might be better to cross-compile for ARM on an x64 and then only test the actual executable on an ARM. But that might be difficult, if not impossible, to set up.

**Comment by madmaxoft** [comment]
Alright, let's do this, but we should also try to use some cache for the builds so that they all speed up (similar to https://github.com/cuberite/cuberite/issues/4378#issuecomment-529096402)

**Comment by peterbell10** [comment]
Okay, so everything except macos is now using `ccache`. However, even after a lot of fiddling about, the `arm64` builds aren't actually any faster... It looks like travis's caching mechanism is actually broken on their `arm64` images at the moment:
```
Installing md5deep
Reading package lists...
Building dependency tree...
Reading state information...
md5deep is already the newest version (4.4-2).
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.
/home/travis/.casher/bin/casher: line 230: md5deep: command not found
```

**Comment by peterbell10** [comment]
On the plus side, everything else is much quicker now so the overall CI running time is still actually faster (as long as nobody changes `World.h`).

**Pull request merged**
