### PR TITLE
Fixed cFile API bindings.

### LINKED ISSUE #3297: Creation of the API Doc is broken
Commit id:        f07dc71648eec56d88a35f42d55bfa8d007e8fab

### Expected behavior
The hooks and article links should working.

### Actual behavior
The hooks and article links are not working.

@tigerw mentioned it in the [forum](https://forum.cuberite.org/thread-434-post-26308.html#pid26308).

### Steps to reproduce the behavior
Browse to http://api-docs.cuberite.org/ and look at articles and hooks. All hooks are not documented and links are also missing.

Have looked into that and after reverting [Fixed RasPi builds of unit tests.](https://github.com/cuberite/cuberite/pull/3281) it works fine again.

I think the problem lies in the combination of `ASSERT` and `_DEBUG`. Example:
The 2 variables are only available in debug mode.
[LuaState.cpp#L1697L1700](https://github.com/cuberite/cuberite/blob/master/src/Bindings/LuaState.cpp#L1697L1700)
```
#ifdef _DEBUG
	auto srcTop = lua_gettop(a_SrcLuaState);
	auto dstTop = lua_gettop(m_LuaState);
#endif
```
but they are accessed here, in release mode:
[LuaState.cpp#L1706L1707](https://github.com/cuberite/cuberite/blob/master/src/Bindings/LuaState.cpp#L1706L1707)
```
ASSERT(lua_gettop(a_SrcLuaState) == srcTop + 3);
ASSERT(lua_gettop(m_LuaState) == dstTop + 1);
```

### PR DESCRIPTION
**Pull request by madmaxoft**
Fixes #3297 .

### CODE REVIEW

**Comment by madmaxoft** [comment]
`ASSERT` was used instead of `VERIFY`, which means that the code to read API function params from Lua wasn't compiled into the Release-mode executable.

**Comment by Seadragon91** [comment]
Tested it and it works fine :smiley:

**Comment by madmaxoft** [comment]
Still failing in the CI

**Comment by Seadragon91** [comment]
Now we see this undocumentedf api symbols.
@LogicParrot has this problem in his pull request https://github.com/cuberite/cuberite/pull/3295#issuecomment-237974159

**Comment by madmaxoft** [comment]
Ah, that's because the "official" list of undocumented symbols already got corrupted by the error. Regenerating the "official" list...

**Pull request merged**
