### PR TITLE
ReTyped block ids

### PR DESCRIPTION
**Pull request by SphinxC0re**
As discussed in #2516

### CODE REVIEW

**Comment by SphinxC0re** [comment]
@madmaxoft HELP! :sob:

**Comment by worktycho** [comment]
tolua doesn't support assignments in declarations. We either need to patch tolua, or do something clever with macros, or use two sets of declarations.

**Comment by tigerw** [comment]
OMG.

This is *waaaay* too verbose, xoft, c'mon.

**Comment by NiLSPACE** [comment]
Would :
```cpp
static const BLOCKTYPE 
   E_BLOCK_AIR = 0,
   E_BLOCK_STONE = 1,
   // ....

```

or something simular work?

**Comment by tigerw** [comment]
What was the warning that this fixed? The original issue casts ::GetBlock to a BLOCKTYPE, which I thought it already returned?

**Comment by worktycho** [comment]
It wont work. If you want to use a single declaration in c++ we need to patch tolua to ignore the equals.

**Comment by SphinxC0re** [comment]
We have to patch tolua anyway

**Comment by worktycho** [comment]
What might work is:
```
static const BloCKTYPE
#ifdef 0
enum BLOCKTYPE // tolua_export
{
#endif
   E_BLOCK_AIR = 0,
   E_BLOCK_STONE = 1,
   // ....
#ifdef 0
}
#endif
;

**Comment by SphinxC0re** [comment]
Doesn't work. Any other suggestions?

**Comment by madmaxoft** [comment]
You didn't use @worktycho's suggestion, it should have worked.

**Comment by SphinxC0re** [comment]
Oh, I did try it locally and it failed

**Comment by madmaxoft** [comment]
Try the updated one, with `tolua_begin` instead

**Comment by SphinxC0re** [comment]
I get an error:
```
Error: macro names must be identifiers
 #ifdef 0
        ^
```

**Comment by madmaxoft** [comment]
Okay, let me try locally. I'll rebase this onto current master, too.

**Comment by madmaxoft** [comment]
There, this should work.

**Comment by SphinxC0re** [comment]
looks good

**Comment by SphinxC0re** [comment]
circle seems to be stuck

**Comment by madmaxoft** [comment]
Yes, they seem to be experiencing some problems. I've verified that the basic style checks out. Merging manually.

**Comment by SphinxC0re** [comment]
And there go another three warnings :smile:

**Comment by tigerw** [comment]
Does nobody care what I say? Why was there a change from enumerations, what should be used, to something that is essentially a ton of static constants, with *less* type safety, all in the name of "fixing compiler warnings"?

**Comment by worktycho** [comment]
Because this change has to happen if we want to support mods that add blocktypes. Enum have undefined behavior for values that aren't in the enum, so we can't use other values. And we have better type safety for how we want to use blocktypes in the future.

**Comment by tigerw** [comment]
Assuming that the extensibility was an intended side-effect of this PR, I argue that you could do it perfectly well having a separate dynamic structure for custom handlers and their ID mappings.

After all, what could this change have possibly achieved? Comparing custom-defined BLOCKTYPEs within the core server? Dynamically creating a new static constant? The server should have its own, unchangeable and inextensible enumeration of basic blocks, and this didn't exactly further that intention.

**Comment by worktycho** [comment]
And what about the block array which also uses blocktype? That needs to store custom blocks.

**Comment by tigerw** [comment]
Damn, you have a point. It occurred to me that storing blocks necessitates mixing the classed enum values and plain unsigned chars. So it looks like extensible handlers demands no enumeration usage. That's really unsatisfying :(

**Pull request merged**
