### PR TITLE
Entities are never lost

### LINKED ISSUE #3104: Spawning in an ungenerated chunk causes fatal problems
When spawning in an ungenerated chunk, cWorld::3836 is not executed, causing instability in cPlayer.

### PR DESCRIPTION
**Pull request by LogicParrot**
Closes #3104 #3045

### CODE REVIEW

**Comment by tigerw** [comment]
Wouldn't this mean entities will forcibly load chunks?

**Comment by LogicParrot** [comment]
@tigerw Yes.

This solution is very simple, previously suggested by @NiLSPACE:
If a mob is being sent to an unloaded chunk, load it or generate it, and put the mob there as usual. If the chunk is too far, it will not tick and will unload quickly. This is very much desired: If I send an entity to a far chunk, I'd like the server to load it and add the entity to it, then save and unload it.

**Comment by SphinxC0re** [comment]
Could you convert [this](https://github.com/LogicParrot/cuberite/blob/chunkStability/src/World.cpp#L1017) into a C++11 loop

**Comment by LogicParrot** [comment]
@SphinxC0re will do.

**Comment by SphinxC0re** [comment]
Also why are you still not working in the canon repo?

**Comment by SphinxC0re** [comment]
Also (sorry for comment chaining) there is another change on line 3000 or so where you could easily convert such a loop to C++11

**Comment by LogicParrot** [comment]
@SphinxC0re You could easily comment on the diff though.

>Also why are you still not working in the canon repo?

1. Habit. Maybe I should do `git remote remove parrot` to force-break it.
2. It's a bit tidier. Look at how many branches you guys have here :P

**Comment by SphinxC0re** [comment]
I think we'll be okay with the branch count :wink:

**Comment by LogicParrot** [comment]
In a followup PR, I think I'll also implement @madmaxoft 's idea:

> My initial idea on how to solve this was to introduce a m_HasAllNeighbors flag for each chunk that would be true if all 8 neighbors of this chunk were valid; and all entities in such a chunk would be ticked only if the flag is true. This would mean that entities on loaded world's border won't be ticked, which seems like a good idea to me - minecarts would stop moving when they reach the edge of the world, rather than when leaving the loaded world completely etc.

I could then ake advantage of that flag to reimplement #3097 more efficiently and remove m_CachedSentChunk: `if !GetParentChunk()->HasAllNeighbords then freeze player`.

**Comment by LogicParrot** [comment]
@SphinxC0re There are lots of them. But I prefer not to mix PRs. We need a seperate PR which refactors all loops.

**Comment by LogicParrot** [comment]
This makes Cuberite unstable after removing a world and then logging in, unless one is near the spawn point.
It also makes it unstable on world travel when warping to an ungenerated chunk.
It makes it a total mess in the Forgetful schema.

I am going to merge this despite the lack of review. Please do review it.

**Comment by SphinxC0re** [comment]
Why are you merging this despite the proposed instability of the builds. You shouldn't.

**Comment by LogicParrot** [comment]
The build is unstable **without** this.

**Comment by LogicParrot** [comment]
I edited my post to avoid confusion.

**Pull request merged**
