### PR TITLE
Implement formatting codes

### LINKED ISSUE #2695: Formatting codes don't work
All the color codes work properly, but these formatting codes do not:
@l - Bold
@n - Underline
@o - Italic
@k - Magic
@m - Strike

Also, perhaps @ should be changed to &, since players from Bukkit servers are more used to &?

### PR DESCRIPTION
**Pull request by mathiascode**
Implements formatting codes similar to Bukkit (&-symbol).
Fixes #2695
Fixes https://github.com/cuberite/Core/issues/84

### CODE REVIEW

**Comment by mathiascode** [comment]
Still needs work.

**Comment by mathiascode** [comment]
This is not abandoned, but I have some other priorities right now.

**Comment by JK2Kgit** [comment]
@mathiascode I would like to ask if you are planning to do it or not. If not I will be happy to take it.

**Comment by mathiascode** [comment]
@JK2Kgit Feel free to take over. :)

**Comment by PureTryOut** [comment]
:(

**Comment by tonitch** [comment]
> :(

https://github.com/cuberite/cuberite/pull/5416

**Pull request closed without merging**
