### PR TITLE
Added GeoTrust Root Certificate

### PR DESCRIPTION
**Pull request by worktycho**

### CODE REVIEW

**Comment by madmaxoft** [comment]
Did Mojang change their signer again? Ugh.

Seems like you'll have to update CheckBasicStyle.lua so that it accepts the double-equal-sign in base64 encoding of the cert.

**Comment by bearbin** [comment]
The build failing on macs is normal, until we can get the mac machine all up and running.

**Comment by worktycho** [comment]
Fixed the checkbasicstyle script by ignoring ==\

**Comment by worktycho** [comment]
Actually fixed now.

**Comment by bearbin** [comment]
After this is pushed out, I will send a update newsletter.

**Comment by bearbin** [comment]
Merge?

**Comment by madmaxoft** [comment]
Looks good to me

**Pull request merged**
