### PR TITLE
cBeaconEntity: fix no world crash

### LINKED ISSUE #3915: Beacons crash server (cBlockArea)
Client version:   1.11.2
Server OS:        Linux
Commit id:        83ff815d1e5a03db3a2ea2a13319cd5c75a9687a

### Expected behavior
You can use WorldEdit to interact with or place beacons.

### Actual behavior
The server crashes. This started happening after block entity support was introduced in cBlockArea (fe4253834919d6c742c59c701d3d5ce8285f4504).
```
[17:33:42]   D:    | Cuberite has encountered an error and needs to close
[17:33:42] Details | SIGSEGV: Segmentation fault
[17:33:42] Cuberite local build build id: Unknown
[17:33:42] from commit id: approx: 028ed77ca9579eb38a02007e98d75e0dbe9509d2 built at: approx: 2017-08-04 00:01:22 +0200
./Cuberite2(_Z15PrintStackTracev+0x15)[0x55e56a31ea15]
./Cuberite2(+0x29ea04)[0x55e56a30ca04]
/lib/x86_64-linux-gnu/libc.so.6(+0x33030)[0x7f5fe5cc1030]
./Cuberite2(_ZN13cBeaconEntity12UpdateBeaconEv+0x62)[0x55e56a58d7a2]
./Cuberite2(_ZN13cBeaconEntityC2EhhiiiP6cWorld+0x6b)[0x55e56a58d8fb]
./Cuberite2(_ZN12cBlockEntity5CloneEiii+0x3ac)[0x55e56a58e8bc]
./Cuberite2(_ZN10cBlockArea12cChunkReader11BlockEntityEP12cBlockEntity+0x67)[0x55e56a233da7]
./Cuberite2(_ZN6cChunk10GetAllDataER18cChunkDataCallback+0xf8)[0x55e56a24d7c8]
./Cuberite2(_ZN9cChunkMap18ForEachChunkInRectEiiiiR18cChunkDataCallback+0x2c7)[0x55e56a260e57]
./Cuberite2(_ZN10cBlockArea4ReadER21cForEachChunkProviderRK7cCuboidi+0x18b)[0x55e56a23bedb]
./Cuberite2(+0x2e1f94)[0x55e56a34ff94]
./Cuberite2(+0x6565ed)[0x55e56a6c45ed]
./Cuberite2(+0x66a8c7)[0x55e56a6d88c7]
./Cuberite2(+0x656d8d)[0x55e56a6c4d8d]
./Cuberite2(+0x655c8b)[0x55e56a6c3c8b]
./Cuberite2(+0x656ffa)[0x55e56a6c4ffa]
./Cuberite2(lua_pcall+0x46)[0x55e56a6c0036]
./Cuberite2(_ZN9cLuaState12CallFunctionEi+0x59)[0x55e56a333fc9]
./Cuberite2(_ZN17LuaCommandHandler14ExecuteCommandERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS6_EEP7cPlayerRKS6_P22cCommandOutputCallback+0xfa)[0x55e56a349caa]
./Cuberite2(_ZN14cPluginManager13HandleCommandER7cPlayerRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb+0x130)[0x55e56a375fb0]
./Cuberite2(_ZN14cPluginManager12CallHookChatER7cPlayerRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1d)[0x55e56a3760bd]
./Cuberite2(_ZN13cClientHandle10HandleChatERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x83)[0x55e56a269f53]
./Cuberite2(_ZN15cProtocol_1_9_023HandlePacketChatMessageER11cByteBuffer+0x5c)[0x55e56a455fdc]
./Cuberite2(_ZN15cProtocol_1_9_012HandlePacketER11cByteBufferj+0x53e)[0x55e56a45df4e]
./Cuberite2(_ZN15cProtocol_1_9_015AddReceivedDataEPKcm+0x30e)[0x55e56a4618be]
./Cuberite2(_ZN15cProtocol_1_9_012DataReceivedEPKcm+0x6a)[0x55e56a46211a]
./Cuberite2(_ZN19cProtocolRecognizer12DataReceivedEPKcm+0x23)[0x55e56a46b3f3]
./Cuberite2(_ZN13cClientHandle20ProcessProtocolInOutEv+0x71)[0x55e56a26d451]
./Cuberite2(_ZN13cClientHandle4TickEf+0x24)[0x55e56a26fb14]
./Cuberite2(_ZN6cWorld11TickClientsEf+0x193)[0x55e56a2fdd13]
[17:33:42]   D:    | Cuberite has encountered an error and needs to close
[17:33:42] Details | SIGABRT: Server self-terminated due to an internal fault
[17:33:42] Cuberite local build build id: Unknown
[17:33:42] from commit id: approx: 028ed77ca9579eb38a02007e98d75e0dbe9509d2 built at: approx: 2017-08-04 00:01:22 +0200
./Cuberite2(_Z15PrintStackTracev+0x15)[0x55e56a31ea15]
./Cuberite2(+0x29ea04)[0x55e56a30ca04]
/lib/x86_64-linux-gnu/libc.so.6(+0x33030)[0x7f5fe5cc1030]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf)[0x7f5fe5cc0fcf]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f5fe5cc23fa]
./Cuberite2(+0x29ea09)[0x55e56a30ca09]
/lib/x86_64-linux-gnu/libc.so.6(+0x33030)[0x7f5fe5cc1030]
./Cuberite2(_ZN13cBeaconEntity12UpdateBeaconEv+0x62)[0x55e56a58d7a2]
./Cuberite2(_ZN13cBeaconEntityC2EhhiiiP6cWorld+0x6b)[0x55e56a58d8fb]
./Cuberite2(_ZN12cBlockEntity5CloneEiii+0x3ac)[0x55e56a58e8bc]
./Cuberite2(_ZN10cBlockArea12cChunkReader11BlockEntityEP12cBlockEntity+0x67)[0x55e56a233da7]
./Cuberite2(_ZN6cChunk10GetAllDataER18cChunkDataCallback+0xf8)[0x55e56a24d7c8]
./Cuberite2(_ZN9cChunkMap18ForEachChunkInRectEiiiiR18cChunkDataCallback+0x2c7)[0x55e56a260e57]
./Cuberite2(_ZN10cBlockArea4ReadER21cForEachChunkProviderRK7cCuboidi+0x18b)[0x55e56a23bedb]
./Cuberite2(+0x2e1f94)[0x55e56a34ff94]
./Cuberite2(+0x6565ed)[0x55e56a6c45ed]
./Cuberite2(+0x66a8c7)[0x55e56a6d88c7]
./Cuberite2(+0x656d8d)[0x55e56a6c4d8d]
./Cuberite2(+0x655c8b)[0x55e56a6c3c8b]
./Cuberite2(+0x656ffa)[0x55e56a6c4ffa]
./Cuberite2(lua_pcall+0x46)[0x55e56a6c0036]
./Cuberite2(_ZN9cLuaState12CallFunctionEi+0x59)[0x55e56a333fc9]
./Cuberite2(_ZN17LuaCommandHandler14ExecuteCommandERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS6_EEP7cPlayerRKS6_P22cCommandOutputCallback+0xfa)[0x55e56a349caa]
./Cuberite2(_ZN14cPluginManager13HandleCommandER7cPlayerRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb+0x130)[0x55e56a375fb0]
./Cuberite2(_ZN14cPluginManager12CallHookChatER7cPlayerRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1d)[0x55e56a3760bd]
./Cuberite2(_ZN13cClientHandle10HandleChatERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x83)[0x55e56a269f53]
./Cuberite2(_ZN15cProtocol_1_9_023HandlePacketChatMessageER11cByteBuffer+0x5c)[0x55e56a455fdc]
./Cuberite2(_ZN15cProtocol_1_9_012HandlePacketER11cByteBufferj+0x53e)[0x55e56a45df4e]
./Cuberite2(_ZN15cProtocol_1_9_015AddReceivedDataEPKcm+0x30e)[0x55e56a4618be]
./Cuberite2(_ZN15cProtocol_1_9_012DataReceivedEPKcm+0x6a)[0x55e56a46211a]
```

```
Currently logging to "crash2.txt".
Logs will be appended to the log file.
Output is being logged and displayed.
Starting program: /home/kaboomserver/server/Cuberite_debug 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6d7b700 (LWP 31138)]
[New Thread 0x7ffff657a700 (LWP 31139)]
[New Thread 0x7ffff5d79700 (LWP 31140)]
[New Thread 0x7fffee991700 (LWP 31141)]
[New Thread 0x7fffee190700 (LWP 31142)]
[New Thread 0x7fffed98f700 (LWP 31143)]
[New Thread 0x7fffec989700 (LWP 31144)]
[New Thread 0x7fffec188700 (LWP 31145)]
[New Thread 0x7fffeb987700 (LWP 31146)]
[New Thread 0x7fffeb186700 (LWP 31147)]
[New Thread 0x7fffea985700 (LWP 31148)]
[New Thread 0x7fffe997f700 (LWP 31149)]
[New Thread 0x7fffe917e700 (LWP 31150)]
[New Thread 0x7fffe897d700 (LWP 31151)]
[New Thread 0x7fffd3fff700 (LWP 31154)]
[New Thread 0x7fffd37fe700 (LWP 31155)]
[New Thread 0x7fffd27f8700 (LWP 31156)]
[New Thread 0x7fffd1ff7700 (LWP 31157)]
[New Thread 0x7fffd17f6700 (LWP 31158)]
[New Thread 0x7fffd0ff5700 (LWP 31159)]
[New Thread 0x7fffc7fff700 (LWP 31160)]
[New Thread 0x7fffc6ff9700 (LWP 31163)]
[New Thread 0x7fffc67f8700 (LWP 31164)]
[New Thread 0x7fffc5ff7700 (LWP 31165)]
[New Thread 0x7fffc57f6700 (LWP 31166)]
[New Thread 0x7fffc4ff5700 (LWP 31167)]
[New Thread 0x7fffc3fef700 (LWP 31168)]
[New Thread 0x7fffc37ee700 (LWP 31169)]
[New Thread 0x7fffc2fed700 (LWP 31170)]
[New Thread 0x7fffc27ec700 (LWP 31173)]
[New Thread 0x7fffc1feb700 (LWP 31174)]
[New Thread 0x7fffc17ea700 (LWP 31175)]

Thread 15 "Cuberite_debug" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe897d700 (LWP 31151)]
0x0000555555ba24ce in std::unique_ptr<cChunkMap, std::default_delete<cChunkMap> >::get (this=0x560) at /usr/include/c++/6/bits/unique_ptr.h:308
308	      { return std::get<0>(_M_t); }
  Id   Target Id         Frame 
  1    Thread 0x7ffff7fe8740 (LWP 31132) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7ffff6d7b700 (LWP 31138) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7ffff657a700 (LWP 31139) "Cuberite_debug" syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  4    Thread 0x7ffff5d79700 (LWP 31140) "Cuberite_debug" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  5    Thread 0x7fffee991700 (LWP 31141) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  6    Thread 0x7fffee190700 (LWP 31142) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  7    Thread 0x7fffed98f700 (LWP 31143) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  8    Thread 0x7fffec989700 (LWP 31144) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  9    Thread 0x7fffec188700 (LWP 31145) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  10   Thread 0x7fffeb987700 (LWP 31146) "Cuberite_debug" 0x00007ffff712b7dd in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  11   Thread 0x7fffeb186700 (LWP 31147) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  12   Thread 0x7fffea985700 (LWP 31148) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  13   Thread 0x7fffe997f700 (LWP 31149) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  14   Thread 0x7fffe917e700 (LWP 31150) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
* 15   Thread 0x7fffe897d700 (LWP 31151) "Cuberite_debug" 0x0000555555ba24ce in std::unique_ptr<cChunkMap, std::default_delete<cChunkMap> >::get (this=0x560) at /usr/include/c++/6/bits/unique_ptr.h:308
  16   Thread 0x7fffd3fff700 (LWP 31154) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  17   Thread 0x7fffd37fe700 (LWP 31155) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  18   Thread 0x7fffd27f8700 (LWP 31156) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  19   Thread 0x7fffd1ff7700 (LWP 31157) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  20   Thread 0x7fffd17f6700 (LWP 31158) "Cuberite_debug" 0x00007ffff712b7dd in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  21   Thread 0x7fffd0ff5700 (LWP 31159) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  22   Thread 0x7fffc7fff700 (LWP 31160) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  23   Thread 0x7fffc6ff9700 (LWP 31163) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  24   Thread 0x7fffc67f8700 (LWP 31164) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  25   Thread 0x7fffc5ff7700 (LWP 31165) "Cuberite_debug" 0x00007ffff712b7dd in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  26   Thread 0x7fffc57f6700 (LWP 31166) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  27   Thread 0x7fffc4ff5700 (LWP 31167) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  28   Thread 0x7fffc3fef700 (LWP 31168) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  29   Thread 0x7fffc37ee700 (LWP 31169) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  30   Thread 0x7fffc2fed700 (LWP 31170) "Cuberite_debug" 0x00007ffff712b7dd in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  31   Thread 0x7fffc27ec700 (LWP 31173) "Cuberite_debug" 0x00007ffff712b7dd in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  32   Thread 0x7fffc1feb700 (LWP 31174) "Cuberite_debug" 0x00007ffff712b7dd in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  33   Thread 0x7fffc17ea700 (LWP 31175) "Cuberite_debug" 0x00007ffff6e5771d in read () at ../sysdeps/unix/syscall-template.S:84

Thread 33 (Thread 0x7fffc17ea700 (LWP 31175)):
#0  0x00007ffff6e5771d in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff6defa00 in _IO_new_file_underflow (fp=0x7ffff71158c0 <_IO_2_1_stdin_>) at fileops.c:600
#2  0x00007ffff6df0b02 in __GI__IO_default_uflow (fp=0x7ffff71158c0 <_IO_2_1_stdin_>) at genops.c:413
#3  0x00007ffff6deb4f0 in _IO_getc (fp=0x7ffff71158c0 <_IO_2_1_stdin_>) at getc.c:38
#4  0x00007ffff793c30d in __gnu_cxx::stdio_sync_filebuf<char, std::char_traits<char> >::underflow() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff78fbb79 in std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000555555c3c6be in cRoot::InputThread (a_Params=...) at /home/kaboomserver/compile/cuberitedebug/src/Root.cpp:89
#7  0x0000555555c4629d in std::_Bind_simple<void (*(std::reference_wrapper<cRoot>))(cRoot&)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x55555d5bb528) at /usr/include/c++/6/functional:1391
#8  0x0000555555c461e9 in std::_Bind_simple<void (*(std::reference_wrapper<cRoot>))(cRoot&)>::operator()() (this=0x55555d5bb528) at /usr/include/c++/6/functional:1380
#9  0x0000555555c461c8 in std::thread::_State_impl<std::_Bind_simple<void (*(std::reference_wrapper<cRoot>))(cRoot&)> >::_M_run() (this=0x55555d5bb520) at /usr/include/c++/6/thread:197
#10 0x00007ffff790ce6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff7122494 in start_thread (arg=0x7fffc17ea700) at pthread_create.c:333
#12 0x00007ffff6e64aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 32 (Thread 0x7fffc1feb700 (LWP 31174)):
#0  0x00007ffff712b7dd in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000555555c52406 in std::this_thread::sleep_for<long, std::ratio<1l, 1000000000l> > (__rtime=...) at /usr/include/c++/6/thread:323
#2  0x0000555555c4d65f in cServer::cTickThread::Execute (this=0x5555566c0fc0) at /home/kaboomserver/compile/cuberitedebug/src/Server.cpp:103
#3  0x0000555555ca6997 in cIsThread::DoExecute (this=0x5555566c0fc0) at /home/kaboomserver/compile/cuberitedebug/src/OSSupport/IsThread.cpp:74
#4  0x0000555555ca7548 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x55555d5ff3c0: (void (cIsThread::*)(cIsThread * const)) 0x555555ca6968 <cIsThread::DoExecute()>, __t=<unknown type in /home/kaboomserver/server/Cuberite_debug, CU 0x739720, DIE 0x742b16>) at /usr/include/c++/6/functional:227
#5  0x0000555555ca74d5 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x55555d5ff3c0: (void (cIsThread::*)(cIsThread * const)) 0x555555ca6968 <cIsThread::DoExecute()>, 
    __args#0=<unknown type in /home/kaboomserver/server/Cuberite_debug, CU 0x739720, DIE 0x742b16>) at /usr/include/c++/6/functional:251
#6  0x0000555555ca7486 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*>(cIsThread*&&) const (this=0x55555d5ff3c0, __args#0=<unknown type in /home/kaboomserver/server/Cuberite_debug, CU 0x739720, DIE 0x742b16>)
    at /usr/include/c++/6/functional:604
#7  0x0000555555ca7451 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x55555d5ff3b8) at /usr/include/c++/6/functional:1391
#8  0x0000555555ca739f in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (this=0x55555d5ff3b8) at /usr/include/c++/6/functional:1380
#9  0x0000555555ca737e in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x55555d5ff3b0) at /usr/include/c++/6/thread:197
#10 0x00007ffff790ce6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff7122494 in start_thread (arg=0x7fffc1feb700) at pthread_create.c:333
#12 0x00007ffff6e64aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 31 (Thread 0x7fffc27ec700 (LWP 31173)):
#0  0x00007ffff712b7dd in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000555555be9025 in std::this_thread::sleep_for<long, std::ratio<1l, 1000l> > (__rtime=...) at /usr/include/c++/6/thread:323
#2  0x0000555555be839b in cDeadlockDetect::Execute (this=0x7fffffffdbe0) at /home/kaboomserver/compile/cuberitedebug/src/DeadlockDetect.cpp:138
#3  0x0000555555ca6997 in cIsThread::DoExecute (this=0x7fffffffdbe0) at /home/kaboomserver/compile/cuberitedebug/src/OSSupport/IsThread.cpp:74
#4  0x0000555555ca7548 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x55555d4a9ae0: (void (cIsThread::*)(cIsThread * const)) 0x555555ca6968 <cIsThread::DoExecute()>, __t=<unknown type in /home/kaboomserver/server/Cuberite_debug, CU 0x739720, DIE 0x742b16>) at /usr/include/c++/6/functional:227
#5  0x0000555555ca74d5 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x55555d4a9ae0: (void (cIsThread::*)(cIsThread * const)) 0x555555ca6968 <cIsThread::DoExecute()>, 
    __args#0=<unknown type in /home/kaboomserver/server/Cuberite_debug, CU 0x739720, DIE 0x742b16>) at /usr/include/c++/6/functional:251
#6  0x0000555555ca7486 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*>(cIsThread*&&) const (this=0x55555d4a9ae0, __args#0=<unknown type in /home/kaboomserver/server/Cuberite_debug, CU 0x739720, DIE 0x742b16>)
    at /usr/include/c++/6/functional:604
#7  0x0000555555ca7451 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x55555d4a9ad8) at /usr/include/c++/6/functional:1391
#8  0x0000555555ca739f in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (this=0x55555d4a9ad8) at /usr/include/c++/6/functional:1380
#9  0x0000555555ca737e in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x55555d4a9ad0) at /usr/include/c++/6/thread:197
#10 0x00007ffff790ce6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff7122494 in start_thread (arg=0x7fffc27ec700) at pthread_create.c:333
#12 0x00007ffff6e64aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 30 (Thread 0x7fffc2fed700 (LWP 31170)):
#0  0x00007ffff712b7dd in nanosleep () at ../sysdeps/unix/syscall-template.S:84
Quit
```

### Steps to reproduce the behavior
1. Download and enable WorldEdit
2. Select an area
3. Run //set beacon

### PR DESCRIPTION
**Pull request by peterbell10**
Fixes #3915

### CODE REVIEW

**Comment by tigerw** [comment]
In what circumstance would a beacon be created without a world?

**Comment by peterbell10** [comment]
`cBlockArea` in general but also `cBlockEntity::Clone` and `cChunkDesc::GetBlockEntity` can all create beacons with the world as `nullptr`.  The same is true for all other block entities as well.

**Comment by tigerw** [comment]
Hm, doesn't seem much in the spirit of object-oriented programming. What is the meaning of a beacon without an associated world? A block entity in an existential crisis? :P

**Comment by madmaxoft** [comment]
Mainly the `cBlockArea`-related stuff - when you copy a portion of the world, or load and save a .schematic file, it needs to represent block entities somehow, and those aren't bound to any world.

**Pull request merged**
