### PR TITLE
Mobs no longer spawn at the top of the nether.

### LINKED ISSUE #3055: Entities spawning on nether above Y 128 (nether's top), and mushrooms too.
It's just that I've seen some ghasts and pigman over there.
There are also mushrooms.

Shouldn't there be no monsters or mushrooms there?

### PR DESCRIPTION
**Pull request by tonibm19**
I don't really know if this is the right place for the check, but it
works.
Fixes #3055

### CODE REVIEW

**Comment by madmaxoft** [comment]
Actually in vanilla mobs do spawn above 127, there are several farm designs based on that:
https://www.youtube.com/watch?v=6W8YgdRnHy8
https://www.youtube.com/watch?v=fPTA6gBoVO8

**Comment by tonibm19** [comment]
what about this wat?

**Comment by madmaxoft** [comment]
I think we should instead focus on mobs not spawning on top of bedrock (anywhere) and that should get us consistent with Vanilla - if someone does get above the bedrock ceiling in the Nether, they can start a farm just like in those videos, simply by covering the bedrock with other blocks.

**Comment by NiLSPACE** [comment]
I believe mobs don't spawn on bedrock everywhere, so it could be replaced with this:
```cpp
if (a_Chunk->GetBlock(a_RelX, a_RelY - 1, a_RelZ) == E_BLOCK_BEDROCK))
{
	return false;   // Make sure mobs do not spawn on bedrock.
}
```

**Comment by madmaxoft** [comment]
Don't forget the Y bounds check

**Comment by tonibm19** [comment]
It seems to work with @NiLSPACE code.
What Y bound check are you talking about? Height is already checked.

**Comment by madmaxoft** [comment]
I don't think the `IsValidHeight()` check was there at first, was it? Or am I blind? :P

**Comment by NiLSPACE** [comment]
No, I changed it afterwards. Forgot to comment that I changed it, sorry.

**Comment by madmaxoft** [comment]
Remove the unrelated horse code modifications, squash into a single commit and we can merge.

**Comment by tonibm19** [comment]
Why remove the horse code? It works.
Anyway, if you want that, i'll remove.

**Comment by madmaxoft** [comment]
Because we don't want unrelated changes in a single PR, let alone a single commit.

**Comment by NiLSPACE** [comment]
Great, can you squash all the commits?

**Comment by tonibm19** [comment]
I'm trying it but... problems.
I've never squashed before D:

**Comment by tonibm19** [comment]
I think I got it

**Comment by SphinxC0re** [comment]
Uhh, a little squash-virgin :laughing: how did it feel?

**Comment by tonibm19** [comment]
weird

**Comment by SphinxC0re** [comment]
Don't worry it will get better over time :smile:

**Comment by madmaxoft** [comment]
Now you can make that horse change, in a separate PR :)

**Pull request merged**
