### PR TITLE
Rebased version of Code for Grass Growth Fix

### PR DESCRIPTION
**Pull request by SamJBarney**
Was having trouble with my git repo. So here's a fresh copy.

### CODE REVIEW

**Comment by SamJBarney** [comment]
Anyone opposed to me merging this?

**Comment by tigerw** [comment]
Looks like Tycho was opposed to \*you* merging it :P

**Comment by SamJBarney** [comment]
Quickdraw Tycho I call him :)
Fastest keyboard this side of the crafting table

**Comment by tigerw** [comment]
+10 Speedy Gozales

**Comment by madmaxoft** [comment]
Too fast to even notice the nonsensical commit message used :P

**Comment by NiLSPACE** [comment]
I doubt this was intended? ;)

**Comment by SamJBarney** [comment]
No. Does it grow back during the day?

**Comment by SamJBarney** [comment]
I think the problem is I'm using cChunk::GetTimeAlteredLight, and so when it turns night, grass under trees die. Hmmm.... but grass doesn't spread at night in Vanilla, right?

**Comment by SamJBarney** [comment]
@NiLSPACE could you post the world that is happening on, along with coords?

**Comment by NiLSPACE** [comment]
I'll do that tomorrow. Would you like to have the executable as well?

**Comment by SamJBarney** [comment]
Just the world would be fine

**Comment by NiLSPACE** [comment]
Here is the download: http://www.mediafire.com/download/t7j6zi8tfn6ja71/Noise3D.zip

At X546, Z-637, but I just noticed it below every tree ;)

**Comment by SamJBarney** [comment]
I think the wiki is lying about how grass dies: http://minecraft.gamepedia.com/Grass_Block#Death
I'm running a test in Vanilla where I've covered a large area of grass with stone, leaving a 1 block air space above it. This drops the light levels to 0, and so far nothing has died except my trust in wikis.

I'll keep running it for a few hours and see what happens.

**Comment by NiLSPACE** [comment]
I don't think grass ever dies, unless you put something directly on top of it.

**Comment by SamJBarney** [comment]
Looks like it. Well, I guess I will fix this mistake of a commit. :(

**Pull request merged**
