### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Wolftein**
thisIsCamelCase ThisIsTitleCase.

### CODE REVIEW

**Comment by madmaxoft** [comment]
Actually, camelcase can be used for both, and is such a common word that everyone knows it, unlike TitleCase. Paired with the actual visual representation, I think the current text is adequate and doesn't require a change.

/me votes NO merge.

**Comment by SphinxC0re** [comment]
I agree. TitleCase is very uncommon

**Comment by madmaxoft** [comment]
I would accept a change to UpperCamelCase, though - this would make things clear and still use the common term.

**Comment by SphinxC0re** [comment]
https://en.wikipedia.org/wiki/CamelCase

**Comment by SphinxC0re** [comment]
https://en.wikipedia.org/wiki/Letter_case#Title_case

**Pull request closed without merging**
