### PR TITLE
Update submodules

### PR DESCRIPTION
**Pull request by mathiascode**

### CODE REVIEW

**Comment by mathiascode** [comment]
Seems to work fine.

**Comment by mathiascode** [comment]
Seems like PRs are built twice by AppVeyor now. Any idea why?

**Comment by madmaxoft** [comment]
PRs were built twice always - once the clean PR code itself, and second the PR merged into master.

**Comment by mathiascode** [comment]
This PR only includes the submodule updates now, since #4440 will take care of the original issue.

**Pull request merged**
