### PR TITLE
Remove nproc to allow BSD compilation

### PR DESCRIPTION
**Pull request by LogicParrot**
Reference: https://forum.cuberite.org/thread-2332.html

### CODE REVIEW

**Comment by madmaxoft** [comment]
CI builds failed, how could you merge!?!

**Comment by SphinxC0re** [comment]
@LogicParrot that's what I told you before...

**Comment by Seadragon91** [comment]
Looking at the change, it replaces `nproc` with a 2. I don't think, that there is a need to run the whole CI for this simple change...

**Comment by LogicParrot** [comment]
CI did not fail. It's because I clicked merge before it completed. This is a 1-line bash change. as @Seadragon91 said.

**Pull request merged**
