### PR TITLE
Added the cUrlParser class, exported to Lua API.

### PR DESCRIPTION
**Pull request by madmaxoft**
This will simplify the web API interaction with `cNetwork`.

### CODE REVIEW

**Comment by worktycho** [comment]
What about protocol relative URLs? For example, the nasty test case: `//::1/foo`

**Comment by madmaxoft** [comment]
Don't wanna do that. We don't need it to be that much universal.
And that URL of yours is invalid, IPv6 should be in brackets: `//[::1]/foo`

**Comment by madmaxoft** [comment]
Uhhh.. I need assistance with the Linux build, it seems the Bindings library would need dependency on the HTTPServer library.

**Comment by SphinxC0re** [comment]
The OS X build is failing:
```sh
Warning: [19:07:34] Cannot load PieceStructures cubeset file Prefabs/PieceStructures/NetherForts.cubeset.gz
Warning: [19:07:34] The PieceStructures generator was asked to generate "NetherForts", but none of the prefabs are valid.
```

**Comment by SafwatHalaby** [comment]
@SphinxC0re That would be issue #2817.

**Comment by SafwatHalaby** [comment]
@SphinxC0re the real failure seems to be a `Segmentation fault`. This is happening randomly on any PR.

**Comment by madmaxoft** [comment]
I don't think the segfault is caused by this PR. Are there any more objections, or can we merge? I've already got two branches dependent on this PR :)

**Pull request merged**
