### PR TITLE
Remove cTracer

### PR DESCRIPTION
**Pull request by madmaxoft**
Removed the obsolete `cTracer` class.

There's a better-documented replacement, `cLineBlockTracer`, that has been in active use for several years, with `cTracer` obsoleted and plugin devs redirected to `cLineBlockTracer`.

There is only one plugin on GitHub actually using `cTracer`, and it's 6 years old:
https://github.com/daniel0916/Lightning

~This PR is sitting on top of #4591, I will rebase it onto master once that gets merged.~ Rebased.

### CODE REVIEW

**Comment by tigerw** [comment]
Was this @FakeTruth's code?

**Comment by FakeTruth** [comment]
> Was this @FakeTruth's code?

Yes

**Comment by tigerw** [comment]
This PR is unholy sacrilege.

**Comment by tigerw** [comment]
Also hello again!

**Comment by madmaxoft** [comment]
Oh wow, the master lives :)

**Comment by FakeTruth** [comment]
Haha it's fine. Hi all!

**Comment by mathiascode** [comment]
Well, hello there! Nice to see some old faces again. :)

**Pull request merged**
