### PR TITLE
Properly deprecate more XYZ parameter'd functions

### LINKED ISSUE #5144: Cuberite crashes in block related functions
Server OS: Windows/Linux
Cuberite Commit id: 8405b8969f205ffae219361dfc03f3b4c680ce73

### Actual behavior
Server crashes

### Steps to reproduce the behavior
Run any of this code from a plugin:
```
cRoot:Get():GetDefaultWorld():GetBlockInfo(1, 355, 1)
cRoot:Get():GetDefaultWorld():SetBlockMeta(1, -100, 1, 1)
cRoot:Get():GetDefaultWorld():GetBlockBlockLight(1, -15, 1)
cRoot:Get():GetDefaultWorld():GetBlockMeta(1, -15, 1)
cRoot:Get():GetDefaultWorld():FastSetBlock(1, -100, 1, 1, 1)
cRoot:Get():GetDefaultWorld():GetBlockSkyLight(1, 355, 1)
cRoot:Get():GetDefaultWorld():SetBlock(1, -100, 1, 1, 1)
```

### PR DESCRIPTION
**Pull request by tigerw**
* Fixes #5144

Thanks @Seadragon91! Does this work?

### CODE REVIEW

**Comment by Seadragon91** [comment]
There are still crashes. Load the attached [world.zip](https://github.com/cuberite/cuberite/files/6095469/world.zip) and call this function:
`cRoot:Get():GetDefaultWorld():DigBlock(1, -100, 1, nil)`

**Comment by Seadragon91** [comment]
Where you able to reproduce it? Do you need a stack trace?

**Comment by tigerw** [comment]
(Many thanks for your help in checking the API!)
Yes, reproduced. The fix is incomplete, I need to go through all of the cWorld exports that take XYZ params and add warnings for Lua code that gives incorrect Y.

**Comment by tigerw** [comment]
Merging as a partial fix, the manual exports will help #5151.

**Comment by mathiascode** [comment]
Each time these deprecations are made, it would be a good idea to also verify that plugins in the Cuberite organization don't use deprecated parameters anymore. A quick search on GitHub is usually enough.

**Pull request merged**
