### PR TITLE
[Testing-Cherrypick] Fixed cChunk::m_Entities corruption upon world travel

### PR DESCRIPTION
**Pull request by LogicParrot**

### CODE REVIEW

**Comment by SphinxC0re** [comment]
Wow. Revert. CI didn't pass

**Comment by SphinxC0re** [comment]
I can't stress this enough: This has been an experiment so you do have to let the CIs pass.

**Comment by LogicParrot** [comment]
The CI was simply interrupted by a premature merge. This piece of code has been run a million times.  It'll run :)

**Comment by LogicParrot** [comment]
Ok, I'll be more strict next time.

**Comment by LogicParrot** [comment]
Ok, I'll be more strict next time. Sorry.

**Pull request merged**
