### PR TITLE
Disable Enderman Spawn (Issue #3108)

### LINKED ISSUE #3108: Disable spawning of Endermen by default
Endermen have no real AI yet, and they are extremely buggy.

### PR DESCRIPTION
**Pull request by benf516**
Temporarily disabled enderman spawning until the glitches can be fixed.

@LogicParrot edit:
Closes #3108

### CODE REVIEW

**Comment by LogicParrot** [comment]
Thank you for the contribution. But I don't think this is the best way to do it.

You have prevented endmen from ever spawning. It makes more sense to disable endermen *by default*; If someone explicitly edits their world.ini and wants endermen, the endermen should spawn. What you should do is edit the default generated `world.ini` instead. See cWorld, line 895 and line 897.

Also note that you did not adhere to the [style guidelines](https://github.com/cuberite/cuberite/blob/master/CONTRIBUTING.md). You must put a space before the first word of a comment. Otherwise the Continous Integration prevents merging your code.
`// Hello world` and not `//hello world`.

**Comment by benf516** [comment]
I apologize, I am not super familiar with the inner workings of MInecraft yet. I assumed this would stop natural spawning but allow spawn eggs to be used to spawn them (which is what I thought you meant by disable by default). I am sorry for my confusion, I will go back and change that now.

**Comment by benf516** [comment]
Is there anything else I should do besides removing Endermen from the strings on lines 895 and 897?

**Comment by LogicParrot** [comment]
>I apologize, I am not super familiar with the inner workings of MInecraft yet. I assumed this would stop natural spawning but allow spawn eggs to be used to spawn them

That is correct, but some people may still want natural spawning for whatever reason. Therefore it's best to just disable natural spawning by default, yet allowing it for those who want it.

>Is there anything else I should do besides removing Endermen from the strings on lines 895 and 897?

No. Your PR was merged into Cuberite. Thank you :)

**Pull request merged**
