### PR TITLE
Revert "Pressure plate fix"

### PR DESCRIPTION
**Pull request by madmaxoft**
Reverts cuberite/cuberite#2574

### CODE REVIEW

**Comment by bearbin** [comment]
Did you mean to merge this?

Sorry for merging the first broken PR.

**Comment by SphinxC0re** [comment]
Oh! Got it! With *reverse-merging* you meat just merging the reversed changes.

**Comment by Schwertspize** [comment]
why? . 1 why not just press the revert button, secondly what is wrong with my pr

**Comment by tigerw** [comment]
No idea about the revert button, it probably was used, but the reversion reason was that the use of `static` variables meant that for more than one pressure plate, since the handler function is reused, the states would have been overwritten by each plate. I believe an appropriate implementation would be to store the pressure plate delay datum in the chunk's redstone simulator data object, so it will be distinct for each plate.

**Comment by Schwertspize** [comment]
no. not for every plate. just if you move to another plate while the first one is activated, those keep activated. but I have talked with @bearbin about what I missed and he said I should make It static.

**Comment by madmaxoft** [comment]
You're thinking single-player. Think 100 players each stepping on various pressure plates. The variable will get overwritten.

**Comment by Schwertspize** [comment]
Oh... but how to solve it? I mean we can't make it non static because that would break the whole code...

**Comment by tigerw** [comment]
I believe an appropriate implementation would be to store the pressure plate delay datum in the chunk's redstone simulator data object, so it will be distinct for each plate.

However, the redstone sim is currently undergoing a remodel. This issue still persists in the new layout, so do you think once that PR is merged (#2542) you could revisit the bug?

**Comment by Schwertspize** [comment]
yeah but where to save it? as a variable in cChunk and a getter and setter? 
I'm new to this project..

**Comment by tigerw** [comment]
So for the current model, there's a structure in cIncrementalRedstoneSimulator.h called cIncrementalRedstoneSimulatorChunkData; you could either add a new map of coordinate to pressure plate delay data, or adapt the existing repeater delay storage to pressure plates.

However, it is recommended to wait until #2542 is merged, since everything changes.

**Comment by Schwertspize** [comment]
yeah.... I think I will wait (but please, merge soon) and save the delay in  a (static)  3 dimensional. map.

**Comment by bearbin** [comment]
Is that not a memory leak - deleted pressure plates are never removed from the map?

**Comment by Schwertspize** [comment]
yeah. thanks for pointing that out, we should create a method to delete them if they exist and run it I'm block destroy.

**Pull request merged**
