### PR TITLE
Fix minecart destruction crash

### PR DESCRIPTION
**Pull request by LogicParrot**
#3335 followup

### CODE REVIEW

**Comment by Seadragon91** [comment]
Okay release mode works fine. Only thing is that I get an assertion under windows in debug build, should we ignore this for now?

**Comment by LogicParrot** [comment]
Down goes the assertion rabbithole...

**Comment by LogicParrot** [comment]
Stacktrace?

**Comment by LogicParrot** [comment]
At least we're not crashing *spontaneously* now. Users have to break it to crash. But we must pursue this. So I'd appreciate a stack trace.

**Comment by Seadragon91** [comment]
```
	Cuberite_debug.exe!issue_debug_notification(const wchar_t * const) Zeile 125	C++
 	Cuberite_debug.exe!__acrt_report_runtime_error(const wchar_t *) Zeile 142	C++
 	Cuberite_debug.exe!abort() Zeile 61	C++
 	Cuberite_debug.exe!common_assert_to_stderr_direct(const wchar_t * const, const wchar_t * const, const unsigned int) Zeile 124	C++
 	Cuberite_debug.exe!common_assert_to_stderr<wchar_t>(const wchar_t * const, const wchar_t * const, const unsigned int) Zeile 142	C++
 	Cuberite_debug.exe!common_assert<wchar_t>(const wchar_t * const, const wchar_t * const, const unsigned int, void * const) Zeile 383	C++
 	Cuberite_debug.exe!_wassert(const wchar_t *, const wchar_t *, unsigned int) Zeile 405	C++
 	Cuberite_debug.exe!cWSSAnvil::LoadMCAFile(const cChunkCoords &) Zeile 267	C++
 	Cuberite_debug.exe!cWSSAnvil::GetChunkData(const cChunkCoords &, std::basic_string<char,std::char_traits<char>,std::allocator<char> > &) Zeile 231	C++
 	Cuberite_debug.exe!cWSSAnvil::LoadChunk(const cChunkCoords &) Zeile 143	C++
 	Cuberite_debug.exe!cWorldStorage::LoadChunk(int, int) Zeile 293	C++
 	Cuberite_debug.exe!cWorldStorage::LoadOneChunk() Zeile 238	C++
 	Cuberite_debug.exe!cWorldStorage::Execute() Zeile 217	C++
 	Cuberite_debug.exe!cIsThread::DoExecute() Zeile 75	C++
 	[Externer Code]	
 	Cuberite_debug.exe!invoke_thread_procedure(unsigned int(*)(void *), void * const) Zeile 92	C++
 	Cuberite_debug.exe!thread_start<unsigned int (__cdecl*)(void * __ptr64)>(void * const) Zeile 115	C++
 	[Externer Code]	
```

I can not really say what happens, I think the chunk is read again from the mca file.

**Comment by LogicParrot** [comment]
This could be a seperate bug, which was simply masked by the other crash which hapened sooner.
Thanks for the trace, I'll investigate.

**Comment by LogicParrot** [comment]
Is there a chance your tests caused some chunk corruption during crashes? Is it reproducable in new worlds?

**Comment by Seadragon91** [comment]
I only placed the minecart, added items and destroyed it. Before server start I deleted all world folders.

**Comment by LogicParrot** [comment]
I see.

>Edit 2: On destroy of the minecart it calls the method cWSSAnvil::LoadMCAFile

I see. I wonder how `destroy()` leads to loading? I cannot trace the code path.

**Comment by Seadragon91** [comment]
Yes, I have no idea why the assert occurs in that method.

**Comment by LogicParrot** [comment]
>A proper fix is that what @madmaxoft said here

I think we need to understand what's going on here first.

**Comment by tigerw** [comment]
(Precisely.)

**Pull request merged**
