### PR TITLE
Add speed limit enforcement for minecarts

### LINKED ISSUE #3000: Limit minecart max speed and powered rails not reducing speed
Minecarts are supposed not to go beyond 8 block per second even when being powered, right now it has no limit(or at least it seems like it) and every powered rail you put increases the minecart speed even more.

I mean is pretty funny like it is i've made a human rocket with a minecart, but the main side effect is that you end inside a wall, the minecart fly over the rail and when taking corners step out of the rails.

That plus powered rails not working also when are are not powered, make the minecart use pretty hard, when not powered the rails are supposed to reduce the speed to almost stop the minecart in one block. 

I mention this two things together because I think may be related to one another.

### PR DESCRIPTION
**Pull request by marvinkopf**
fixes #3000

### CODE REVIEW

**Comment by LogicParrot** [comment]
Can I trust you on this one? If so, rebase and let's merge.

**Comment by LogicParrot** [comment]
Can I trust you tested this one? If so, rebase and let's merge.

**Comment by SphinxC0re** [comment]
Sounds good

**Comment by tigerw** [comment]
I think Mr Kopf may be a little miffed at the timing of this.

**Comment by marvinkopf** [comment]
Ready to merge :-)

**Comment by LogicParrot** [comment]
>I think Mr Kopf may be a little miffed at the timing of this.

Better late than never!

**Comment by rekuen** [comment]
Could this PR be the reason of #3147 ?

**Comment by marvinkopf** [comment]
That's very unlikely.

**Pull request merged**
