### PR TITLE
Fixed tracer usage in Entity physics handling.

### PR DESCRIPTION
**Pull request by madmaxoft**
Fixes entity movement problems introduced in #3704.

### CODE REVIEW

**Comment by madmaxoft** [comment]
The `else` branch was in the wrong nesting level, and the IsOnGround check was at a wrong block face (bottom instead of top). Entities move properly now (though still not the same as in Vanilla).

**Comment by Seadragon91** [comment]
Sorry, but the mobs are really strange, when the encounter a block to climb up. They are then placed on the upper block and looking to the opposite.

**Comment by Seadragon91** [comment]
Tested pickups in water, they are moving but in the opposite direction, for all directions :)

**Comment by Seadragon91** [comment]
Inverting the values in `switch (WaterDir)` in file `Entity.cpp` fixes the moving direction.

**Comment by madmaxoft** [comment]
The water direction code is all wrong and will need replacing anyway.

**Comment by mathiascode** [comment]
I'll do some testing for this PR.

**Comment by madmaxoft** [comment]
I think it's definitely better than current master, so even if it isn't 100% perfect, it should be merged and the rest dealt with later.

**Comment by mathiascode** [comment]
What I noticed so far:
- The "Verification failed: bb.CalcLineIntersection(m_Start, m_End, LineCoeff, Face), file cuberite/src/LineBlockTracer.cpp, line 125" crash still occurs randomly, but frequently
- Mobs have a hard time walking up blocks seem to teleport and glitch into the ground when doing it or standing close to an edge
- Pickups and primed TNT teleport to the ground a few blocks above it instead of falling normally

**Comment by madmaxoft** [comment]
I've got everything almost fixed, only the mob pathfinding still has some problems with jumps. Will publish a fixed version soon.

**Comment by madmaxoft** [comment]
The code as it is now works fine for me. Mobs walk normally and there are no asserts. I'd like more people to test this out, though.

**Comment by Seadragon91** [comment]
Will test it.

**Comment by Seadragon91** [comment]
Okay mobs jumps and walks now fine. Still got the crash at the verify line after 15 mins.

**Comment by mathiascode** [comment]
Everything seems normal again.

**Pull request merged**
