### PR TITLE
Add player permission level

### PR DESCRIPTION
**Pull request by Persson-dev**
I added permission level to players. It's used to indicate to the client which operations it can perform (opening command blocks, switching gamemodes, executing commands).
It should be set with the Core plugin (op command) to be fully functional (for now, it does nothing).
I tested to give me level 4 permission level and i could open command blocks and use the keyboard shortcut F3+N to switch between creative and spectator mode.
I used 1.12.2 version to test this but the specifications have not changed since 1.8 so i just had to modify 1.8 protocol.
https://minecraft.fandom.com/wiki/Permission_level

### CODE REVIEW

**Comment by tigerw** [comment]
I think the `int` should be derived from the existing permission system instead of being its own independent thing.

**Comment by Persson-dev** [comment]
Do you mean assigning the int to a rank or something?

**Comment by bearbin** [comment]
I agree, taking @tigerw's comment to mean - the permission level sent in the protocol should be derived from a HasPermission call, and the numerical value should not be stored or exposed on the player.

**Comment by Persson-dev** [comment]
The goal is actually to expose it to the player. If it's not exposed to the player, the client does not even try to open the gui of a command or change the gamemode using F3+N. It prints "Unable to change gamemode, no permission" instead even if you are op. Or maybe i just misunderstood you.

**Comment by tigerw** [comment]
Thanks, you just uncovered part of the mystery of #3239

There's a [RankManager](https://github.com/cuberite/cuberite/blob/master/src/RankManager.h) handling Bukkit-style fine-grained permissions, see [WorldEdit](https://github.com/cuberite/WorldEdit#biome) for example. Instead of bolting on a separate vanilla-style operator level permission system, we should find a way to translate our string permissions to integer levels.

For example, Vanilla level 1 is "bypass spawn protection". We could map Core's current bypass spawn protection permission [core.spawnprotect.bypass](https://github.com/cuberite/Core/blob/68519b3e0e7fc129f2fae21c7a766c83167c3cc7/core_worlds.lua#L114) to level 1.

To do the mapping, maybe something like

```cpp
EntityAnimation GetPermissionLevel(Player)

if !Player.HasPermission("core.spawnprotect.bypass")
  return EntityAnimation::PlayerSetsOperatorLevelZero

if !Player.HasPermission("comandblock.set") || !Player.HasPermission("core.clear") || ...
    return EntityAnimation::PlayerSetsOperatorLevelOne

// ...
return EntityAnimation::PlayerSetsOperatorLevelTwo
```

**Comment by Persson-dev** [comment]
Is it better now ? Is it enough to send the permission level to the client when SetPlayerRank is called or are they more functions to cover ?

**Comment by bearbin** [comment]
Permissions could also change when they're modified for a rank, rather than just when a player is assigned to one. I'm also not sure if we should set the permission level based on having all the permissions for a level or just having at least one for a level. Since it's a client side thing, we can still deny the action afterwards - so I think we should set the level based on the highest permission-level one of their rank's permissions requires.

**Comment by Persson-dev** [comment]
> I think we should set the level based on the highest permission-level one of their rank's permissions requires.


The permission is now based on the highest permission-level one of the player's rank. 
Also, the permission is now updated whenever a rank or group has changed.
It should be good now.

**Review by bearbin — APPROVED** [review]

**Comment by Persson-dev** [comment]
I don't want to hurry you, but is this PR still good or do you want me to make more changes ?

**Comment by tigerw** [comment]
Sorry about my delay. The plugin docs says plugins are expected to manually invoke LoadRank to update ranks after any changes, and indeed Core does this. It also has the nice effect of batching any effects of a sequence of rank/permission operations. With the current code we could end up with some performance issues if every rank manager operation sends packets to every player in the server. I'm still thinking through if `UpdatePlayersPermissionLevel` is needed and if we will be okay solely relying on the requirement to call LoadRank, and having the network packet sent in that function.

**Comment by Persson-dev** [comment]
I moved the update function to LoadRank and it seems to work fine. However, LoadRank is called once when the player is not yet initialized so i have to skip the UpdatePermissionLevel call to not crash Cuberite with segmentation fault.
I currently check if m_MaxHealth is initialized but maybe there is a cleaner way to do it.

**Comment by tigerw** [comment]
Thank you!

**Pull request merged**
