### PR TITLE
 Lock hopper when powered by redstone

### LINKED ISSUE #3451: Stopping a hopper with redstone doesn't work
Trying to use redstone on a hopper (Which would normally make it stop passing items) does not work.

Taken from #1109

### PR DESCRIPTION
**Pull request by Bond-009**
Fixes #3451

### CODE REVIEW

**Comment by tigerw** [comment]
Changes seem reasonable.

but also it's just occurred to me how much boilerplate we need to write. so much indirection!

**Comment by tigerw** [comment]
Travis is complaining about an undocumented API symbol, you could probably just remove the export for now.

**Comment by mathiascode** [comment]
Any update on this?

**Comment by Bond-009** [comment]
I’m still confused by the lua bindings

**Comment by mathiascode** [comment]
Shouldn't it just be a case of documenting DoWithHopperAt in Server/Plugins/APIDump/Classes/World.lua, like the other DoWith...At methods? Or am I missing something?

**Pull request merged**
