### PR TITLE
Spawn baby mobs

### PR DESCRIPTION
**Pull request by hallucino**
#2326

### CODE REVIEW

**Comment by NiLSPACE** [comment]
You could've saved yourself allot of time by giving the IsBaby parameter a default value of `false` ;) That would make plugins using the function work just fine as well.

**Comment by hallucino** [comment]
like that ? I could remove the changement in others files or it is still more clear like that ?

**Comment by NiLSPACE** [comment]
I suppose it makes sense to keep them :)

**Comment by tigerw** [comment]
Why bother with optional values at all if they're filled in anyway?

**Comment by scribblemaniac** [comment]
@tigerw Optional values are still a good idea so that any external plugins that use that function are not broken and still behave the same.

**Comment by NiLSPACE** [comment]
@scottwillmoore Exactly :)

The documentation has to be updated though.

**Comment by hallucino** [comment]
I must change something ?

**Comment by NiLSPACE** [comment]
In the APIDump plugin the spawnmob function is still documented without the IsBaby parameter, You should add that with brackets around it since it's an optional parameter.

**Comment by tigerw** [comment]
Apparently Lua ignores any extra parameters at the end that aren't filled though.

**Comment by NiLSPACE** [comment]
Yes, that's true simply because it has a default value. Otherwise it would give an error because of too many parameters. This is simply because the cpp code that exports it checks for the amount of parameters.

**Comment by hallucino** [comment]
Not sure about the doc for SpawnMob, if you have a better idea I will use it :+1:

**Comment by hallucino** [comment]
Ok fixed. Sorry

**Comment by SphinxC0re** [comment]
Looks good. Squash and rebase. When it compiles, merge.

**Pull request merged**
