### PR TITLE
Add player statistics to API

### LINKED ISSUE #5166: API access to Player Statistics/Achievements
At this point it seems impossible to access the players statistics through the LUA API. At least it's not documented. This should be an  intermediate issue because all methods are already there in the C++ Code.

### PR DESCRIPTION
**Pull request by nshah25**
Hello! I made the edits suggested in the previous pull request. Please let me know if anything needs to be changed. Thank you!

Fixes #5166

### CODE REVIEW

**Comment by 12xx12** [comment]
We still need to fix the checks:

For checkstyle run the lua file 'CheckBasicStyle.lua' in the 'src' folder.

For the other things I think you'll need to stop exporting the typedefs from the statistics class. By using end end and beginning export markers before and after

**Comment by 12xx12** [comment]
Oh and another thing.

You don't need to close the PRs and open another one. Just commit again and it'll get updated.

And please use more descriptive names in the title and commit messages. See the title I added for this PR

**Comment by nshah25** [comment]
Hello! I tried to run the style check locally, but kept getting an error saying "checkBasicStyle.lua" is not a file or directory. I followed the setup instruction from contributing.md, but have not had any luck getting it to run. Do you have any tips that might help? Thank you so much!

**Comment by 12xx12** [comment]
You might want to check the capitalisation of the file. It’s there in the source folder

**Comment by 12xx12** [comment]
And you can see the logs of the checks and see the checkstyle results there. Although I still advise you to make it run on your machine

**Comment by 12xx12** [comment]
Do you mind me push to this PR - I fixed the compile

**Comment by nshah25** [comment]
Hello! Sorry for the late response, is it at all possible for you to send me the code and then I would push it? The only reason I ask is that this is for a school project and I would get extra credit if my pull request gets accepted. I understand if that's not possible, thank you so much for all your help!

**Comment by 12xx12** [comment]
In the end it's just a few things:
- Mark the closing "}" of the statistics class for export
- fix style

and please remove the other unrelated stuff you changed in the APIDesc.
Maybe update to master before merging

**Comment by bearbin** [comment]
@nshah25 - not sure if you were talking at cross purposes there. @12xx12 was suggesting that they would push a change to fix the build to your repository as part of this PR. The PR would still be open with your code inside, just the build would be fixed and it would then be open to merge in. I think it would be best if 12xx12 did the push, then you can get this accepted and merged. 

That said, I have to comment that your teacher has set a rather unethical project description - in real life the acceptance rate of pull requuests is not that correlated (perhaps even inversely correlated!) to the quality of the contribution. Good PRs can take longer to review and fix issues, or may even get stalled for whatever reason. Giving extra credit for an accepted pull request is basically just giving extra credit randomly, or rewarding people who make silly typo fixes which can be merged in easily.

**Comment by 12xx12** [comment]
I agree this a kind of weird solution to award points but if @nshah25 need to hand in a link which gets checked i don't mind. It's just 2 lines for the compile, 2 lines for checkstyle and then the other stuff on `ApiDesc.lua`

**Comment by nshah25** [comment]
Hello. It would be great if  @12xx12 could push those changes and then I would commit again. I understand the concern around getting extra credit for having an approved pull request, but I'm really grateful you guys are so helpful. Thank you so much and please let me know if there's anything else I can do.

**Comment by nshah25** [comment]
Hello, I do not want to sound pushy at all, and I am really grateful for all the help you guys have given me, but would it be possible to issue a pull request before the end of the day tomorrow? Thank you so much!

**Comment by 12xx12** [comment]
Sorry - my bad. Totaly forgot this :(

**Comment by 12xx12** [comment]
There is a `}` missing in the API doc

**Review by bearbin — APPROVED** [review]

**Comment by 12xx12** [comment]
one sec - i'm removing the unrelated API stuff

**Comment by 12xx12** [comment]
It's alive - finnaly

**Comment by bearbin** [comment]
Looks good then, you can merge :)

**Review by nshah25 — COMMENTED** [review]
Thank you so much for all your help!

**Comment by 12xx12** [comment]
No problem - you're welcome

**Comment by 12xx12** [comment]
Oh - one thing I just noticed. There isn't a way just to ask for a stat value... Maybe we sould add that to the API

**Review by 12xx12 — CHANGES_REQUESTED** [review]
API function for simple value acces is missing 

GetValue(Statistic)

**Comment by tigerw** [comment]
I don't want a proliferation of getters and setters when we add the other stat trackers though, plus the original interface was Add/Get/Set which is even more. I think it's pretty nice to expose the mapping to Lua natively as a table, so you can say
```lua
Statistics.Custom[CustomStatistic.InteractWithFurnace] = 1337

local Value = Statistics.BlocksMined[BlockType.Stone]
```

**Comment by tigerw** [comment]
@12xx12 what say you?

**Comment by 12xx12** [comment]
You're right - I totally forgot about the other types 🤦🏻‍♂️

**Comment by 12xx12** [comment]
I'm just a bit confused why the StatManager isn't called cStatManager

**Comment by tigerw** [comment]
Now is probably a good time to open the style guide change PR

**Pull request merged**
