### PR TITLE
Allow enderman to attack during day

### LINKED ISSUE #2472: enderman doesn't attack you
if you hit or look in the eyes of a Enderman, he won't hit you.

### PR DESCRIPTION
**Pull request by mathiascode**
Seems to be some old behavior. Fixes #2472

### CODE REVIEW

**Comment by bearbin** [comment]
Has the enderman teleporting behaviour (during the day) now been dropped from vanilla? I haven't been playing enough recently to have noticed.

**Comment by Greaper88** [comment]
Would it also be a good idea to investigate their behaviors using the snapshots if possible? That way any changes made will be mostly up to date....

**Comment by mathiascode** [comment]
@bearbin Yes, it's been removed.

**Comment by mathiascode** [comment]
@Greaper88 Feel free to do so if you have time, and report issues if you find any changes (but please, no megalist issues :P)

**Pull request merged**
