### PR TITLE
Fix typo in block break particle coordinate

### LINKED ISSUE #2482: Sheep eat grass from several blocks away
Today I noticed that sheep, when eating, pull the grass out of the dirt 10-20 blocks away from then, seemingly at random.

### LINKED ISSUE #4318: Random explosions of dirt particles above the ground
Client version:   1.12.2
Server OS:        Debian 9
Commit id:        7d512f21913b3ed7dee2a025fdc1dea77a08d83b

### Actual behavior
There are random explosions of dirt particules as if someone was breaking dirt blocks, but in random places above the ground in the overworld. I see it every few seconds.
Edit : it also makes the sound of dirt when it's destroyed

### Steps to reproduce the behavior
I just compiled and started the server and it does that on its own.

### PR DESCRIPTION
**Pull request by mathiascode**
Fixes #2482
Fixes #4318

### CODE REVIEW

**Comment by madmaxoft** [comment]
How does this fix anything, by making the constructor explicit? Or was a different `Vector3` type assumed? Still, how is that different?

**Comment by mathiascode** [comment]
Actually, it should be a Vector3i. Now I'm a bit confused, I reverted my change, and block particles still show up in the correct position...

**Comment by mathiascode** [comment]
When you actually want bugs to appear, they seemingly vanish. How typical.

**Comment by mathiascode** [comment]
Noooo, there's a typo... PosX should be PosZ.

**Comment by TooAngel** [comment]
I like that

**Comment by madmaxoft** [comment]
And that's why we should use `Vector3`s everywhere instead of raw params :)

**Pull request merged**
