### PR TITLE
Revised handling of time increments to ripen for cBlockCropsHandler blocks

### PR DESCRIPTION
**Pull request by dbhicks**
I'm fairly new to Cuberite. After installing and running the server, I initiated a survival map, but noticed immediately that many of my crops weren't producing the expected yield. I think the culprit was that the literal being passed into the template class was too high or the test value in cWorld::GrowRipePlant was too low. In either case, the crops in question would never have their meta value incremented to the point where ConvertToPickups would consider it ripe enough to bear fruit.

I also tried to cut down on some of the repeated literals with some additional constants and a function.

This builds on my system and, after some simple testing, seems to solve the problem.

### CODE REVIEW

**Comment by madmaxoft** [comment]
I'm with @worktycho here, the template parameter should have been kept, and only the changes to `ConvertToPickups` should be in this PR.

**Comment by madmaxoft** [comment]
Oh my, I think we may have mislead you. I've revised the crops code and it seems to me that the problem is that the code assumes `RipeMeta` is the value of the metadata for the ripe crops block, but the constructors (in BlockHandler.cpp) actually fill it with a value one larger (4 instead of 3, 8 instead of 7). So it seems to me that the most proper fix would be to actually change the values in BlockHandler.cpp, what do you think?

**Comment by dbhicks** [comment]
I would probably leave it the way it is now for readability/clarity, since the constructor takes a 1-indexed number and I think people in the future will be less likely to make similar errors to the one that was made here if it remains to be 1-indexed.

**Comment by madmaxoft** [comment]
I see a naming problem. The value is called `Meta`, but it currently is not a Meta value, it's rather a NumMetaStates value. This makes a nice WTF.

**Comment by dbhicks** [comment]
Coming into this project blind, I can confirm it was a puzzling choice.

**Comment by madmaxoft** [comment]
Exactly the reason why I think it should be changed :)

**Comment by dbhicks** [comment]
Perhaps I'm confused. Are you suggesting that this PR should be expanded to involve itself with revising variable naming conventions? That, to me, seems unrelated to the intent of my PR, which is to make crops yield fruit when ripe. It may also be a task better suited for someone with greater project-wide perspective than I have. I'd be happy to open an issue to discuss renaming the variable. I think it would be best to take care of that in another branch.

**Comment by worktycho** [comment]
You're right, I'm going to merge this now pending CI success on the updated branch. Refactors tend to have a tendency to grow so lets get this merged to fix the bug for now.

**Comment by madmaxoft** [comment]
Nah, I just wanted you to take the other approach - instead of passing in `<4>` and `<8>` when the objects are constructed, pass in `<3>` and `<7>`, so that the `RipeMeta` value is a real meta.

I guess I'll change it now, since the PR is already merged.

**Pull request merged**
