### PR TITLE
Updated old forum links

### PR DESCRIPTION
**Pull request by mathias-github**

### CODE REVIEW

**Comment by SphinxC0re** [comment]
Looks good

**Comment by LogicParrot** [comment]
Someone should prevent new posts in the old forum asap.

**Comment by NiLSPACE** [comment]
I've locked the old forum.

**Comment by SphinxC0re** [comment]
nice

**Comment by LogicParrot** [comment]
@NiLSPACE Great :)
As NiLSPACE mentioned in the forum, URL-preserving redirects would be great.

**Pull request merged**
