### PR TITLE
SelfTests are registered and executed after logging framework init.

### LINKED ISSUE #2228: Change self-tests to execute after logging has been initialized
Currently the self-tests are executed in the constructors of global objects. This has the unfortunate side-effect that the logging framework is not initialized with console output at that time.

I propose we change the way self-tests are done. The global constructor should register the self-test for later execution, and then once logging is initialized, the queued tests should get executed.

### PR DESCRIPTION
**Pull request by madmaxoft**
Fixes #2228.

### CODE REVIEW

**Comment by tigerw** [comment]
Would it be possible to initialise the logging framework just for testing?

**Comment by madmaxoft** [comment]
Not really, because one needs `cRoot::m_IsService` in order to initialize the logging, so you need to read the cmdline params first, and it gets hairier and hairier. This way is much simpler.

**Comment by madmaxoft** [comment]
I wonder why AppVeyor is not testing the PR

**Comment by worktycho** [comment]
I think that the self tests frame work should be outside cRoot, but really these tests should be in separate executables.

**Comment by madmaxoft** [comment]
I'm moving it out of Root.h, otherwise it gets included in ProtoProxy (hence the CI failures).
Moving them out of the executable is out of scope for now.

**Comment by madmaxoft** [comment]
I think this is now ready for a merge. Anyone opposed?

**Comment by SphinxC0re** [comment]
Looks good to me

**Pull request merged**
