### PR TITLE
Note block Left Click Fix

### LINKED ISSUE #4839: No noteblock playback on left click
Client version: any
Server OS: any
Cuberite Commit id: d2de029c024309b0ac2429373cc8ef2e56f880e0

### Expected behavior
When left clicking a note block in survival you play back the sound without changing the pitch

### Actual behavior
no sound playback or a animation

### Steps to reproduce the behavior
- place noteblock
- go into survival
- left click on it

### PR DESCRIPTION
**Pull request by ProjectBM**
* Player can now left click on note block and play back the sound with an animation.

Fixes #4839

### CODE REVIEW

**Comment by 12xx12** [comment]
Can you verify that the note block doesn't play if the client is in creative mode? Vanilla doesn't

**Comment by ProjectBM** [comment]
> Can you verify that the note block doesn't play if the client is in creative mode or adventure? Vanilla doesn't

Tested in creative mode:
* Left clicking while holding any sword item does not play back sound.
* Left clicking while holding non-sword items break the block.

Tested in adventure mode:
* Left clicking does not play back sound regardless of what items are being held.

(Side Note: Not too sure why clang-tidy failed last time. The generated output doesn't seem related to the changes I made)

**Comment by 12xx12** [comment]
So it matches vanilla - nice.

Yeah the include stuff is a bit confusing. I use MVSC and there you need few imports to compile but the clang fails

**Comment by ProjectBM** [comment]
Yup it was an import issue. CLion sent me on a wild goose chase :( 

Anyways clang-tidy passes now

**Review by 12xx12 — APPROVED** [review]

**Comment by ProjectBM** [comment]
Not too sure why clang-6.0 debug failed. Should I be concerned about the output below?

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

**Comment by 12xx12** [comment]
Ah sh*t here we go again.. we don't know... this happens every few PRs.

- Close this PR,
- create a new commit on branch
- open new PR

**Pull request closed without merging**
