### PR TITLE
Baby chickens don't lay eggs

### PR DESCRIPTION
**Pull request by Gargaj**

### CODE REVIEW

**Comment by madmaxoft** [comment]
How about early bail-out:
```cpp
if (IsBaby())
{
  return;
}
```

**Comment by Gargaj** [comment]
Does it matter?

**Comment by madmaxoft** [comment]
It improves readability by reducing the nesting level

**Comment by Gargaj** [comment]
I would argue ```if (this isn't true) { do something; }``` is easily more readable than ```if (this is true) nothing to do here;```

**Comment by NiLSPACE** [comment]
It's more like `if (this is true) nothing left do do for us. We can leave`

**Comment by madmaxoft** [comment]
Compare:
```cpp
if (something)
{
  ...
  if (somethingelse)
  {
    ...
    if (yetanother)
    {
      ...
    }
  }
}
```
with
```cpp
if (!something)
{
  // Nothing needed
  return;
}

...
if (!somethingelse)
{
  // We can't do this now
  return;
}

...
if (!yetanother)
{
  // Access denied
  return;
}
...
```

**Pull request closed without merging**
