### PR TITLE
Delet SpawnObject params

### LINKED ISSUE #4679: Move angle processing into cProtocol::SendSpawnObject
`cProtocol::SendSpawnObject` currently accepts yaw and pitch parameters as a `Byte`, which causes the protocol-related calculations to leak into the client classes, such as the `cArrowEntity`. The function should accept yaw and pitch in degrees, like stored in the `cEntity`, and do its conversions internally.

### PR DESCRIPTION
**Pull request by tigerw**
* Fix #4679

awkward...

### CODE REVIEW

**Comment by tigerw** [comment]
You thought it was still being used...

BUT NO!
----

It was ***ME***, *a 1.6 leftover*, ***ALL ALONG!***

**Comment by madmaxoft** [comment]
Wait, WHUT? The params were not even used?!?

**Comment by madmaxoft** [comment]
I have an itsy bitsy teenie weenie suggestion: How about unifying all the spawning into `cProtocol::SendSpawnEntity(const cEntity &)` that will figure out which of the bajillion spawning packets to send based on the entity, and take all its data from that entity?

I mean, with `a_ClientHandle.SendSpawnObject(*this, 51, 0);` for `cEnderCrystal`, how long will it be `51` and when will we need a per-protocol translation layer?

The protocol classes should not be modelled after the packets they send / receive, but on the high-level actions they provide, 's'all I'm saying.

**Comment by Pokechu22** [comment]
Object IDs are one of those things that were hardcoded on Mojang's side (and hence are really jank).  They will not change, and there is no point in investing time in improving them specifically.

In 1.14 (specifically 19w05a), Spawn Object was changed to use normal entity IDs (which match those in Spawn Mob), but that can be handled by just using those same IDs.  Entity IDs do shift, but are also exposed by a data generator (if I recall correctly) and on burger.

**Comment by madmaxoft** [comment]
If I remember correctly, some entities already changed their spawn packets; the object data can also change meaning between protocol versions. My point is, the Entity classes should not be the ones taking care of that, the Protocol classes should.

**Comment by tigerw** [comment]
In the current wiki.vg/Protocol I don't see any Spawn Object at all, only Spawn Entity. Interestingly https://wiki.vg/Entity_metadata still references Spawn Object.

**Comment by Pokechu22** [comment]
That confused me as well; someone renamed them to Spawn Entity (and Spawn Living Entity).

**Comment by tigerw** [comment]
How do you know so much about the protocol? You don't happen to work at Mojang, do you? :)

**Comment by Pokechu22** [comment]
I do a lot of work on writing the documentation (mainly research for snapshots, based on [burger](https://github.com/mcdevs/Burger) (which I maintain); that in particular gives me a fair bit of familiarity with when numeric IDs change).  I'm also a volunteer moderator over on Mojang's bug tracker, but I'm not an employee; this has given me some level of familiarity with different bugs and when they were fixed (which helps identify specific changes).

**Comment by tigerw** [comment]
I think before we implement SendSpawnEntity and to avoid duplicating the logic twice, we should get the 1.9 protocol to inherit from 1.8. diff shows ~90% the same, the rest seems like it can be overridden as normal.

**Pull request merged**
