### PR TITLE
Clean up items.ini

### PR DESCRIPTION
**Pull request by bearbin**
underscores in the names of items are now ignored, and any items with that name are stripped from the file.

This pull request depends on https://github.com/cuberite/cuberite/pull/3199

### CODE REVIEW

**Comment by mathias-github** [comment]
I added the underscores, because vanilla Minecraft uses them. Otherwise, give commands taken from the internet would be broken.

**Comment by madmaxoft** [comment]
I'm not sure this is the right approach - what if future MC actually requires the use of underscored names for some reason? Such as advanced NBT tags for composite items, or whatever.

**Comment by bearbin** [comment]
Would you rather items.ini contained only underscored names, and the server just did a underscore-insensitive compare to those?

**Comment by madmaxoft** [comment]
I'm not sure. Is there a possibility that two underscored names can compare to the same underscore-less one?
Also, I think commands such as `/give o_akdo_or` should fail.

**Comment by bearbin** [comment]
So in your eyes the correct solution would be to just edit items.ini so it contained both underscored and non-underscored names?

Does anybody else have an opinion on this matter?

**Comment by madmaxoft** [comment]
Yes, I think having both is the way to go for now.

**Comment by tigerw** [comment]
That's just inviting de-synchronisation. Recommended solution is to remove non-underscored names.

**Comment by SphinxC0re** [comment]
Yeah, just let the server load all items at server start and for every item:
 - save it as it is 
 - remove the underscores and save it again

**Comment by madmaxoft** [comment]
That would be a workable solution.

**Comment by SphinxC0re** [comment]
Also, are the names check case-sensitive? Because I think this would be bad UX

**Comment by madmaxoft** [comment]
@bearbin Any chance of finalizing this, based on @SphinxC0re's suggestions? (https://github.com/cuberite/cuberite/pull/3202#issuecomment-221207962)

**Comment by SphinxC0re** [comment]
About that: By "saving" I didn't mean to actually save the results to disk. Just replace it with "caching" 😉

**Pull request closed without merging**
