### PR TITLE
made survival the default gamemode

### LINKED ISSUE #2600: Make 'Survival' the default gamemode
We can keep 'Creative' as gamemode for debugging

### PR DESCRIPTION
**Pull request by Alcamech**
Closes #2600

### CODE REVIEW

**Comment by sphinxc0re** [comment]
Thank you soooooo much for this change ❤️

**Comment by LogicParrot** [comment]
I don't think this is a good idea. Survival is less complete than creative. At the very least, mobs and mob spawning should be fixed first.

**Comment by Alcamech** [comment]
Under the issue you commented that mobs no longer spawned too close to players. I thought that was the issue preventing this from being done. Mind filling me in on what else is wrong with the mob spawning ?

**Comment by sphinxc0re** [comment]
The default gamemode should be survival so you can start playing directly after starting the server. Having sane defaults is always a good idea. Having creative mode in debug builds by default would be a good idea though. It's easier to test that way.

**Comment by LogicParrot** [comment]
> Mind filling me in on what else is wrong with the mob spawning ?

Mobs no longer spawn too close to players, but tuning is needed for the number of mobs that spawn, and the mixture of types that spawn, and most mobtypes need to be implemented. Also, #2858 claims mobs do not spawn in caves, though I haven't tested that yet.

Also, pushing is broken, so it is currently disabled. (Zombie hits or arrows do not push the player). There are probably several more issues that I missed.

> I thought that was the issue preventing this from being done.

Spawning near players was a major issue and there was no way I'd agree to having survival as the default prior to fixing that. The remaining issues are less severe and I'll leave the choice to the other devs.

**Comment by sphinxc0re** [comment]
The change is good anyway. So I'd say merge. People who want to play on the server want to play on survival regardless of feature completeness as stated here #2600

**Comment by sphinxc0re** [comment]
@madmaxoft any thoughts? @Alcamech please rebase and squash the commits onto the current master

**Comment by madmaxoft** [comment]
Don't care; no need to squash / rebase.

**Pull request merged**
