### PR TITLE
Fixed a few crafting recipes

### PR DESCRIPTION
**Pull request by mathias-github**
- Sandstone and Red Sandstone recipes now have the correct amounts and blocks
- Flint and Steel fix (#2722)
- Lead amount fix (#2722)
- FireCharge amount fix
- Switched iron ingots and gold ingots in weighted pressure plate recipe, since they were wrong

### CODE REVIEW

**Comment by SafwatHalaby** [comment]
Merge-blocking is an anti-feature. It's just slowing things downs. How about we remove this Github check and manually ask for rebases when the PR is reasonably old and nontrivial?

**Comment by worktycho** [comment]
The merge blocking is not about rebases, but CI. Which is should complete and picks up things humans miss.

**Comment by SafwatHalaby** [comment]
I don't know what `owners` can do, but I can't merge this PR even though all CIs passed unlessed the OP rebases.

**Comment by worktycho** [comment]
Theres nothing in the settings about that.

**Comment by mathias-github** [comment]
In a few minutes.

**Comment by SafwatHalaby** [comment]
Could you please rebase that to avoid polluting master with "Merge X into..."?

**Comment by mathias-github** [comment]
This didn't go as planned.

**Comment by SafwatHalaby** [comment]
We'll just use my PR.

**Comment by SafwatHalaby** [comment]
For future reference:
Do not click the github `Merge master into this branch` button. Rebase instead:
fetch or pull the latest master, then:
 ```
git checkout myBranch
git rebase -i master
git push myRepo myBranch --force
```

**Pull request closed without merging**
