### PR TITLE
Minor update

### LINKED ISSUE #2809: Add BACKERS file
As promised on the Bountysource page ( https://salt.bountysource.com/teams/cuberite ) we need to add the people who contributed to the BACKERS file.

### PR DESCRIPTION
**Pull request by mathias-github**
- Added a BACKERS file (fixes #2809)
- Changed description and year in LICENSE file
- Removed unused WebAdmin files

### CODE REVIEW

**Comment by SphinxC0re** [comment]
Why did you remove all those webadmin files?

**Comment by mathias-github** [comment]
I though those files were not used anywhere. Am I mistaken?

**Comment by SphinxC0re** [comment]
I don't know whether they are used anywhere. But since you are probably going to overhaul the webadmin experience anyway, I think it should be alright.

**Comment by NiLSPACE** [comment]
As long as the webadmin will look the same. We've had allot of webadmin overhauls already, but this one is by far the best.

**Comment by SphinxC0re** [comment]
You mean the last one?

**Comment by LogicParrot** [comment]
Merge?

**Pull request merged**
