### PR TITLE
Added clang 5.0 flag to ignore error in sqlite

### PR DESCRIPTION
**Pull request by Seadragon91**

### CODE REVIEW

**Comment by madmaxoft** [comment]
Is there any chance to use this only for the libraries, but keep the warning for our code?

**Comment by Seadragon91** [comment]
What did you do there @worktycho?

**Comment by Seadragon91** [comment]
@madmaxoft Whats about the file CMakeLists.txt](https://github.com/cuberite/sqlite/blob/master/CMakeLists.txt)? Also there are two more flags that could be moved into this file.

**Comment by worktycho** [comment]
Clicked the update branch button with a view to merging the PR.

**Comment by worktycho** [comment]
Didn't see xofts comment.

**Comment by Seadragon91** [comment]
Okay :)

**Pull request closed without merging**
