### PR TITLE
Added sponge.

### PR DESCRIPTION
**Pull request by Howaner**
Implements #1411

### CODE REVIEW

**Comment by Howaner** [comment]
Is this merge-able?

**Comment by madmaxoft** [comment]
This is somewhat unfortunate - the sponge as implemented here doesn't make the water-absorption count as the player-placement. This means that plugins such as grief prevention couldn't prevent protected water being absorbed by unprotected sponges. Is there any way this could be worked around?

**Comment by tigerw** [comment]
Would you suggest implementing a new hook for sponges or reusing the current player-break-block hook? The first one is more maintainable.

**Comment by madmaxoft** [comment]
It should reuse the player-place infrastructure, placing air blocks. This will ensure that the same mechanism is used everywhere; if we decide to change the `OnPlayerPlacingBlock` hook (which I'm considering, changing it to report all the blocks at once), it will get changed automatically, too.

**Comment by tigerw** [comment]
If only the hook could be renamed without regard for thinking about plugins.

**Comment by SphinxC0re** [comment]
Any update on this one?

**Comment by Howaner** [comment]
So, what should I do.
Should I create a new BLOCK_SPONGE_HOOK hook?

**Comment by madmaxoft** [comment]
Instead of changing the blocks to air in the `cWorld`, it should call the `cPlayer::PlaceBlocks()` instead. That's all.

**Comment by SphinxC0re** [comment]
Does this implement the *new* or the *old* sponge mechanics?
[This](https://www.youtube.com/watch?v=VfOuiPOIJA0) will only work with the new mechanics

**Comment by SphinxC0re** [comment]
What's up with this PR??

**Comment by SphinxC0re** [comment]
Closing due to no response

**Pull request closed without merging**
