### PR TITLE
Stop Tamed Wolf from following player when he is flying

### PR DESCRIPTION
**Pull request by iam10K**
Check to make sure player is not flying before allowing wolf to move to player. Fixes https://github.com/cuberite/cuberite/issues/3013

### CODE REVIEW

**Comment by LogicParrot** [comment]
Looks good. Could you rebase and squash your commits before we merge?

**Comment by iam10K** [comment]
Squashed and rebased.

**Comment by LogicParrot** [comment]
Sorry, you'd need to do that again, because the master branch has just been updated. Make sure you rebase against the latest master.

**Comment by NiLSPACE** [comment]
I think we need a page that describes how to rebase on the latest master and similar git actions that is required for a PR. I'd have no idea what to do when asked to rebase against the latest master. In fact, it holds me back when I want to do some work on the server code. *Oh, I want to implement this feature. But crap, then I have to do all those actions again :/*

Just a simple step-by-step manual should do it.
```
Squashing commits:
If you want to squash commits you can use this command:
  git rebase -i HEAD~{Num commits to squash}
In front of the commit that you don't want to keep you replace 'pick' with 'fixup'. Keep only one commit with 'pick'. After that press 'escape' and then literely write ':write' and then ':quit'.
Finally you'll want to push your changes using 'git push --force'

Rebasing against current master:
...
```

**Pull request merged**
