### PR TITLE
Should Fix sign flipping.

### LINKED ISSUE #1118: Sign block meta-data mirroring is wrong
Mirroring the signs using the `//mirror xy` or `//mirror yz` WorldEdit commands is buggy, because the sign blockhandler's meta mirroring is wrong. Fix the `cBlockSignHandler::MetaMirrorXY()` and `cBlockSignHandler::MetaMirrorYZ()` functions.

### PR DESCRIPTION
**Pull request by bearbin**
Fixes #1118

### CODE REVIEW

**Comment by madmaxoft** [comment]
Have you tested this?

**Comment by bearbin** [comment]
No. I will now.

**Comment by bearbin** [comment]
I've now tested it, but mirroring doesn't seem to be working on anything now :(

**Comment by bearbin** [comment]
I tested this, and the flipping didn't work using WorldEdit - but when I tested vines they didn't work either, so I think it may just be the worldedit flip function that's broken.

Otherwise, this should work, as it matches up with the wiki information.

**Comment by madmaxoft** [comment]
I have a feeling vines don't work either. Try a wall-mounted torch, that should work 100%

**Comment by bearbin** [comment]
Nope, torch didn't work.

**Comment by tigerw** [comment]
nothing works

**Comment by bearbin** [comment]
I'm pretty sure that this code is correct, and since the mirroring using worldedit is not working at all and there's no way to test, should I just merge this?

**Comment by NiLSPACE** [comment]
It's not working in WorldEdit? What? Why isn't that reported? How did you try. I believe you have to copy it first, mirror it, and then paste it again.

**Comment by bearbin** [comment]
I selected an area and did `//mirror`. The blocks in the area switched around, but they did not rotate.

**Comment by SphinxC0re** [comment]
That's another problem. May someone remove this coveralls job?

**Pull request merged**
