### PR TITLE
Double chest window fix

### LINKED ISSUE #2934: Double chests can cause SEGFAULTS
If half of a double chest that someone is accessing is broke and it is the half that they clicked on the chest will close as it should. If the other half of the chest starting on the half that they did not click on will crash the server once they do anything (including closing the chest or moving items in or out).

`[19:15:04]   D:    | Cuberite has encountered an error and needs to close
[19:15:04] Details | SIGSEGV: Segmentation fault
[19:15:04] Cuberite local build build id: Unknown
[19:15:04] from commit id: approx: d9e4eaa2a6d9764d7d9f5eee66611397e95cc20d built at: approx: 2016-01-29 19:42:29 +0200
./Cuberite(_Z15PrintStackTracev+0x14)[0x623d34]
./Cuberite[0x6110a3]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x6a83ad2e2d40]
./Cuberite(_ZN12cChestWindow14ClosedByPlayerER7cPlayerb+0x52)[0x858962]
./Cuberite(_ZN7cPlayer15CloseWindowIfIDEcb+0x2e)[0x81f6ae]
./Cuberite(_ZN12cProtocol18023HandlePacketWindowCloseER11cByteBuffer+0x2d)[0x72447d]
./Cuberite(_ZN12cProtocol18012HandlePacketER11cByteBufferj+0x216)[0x728166]
./Cuberite(_ZN12cProtocol18015AddReceivedDataEPKcm+0x111)[0x7283e1]
./Cuberite(_ZN12cProtocol18012DataReceivedEPKcm+0x80)[0x728d20]
./Cuberite(_ZN19cProtocolRecognizer12DataReceivedEPKcm+0x21)[0x72d3d1]
./Cuberite(_ZN13cClientHandle4TickEf+0x61)[0x584d41]
./Cuberite(_ZN6cWorld11TickClientsEf+0x1bf)[0x604c8f]
./Cuberite(_ZN6cWorld4TickENSt6chrono8durationIlSt5ratioILl1ELl1000EEEES4_+0x1f9)[0x60a409]
./Cuberite(_ZN6cWorld11cTickThread7ExecuteEv+0x71)[0x60a6d1]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb1a40)[0x6a83adc3ea40]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8182)[0x6a83ade99182]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x6a83ad3a647d]
[19:15:04]   D:    | Cuberite has encountered an error and needs to close
[19:15:04] Details | SIGABRT: Server self-terminated due to an internal fault
[19:15:04] Cuberite local build build id: Unknown
[19:15:04] from commit id: approx: d9e4eaa2a6d9764d7d9f5eee66611397e95cc20d built at: approx: 2016-01-29 19:42:29 +0200
./Cuberite(_Z15PrintStackTracev+0x14)[0x623d34]
./Cuberite[0x6110a3]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x6a83ad2e2d40]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x39)[0x6a83ad2e2cc9]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x6a83ad2e60d8]
./Cuberite[0x6110a8]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x6a83ad2e2d40]
./Cuberite(_ZN12cChestWindow14ClosedByPlayerER7cPlayerb+0x52)[0x858962]
./Cuberite(_ZN7cPlayer15CloseWindowIfIDEcb+0x2e)[0x81f6ae]
./Cuberite(_ZN12cProtocol18023HandlePacketWindowCloseER11cByteBuffer+0x2d)[0x72447d]
./Cuberite(_ZN12cProtocol18012HandlePacketER11cByteBufferj+0x216)[0x728166]
./Cuberite(_ZN12cProtocol18015AddReceivedDataEPKcm+0x111)[0x7283e1]
./Cuberite(_ZN12cProtocol18012DataReceivedEPKcm+0x80)[0x728d20]
./Cuberite(_ZN19cProtocolRecognizer12DataReceivedEPKcm+0x21)[0x72d3d1]
./Cuberite(_ZN13cClientHandle4TickEf+0x61)[0x584d41]
./Cuberite(_ZN6cWorld11TickClientsEf+0x1bf)[0x604c8f]
./Cuberite(_ZN6cWorld4TickENSt6chrono8durationIlSt5ratioILl1ELl1000EEEES4_+0x1f9)[0x60a409]
./Cuberite(_ZN6cWorld11cTickThread7ExecuteEv+0x71)[0x60a6d1]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb1a40)[0x6a83adc3ea40]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8182)[0x6a83ade99182]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x6a83ad3a647d]
./run.sh: line 6: 30752 Aborted                 (core dumped) ./Cuberite`

### PR DESCRIPTION
**Pull request by peterbell10**
Fixes #2934

### CODE REVIEW

**Comment by madmaxoft** [comment]
This has a potential problem with double-chest being placed across a chunk boundary. If one of the chests unloads, this code still has a dangling pointer to it.

**Comment by peterbell10** [comment]
Are unloaded entities not destroyed?

**Comment by madmaxoft** [comment]
Right, the threads get synchronized on this, so there shouldn't be an issue with this. Sorry, my bad.

**Comment by peterbell10** [comment]
I really don't understand these MSVC build errors: 
```
'm_World' : undeclared identifier
'm_PosX' : undeclared identifier
'm_PosY' : undeclared identifier
'm_PosZ' : undeclared identifier
```
Even though it compiles fine with VS2015, clang and gcc.

**Comment by peterbell10** [comment]
Apparently this is a actually [known bug in MSVC](https://connect.microsoft.com/VisualStudio/feedback/details/811369/local-struct-class-with-in-class-initialization-of-member-causes-compilation-failure).  I guess local classes are just a bit buggy.

**Pull request merged**
