### PR TITLE
The physics of motion of Pickups in water

### PR DESCRIPTION
**Pull request by bionext03**
I want to propose my own algorithm for the movement of Pickups in the stream of water.

### CODE REVIEW

**Comment by bearbin** [comment]
I'm going to give this a proper review at some point soon, but first you should make sure that all the code conventions are followed: https://github.com/cuberite/cuberite/blob/master/CONTRIBUTING.md
The CheckBasicStyle.lua script can help with this.

Also, I noticed a few places where there is code commented out. Comments are to document the code not act as a backup, you should remove it or put it inside a compile/runtime flag.

**Comment by bionext03** [comment]
Well, I'll finalize the code in accordance with the formatting requirements. And also try to exclude all the errors in determining the direction of motion, which are present.

**Comment by bionext03** [comment]
I finished work on the algorithm for calculating the direction of water movement. You can see my code and make my decision.

**Comment by bionext03** [comment]
Sorry during the correction of syntax errors allowed a logical error.

**Comment by bearbin** [comment]
You need to roll back all of those permissions changes, as they make the PR unreviewable as it is.

**Pull request closed without merging**
