### PR TITLE
imprementing plugin message to send server brand

### PR DESCRIPTION
**Pull request by 12xx12**
I think abbout working on the other message types - don't merge right now - this is just for review purposes

### CODE REVIEW

**Comment by Titaniumtown** [comment]
I'll test this later! Thanks for addressing my issue!

**Comment by Titaniumtown** [comment]
Just a thought, maybe it could be implemented into the API to be able to change the server "brand".

**Comment by 12xx12** [comment]
@Titaniumtown right now the "brand" is just a string hardcoded into the code - it shouldn't be that hard but i don't see the sense in that because brand just describes the kind of te server. Although I am not the person to decide this.

**Comment by Titaniumtown** [comment]
Maybe by default it can be "Cuberite" but it would just be neat to have the functionality.

**Comment by Titaniumtown** [comment]
Btw it's compiling rn. I'll do some testing.

**Comment by Titaniumtown** [comment]
It worked :)

**Comment by bearbin** [comment]
Is this still WIP or ready for review/merge?

**Comment by 12xx12** [comment]
WIP. Gotta add a parameter to the transmission which was not there before in die older versions. 

Gonna do that later

**Comment by 12xx12** [comment]
@bearbin ready for review (when checks are done)

**Pull request merged**
