### PR TITLE
Fixes Floating Dark Oak Tree Bug

### LINKED ISSUE #3455: Terrain generator made a 2x2 three with no dirt at half of the bottom
Client version:   1.9.4
Server OS:        Linux (debian jessie)
Commit id:        ded59e9519c429c511866609d0e5e909f8e10aad

screen shot 2016-11-22 at 13 21 08

### PR DESCRIPTION
**Pull request by Balajanovski**
Fixes Floating Dark Oak Tree Bug

Closes #3455

### CODE REVIEW

**Comment by NiLSPACE** [comment]
Great, could you also add it for large jungles trees?

**Comment by Balajanovski** [comment]
@NiLSPACE Sure

**Comment by madmaxoft** [comment]
You may want to pair your commit email with your GitHub account, so that GitHub shows your authorship for the commits.

**Comment by Pokechu22** [comment]
> You may want to pair your commit email with your GitHub account, so that GitHub shows your authorship for the commits.

More info about that [here](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by NiLSPACE** [comment]
Do you want to pair the commits with your GitHub account or do you want me to merge the PR as it is?

**Comment by madmaxoft** [comment]
@Balajanovski You can either add the email address you used for the commits to your GitHub account, or you can use a different email address for the commits. In the latter case, you will need to amend the commits; the GitHub help page Pokechu22 linked says Github discourages changes to the git history (including email addresses), but we here at Cuberite encourage such changes - we consider the PR owned by its author and so not "shared" in the broad sense of the word. In other words, for PRs we encourage amends, rebases and squashes.

**Pull request merged**
