### PR TITLE
Lua binding for cIniFile.noID

### LINKED ISSUE #3324: No Lua binding cIniFile.noID
Inherited noID enum of cIniFile class isn't exported to Lua's bindings.

### PR DESCRIPTION
**Pull request by ElNounch**
Fix #3324

### CODE REVIEW

**Comment by sphinxc0re** [comment]
@cuberite/core-team someone seems to be quite busy here 😉

**Comment by madmaxoft** [comment]
Does that really need manual binding, can't it be exported automatically?

**Comment by madmaxoft** [comment]
Now we have a choice - this PR, or #3329? :)

**Comment by ElNounch** [comment]
@madmaxoft : both are ugly :worried:, proper fix of the dependency would be neat. :grimacing:
Don't you think so ? :grinning:

**Comment by madmaxoft** [comment]
ToLua++ could handle the dependency, but we don't want to export the base class.

I'm trying a slightly better version of my original approach, without the preprocessor guards.

**Comment by ElNounch** [comment]
Superseded by https://github.com/cuberite/cuberite/pull/3329

**Pull request closed without merging**
