### PR TITLE
PieceStructures generator: Fixed wrong merge conflict resolution.

### PR DESCRIPTION
**Pull request by madmaxoft**
Also improved reporting messages.
Ref.: http://forum.mc-server.org/showthread.php?tid=2256

### CODE REVIEW

**Comment by Seadragon91** [comment]
Again a deadlock, hehe nice hit.

**Comment by madmaxoft** [comment]
Weird thing is, when I copy the seed to my local instance of the server, it works without any problems. I wonder what's going on there.

**Comment by Seadragon91** [comment]
I had around 3 pull requests, who deadlocked. Tested all the seeds local and had no problem with them. I just say, it's something like a race-condition.

**Comment by madmaxoft** [comment]
Rebased and merged.

**Pull request merged**
