### PR TITLE
Changed allocation of smart pointers via make_xxx

### PR DESCRIPTION
**Pull request by bibo38**
Like the title says.
I don't know, if I've catched them all. So it's only related to #2068

### CODE REVIEW

**Comment by SphinxC0re** [comment]
looks okay, so far.

**Comment by tigerw** [comment]
Pokémon

**Comment by SphinxC0re** [comment]
Oh, @tigerw you and your memes :laughing:

**Comment by tigerw** [comment]
Oh you

**Comment by SphinxC0re** [comment]
It is mergeable altough it doesn't solve #2068 completely

**Pull request merged**
