### PR TITLE
Don't set entity world twice

### PR DESCRIPTION
**Pull request by mathiascode**
https://github.com/cuberite/cuberite/issues/4582#issuecomment-608401321

### CODE REVIEW

**Comment by mathiascode** [comment]
Need to investigate further.

**Comment by bearbin** [comment]
Is this still a WIP?

**Comment by mathiascode** [comment]
Seems like all checks passed this time, so should be ready.

**Comment by tigerw** [comment]
Wait, but AddEntity only queues the entity to be added later on in the tick thread, are we sure nothing depends on the "pending" world being set and available immediately?

**Comment by tigerw** [comment]
I guess we are sure then.

**Comment by tigerw** [comment]
Should be ok. The entity isn't (shouldn't) be touched/ticked before added to a world, so that moment when m_World is null or uninitialised when an entity has just been birthed cannot matter. Also DoMoveToWorld sets the destination pre-emptively, so no worries there.

**Pull request merged**
