### PR TITLE
Added IsBlockFence method to defines.h

### PR DESCRIPTION
**Pull request by SphinxC0re**

### CODE REVIEW

**Comment by worktycho** [comment]
I don't like adding deadcode to the server. I'll merge if we have something using this.

**Comment by SphinxC0re** [comment]
@SafwatHalaby mentioned it in #2795. He implemented it himself in cPath but thought that it might not be the right place for it

**Comment by worktycho** [comment]
@safwat, if you are willing to rebase your pr to use this one, ill merge it.

**Comment by SafwatHalaby** [comment]
Wouldn't cBlockInfo be the right place?

**Comment by SafwatHalaby** [comment]
@worktycho done.

**Pull request merged**
